### ISSUE TITLE
Truncated coordinates

### ISSUE THREAD

**Issue by deviloper** [potree/PotreeConverter#105]
When I try to convert las files with UTM coordinates it seems the converter is truncating higher values losing precision on output points (e.g. 701362.56 becomes 701362 and 4485513.72 becomes 4485510). What i can see in converted point cloud is that points are lying on flat lines and these lines are parallel to the axis.

I think there is a problem like floating point overflow somewhere in the converter.

Here is a screenshot:
![2015-02-02 21_15_28-viewer](https://cloud.githubusercontent.com/assets/5602328/6113043/a6d3bebe-b094-11e4-8092-06b9cc9e96ea.png)

**Comment by m-schuetz** [comment]
Hi! Are you using the newest version of the converter? 
( http://potree.org/downloads/PotreeConverter/PotreeConverter_2014.12.30.zip )

This one should output data/*.bin files and as far as I remember already support huge coordinates.

If you already do, it would be helpful if you could send me a sample of your original as well as converted data along with your potree directory. 

As a workaround, you can try to output to LAS or LAZ files instead:
```PotreeConverter.exe data.las --output-format LAZ ```
and use the lion_laz.html file as template.

**Comment by deviloper** [comment]
I found I was using the previous version of the converter, now it seems to work! 
Thank you Markus!
