### ISSUE TITLE
Build issue on Ubuntu 12.04 x64 (2015/02/15 - develop branch)

### ISSUE THREAD

**Issue by sanak** [potree/PotreeConverter#106]
I encountered the following error when building the current `develop` branch (https://github.com/potree/PotreeConverter/commit/1c1221cb804085061d623f9776612a0adb1310a4) on Ubuntu 12.04 x64.
<pre>
/srv/tools/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp: In constructo                                          r 'PTXPointReader::PTXPointReader(std::string)':
/srv/tools/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:83:57: error:                                           use of deleted function 'std::basic_fstream<char>& std::basic_fstream<char>::ope                                          rator=(const std::basic_fstream<char>&)'
In file included from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:0:
/usr/include/c++/4.6/fstream:761:11: error: 'std::basic_fstream<char>& std::basi                                          c_fstream<char>::operator=(const std::basic_fstream<char>&)' is implicitly delet                                          ed because the default definition would be ill-formed:
/usr/include/c++/4.6/fstream:761:11: error: use of deleted function 'std::basic_                                          iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<c                                          har>&)'
In file included from /usr/include/c++/4.6/fstream:40:0,
                 from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:
/usr/include/c++/4.6/istream:774:11: error: 'std::basic_iostream<char>& std::bas                                          ic_iostream<char>::operator=(const std::basic_iostream<char>&)' is implicitly de                                          leted because the default definition would be ill-formed:
/usr/include/c++/4.6/istream:774:11: error: use of deleted function 'std::basic_                                          istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char                                          >&)'
/usr/include/c++/4.6/istream:57:11: error: 'std::basic_istream<char>& std::basic                                          _istream<char>::operator=(const std::basic_istream<char>&)' is implicitly delete                                          d because the default definition would be ill-formed:
/usr/include/c++/4.6/istream:57:11: error: use of deleted function 'std::basic_i                                          os<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)'
In file included from /usr/include/c++/4.6/ios:45:0,
                 from /usr/include/c++/4.6/istream:40,
                 from /usr/include/c++/4.6/fstream:40,
                 from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:
/usr/include/c++/4.6/bits/basic_ios.h:64:11: error: 'std::basic_ios<char>& std::                                          basic_ios<char>::operator=(const std::basic_ios<char>&)' is implicitly deleted b                                          ecause the default definition would be ill-formed:
/usr/include/c++/4.6/bits/ios_base.h:791:5: error: 'std::ios_base& std::ios_base                                          ::operator=(const std::ios_base&)' is private
/usr/include/c++/4.6/bits/basic_ios.h:64:11: error: within this context
In file included from /usr/include/c++/4.6/fstream:40:0,
                 from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:
/usr/include/c++/4.6/istream:774:11: error: use of deleted function 'std::basic_                                          ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char                                          >&)'
In file included from /usr/include/c++/4.6/istream:41:0,
                 from /usr/include/c++/4.6/fstream:40,
                 from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:
/usr/include/c++/4.6/ostream:57:11: error: 'std::basic_ostream<char>& std::basic                                          _ostream<char>::operator=(const std::basic_ostream<char>&)' is implicitly delete                                          d because the default definition would be ill-formed:
/usr/include/c++/4.6/ostream:57:11: error: use of deleted function 'std::basic_i                                          os<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)'
In file included from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:0:
/usr/include/c++/4.6/fstream:761:11: error: use of deleted function 'std::basic_                                          filebuf<char>& std::basic_filebuf<char>::operator=(const std::basic_filebuf<char                                          >&)'
/usr/include/c++/4.6/fstream:69:11: error: 'std::basic_filebuf<char>& std::basic                                          _filebuf<char>::operator=(const std::basic_filebuf<char>&)' is implicitly delete                                          d because the default definition would be ill-formed:
/usr/include/c++/4.6/streambuf:790:7: error: 'std::basic_streambuf<_CharT, _Trai                                          ts>::__streambuf_type& std::basic_streambuf<_CharT, _Traits>::operator=(const __                                          streambuf_type&) [with _CharT = char, _Traits = std::char_traits<char>, std::bas                                          ic_streambuf<_CharT, _Traits>::__streambuf_type = std::basic_streambuf<char>]' i                                          s private
/usr/include/c++/4.6/fstream:69:11: error: within this context
/srv/tools/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp: In member fun                                          ction 'void PTXPointReader::scanForAABB()':
/srv/tools/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:99:51: error:                                           use of deleted function 'std::basic_fstream<char>::basic_fstream(const std::basi                                          c_fstream<char>&)'
In file included from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:0:
/usr/include/c++/4.6/fstream:761:11: error: 'std::basic_fstream<char>::basic_fst                                          ream(const std::basic_fstream<char>&)' is implicitly deleted because the default                                           definition would be ill-formed:
/usr/include/c++/4.6/fstream:761:11: error: use of deleted function 'std::basic_                                          iostream<char>::basic_iostream(const std::basic_iostream<char>&)'
In file included from /usr/include/c++/4.6/fstream:40:0,
                 from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:
/usr/include/c++/4.6/istream:774:11: error: 'std::basic_iostream<char>::basic_io                                          stream(const std::basic_iostream<char>&)' is implicitly deleted because the defa                                          ult definition would be ill-formed:
/usr/include/c++/4.6/istream:774:11: error: use of deleted function 'std::basic_                                          istream<char>::basic_istream(const std::basic_istream<char>&)'
/usr/include/c++/4.6/istream:57:11: error: 'std::basic_istream<char>::basic_istr                                          eam(const std::basic_istream<char>&)' is implicitly deleted because the default                                           definition would be ill-formed:
/usr/include/c++/4.6/istream:57:11: error: use of deleted function 'std::basic_i                                          os<char>::basic_ios(const std::basic_ios<char>&)'
In file included from /usr/include/c++/4.6/ios:45:0,
                 from /usr/include/c++/4.6/istream:40,
                 from /usr/include/c++/4.6/fstream:40,
                 from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:
/usr/include/c++/4.6/bits/basic_ios.h:64:11: error: 'std::basic_ios<char>::basic                                          _ios(const std::basic_ios<char>&)' is implicitly deleted because the default def                                          inition would be ill-formed:
/usr/include/c++/4.6/bits/ios_base.h:788:5: error: 'std::ios_base::ios_base(cons                                          t std::ios_base&)' is private
/usr/include/c++/4.6/bits/basic_ios.h:64:11: error: within this context
In file included from /usr/include/c++/4.6/fstream:40:0,
                 from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:
/usr/include/c++/4.6/istream:57:11: error: use of deleted function 'std::basic_i                                          os<char>::basic_ios(const std::basic_ios<char>&)'
/usr/include/c++/4.6/istream:774:11: error: use of deleted function 'std::basic_                                          ostream<char>::basic_ostream(const std::basic_ostream<char>&)'
In file included from /usr/include/c++/4.6/istream:41:0,
                 from /usr/include/c++/4.6/fstream:40,
                 from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:
/usr/include/c++/4.6/ostream:57:11: error: 'std::basic_ostream<char>::basic_ostr                                          eam(const std::basic_ostream<char>&)' is implicitly deleted because the default                                           definition would be ill-formed:
/usr/include/c++/4.6/ostream:57:11: error: use of deleted function 'std::basic_i                                          os<char>::basic_ios(const std::basic_ios<char>&)'
/usr/include/c++/4.6/ostream:57:11: error: use of deleted function 'std::basic_i                                          os<char>::basic_ios(const std::basic_ios<char>&)'
In file included from /usr/include/c++/4.6/fstream:40:0,
                 from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:
/usr/include/c++/4.6/istream:774:11: error: use of deleted function 'std::basic_                                          ios<char>::basic_ios(const std::basic_ios<char>&)'
In file included from /srv/tools/PotreeConverter/PotreeConverter/src/PTXPointRea                                          der.cpp:1:0:
/usr/include/c++/4.6/fstream:761:11: error: use of deleted function 'std::basic_                                          ios<char>::basic_ios(const std::basic_ios<char>&)'
/usr/include/c++/4.6/fstream:761:11: error: use of deleted function 'std::basic_                                          filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)'
/usr/include/c++/4.6/fstream:69:11: error: 'std::basic_filebuf<char>::basic_file                                          buf(const std::basic_filebuf<char>&)' is implicitly deleted because the default                                           definition would be ill-formed:
/usr/include/c++/4.6/streambuf:782:7: error: 'std::basic_streambuf<_CharT, _Trai                                          ts>::basic_streambuf(const __streambuf_type&) [with _CharT = char, _Traits = std                                          ::char_traits<char>, std::basic_streambuf<_CharT, _Traits>::__streambuf_type = s                                          td::basic_streambuf<char>]' is private
/usr/include/c++/4.6/fstream:69:11: error: within this context
/srv/tools/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp: In member fun                                          ction 'bool PTXPointReader::doReadNextPoint()':
/srv/tools/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:216:65: error:                                           use of deleted function 'std::basic_fstream<char>& std::basic_fstream<char>::op                                          erator=(const std::basic_fstream<char>&)'
make[2]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PTXPointReader.                                          cpp.o] Error 1
make[1]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/all] Error 2
make: *** [all] Error 2
</pre>

**Comment by anttiviljami** [comment]
+1 here, now in master branch

**Comment by m-schuetz** [comment]
Will fix it later today. Seems like an incorrect usage of fstream that wasn't caught by Visual Studio 2012 compiler. More of that in https://github.com/potree/PotreeConverter/issues/115

**Comment by anttiviljami** [comment]
Thanks! I'd be glad to help with testing. Running 14.04 latest here

**Comment by nmgeek** [comment]
+1 in master branch

Below is the first error but there are many more:

.../PotreeConverter/PotreeConverter/src/PTXPointReader.cpp: In constructor ‘PTXPointReader::PTXPointReader(std::string)’:
.../PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:83:18: error: use of deleted function ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’
     this->stream = fstream(*(this->currentFile), ios::in);
                  ^
In file included from .../PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:0:

**Comment by potree** [comment]
Hi!

Please check the develop branch. Its been fixed there!
