### ISSUE TITLE
Bug when convertin LAS file without color (only intensity)

### ISSUE THREAD

**Issue by ghgr** [potree/PotreeConverter#110]
When converting a LAS file with only intensity data, the resulting octree is completely black (even after doing "las2las -i pointcloud.las -scale_rgb_up", since the r,g,b, values are 0).

Nevertheless, when converting an ASCII file with format -f xyzi everything runs fine.

The problem seems to be in the file BINPointWriter.hpp:65 (branch master). Since I have a HUGE pointcloud in LAS (10^9+ points) with only intensity information (R=G=B=0), and it's too big for CloudCompare to "Convert scalar to RGB", I needed to patch the file BINPointWriter.hpp.

On line 65 of BINPointWriter.hpp:
- unsigned char rgba[4] = {point.x, point.y, point.z, 255};
+ unsigned char rgba[4] = {point.intensity, point.intensity, point.intensity, 255};

I would propose a patch, but I am not sure how to deal when there is BOTH rgb and intensity information (should I take RGB on priority? or the intensity? or should I merge both, although it seems kind of redundant?).

**Comment by potree** [comment]
Hi!

Same problem has been mentioned here: https://github.com/potree/PotreeConverter/pull/107

I'm going to add support for intensity and other attributes in the next 1 or 2 weeks.


As a workaround you can try to convert to las or laz output:

```
PotreeConverter.exe data.las --output-format LAS
PotreeConverter.exe data.las --output-format LAZ
```

This will produce las/laz instead of bin files. You can then adapt the lion_laz.html file to load the converted point cloud.
LAS needs more space than the default BIN. 
LAZ requires a lot less space but more CPU and RAM to uncompress.

**Comment by m-schuetz** [comment]
Work in Progress: 
https://github.com/potree/potree/commit/29b6a9eda2a388d16035e2c3a74a2baef4fb81fa https://github.com/potree/PotreeConverter/commit/8f2a927b66a421ba2aa2f446777a5131e6bf421d

It is now possible to specify attributes that should be stored in the bin files. 
```--output-attributes RGB INTENSITY CLASSIFICATION```
default is just RGB

TODO:
* Check performance of BinaryLoader. I think it got slower with the code for parsing variable types of attributes
* Enable all available attributes in the "Materials" drop down list. At the moment, intensity and classification are only shown with --output-format LAS or LAZ

**Comment by m-schuetz** [comment]
It'd be neat if BinaryLoader would do the loading in a parallel thread.

**Comment by m-schuetz** [comment]
BinaryLoader uses WebWorker threads now: https://github.com/potree/potree/commit/0a12ad7ab28e894dd63ea2ca63d62f500e462d8d

Works very smoothly now that the main thread no longer has to do the loading.

**Comment by pogilon** [comment]
How can I load "Time" field from .LAS files?
