### ISSUE TITLE
las mime type

### ISSUE THREAD

**Issue by joemcglinchy** [potree/PotreeConverter#121]
Hi, 

This is a great software package! well done. 

I am unable to load the LAS example. I am guessing .las needs to be added as a MIME type, but what is the type to be added? I needed to do the same on my server for .hrc (BIN files) and specified .hrc/json to get it working.

Thanks,
Joe

**Comment by potree** [comment]
Hello Joe,

Unfortunately I don't know much about mime types. las and hrc files are both binary files so according to [this](http://stackoverflow.com/questions/6783921/which-mime-type-to-use-for-a-binary-file-thats-specific-to-my-program)  you should probably use ```application/octet-stream```

**Comment by joemcglinchy** [comment]
thanks, that works!

**Comment by joemcglinchy** [comment]
When I copy the project over to my web server, I see an error in the web console saying "Uncaught ReferenceError: LASFile is not defined" occuring on line 659 of potree.js, how to remedy?

**Comment by potree** [comment]
Propably missing some dependencies. When using las or laz files, you need these 3 includes:

```
<script src="../libs/plasio/js/laslaz.js"></script>
<script src="../libs/plasio/vendor/bluebird.js"></script>
<script src="../build/js/laslaz.js"></script>
```

**Comment by joemcglinchy** [comment]
Awesome, thank you again. Especially for the quick reply.
