### ISSUE TITLE
The generated website with 1.1 has bad urls

### ISSUE THREAD

**Issue by s093294** [potree/PotreeConverter#124]
My point clouds do not load, due to erros where urls do not exists like the example given below. 

http://sinnovations.blob.core.windows.net/points/test4/resources/pointclouds/1km_6206_643.laz/data/r//r.laz 404 (The specified blob does not exist.)

Looks like in `url = this.pcoGeometry.octreeDir + "/" + this.getHierarchyPath() + "/" + this.name;` that getHierarchyPath returns paths with suffix "/", and therefore the path has two "//"

**Comment by m-schuetz** [comment]
Interesting. The double "//" has been there for a long time but  that's the first time I hear about it causing problems. Maybe it's the server configuration that does not accept double dashes.

**Comment by s093294** [comment]
Could be that I am using Microsoft Azure blob storage to host generated data. Its not that common yet in the GIS community.

**Comment by s093294** [comment]
Also noticed that with output set to laz, then the generated website do not include the needed las js files.

About the double slash, i just remembered that I used the previously version without problem on azure blob storage. I think its related to the new Hierarchy that was added. `this.getHierarchyPath()`

**Comment by m-schuetz** [comment]
> Also noticed that with output set to laz, then the generated website do not include the needed las js files

Yes, I just uploaded http://potree.org/downloads/PotreeConverter/PotreeConverter_1.1.1.zip to fix this.

I'll fix the "//" tomorrow.

**Comment by s093294** [comment]
Cool. Awesome stuff btw.

I have 200km2 lidar data available that I would like to turn into potree format. Its already provided in a grid. I looked at all the documentation / examples that i could find, but was not able to figure out if its a trivial task to generate the potree  Hierarchy  in parrallel.

I have a algorithm service that enables me to very quickly scale and run many command line jobs. So i would be able to use potreeconverter on each grid element. I wonder if its possible to then combine the results from each job after.

Do you have any other place (google groups or similar?) where questions like above would be better to take up then here in the issue tracker?

**Comment by m-schuetz** [comment]
Fixed the double slashes: https://github.com/potree/potree/commit/2caa4246949744457da8d944f45f7190060cd0c4

> Do you have any other place (google groups or similar?) where questions like above would be better to take up then here in the issue tracker?

Not yet, I'll think about it

> I have 200km2 lidar data available that I would like to turn into potree format. Its already provided in a grid. I looked at all the documentation / examples that i could find, but was not able to figure out if its a trivial task to generate the potree Hierarchy in parrallel.
> I have a algorithm service that enables me to very quickly scale and run many command line jobs. So i would be able to use potreeconverter on each grid element. I wonder if its possible to then combine the results from each job after.

Parallel conversion is not possible, yet. Parallel conversion and merging afterwards is something I thought about but I haven't had the time, yet.

**Comment by m-schuetz** [comment]
Just generated this group: 
https://groups.google.com/forum/#!forum/potree

**Comment by s093294** [comment]
Cool. Parallel conversion would be awesome.  I will see if the forum gets any usage.

**Comment by m-schuetz** [comment]
It will take some time until I can start with that, though.
In the meantime I'll try to improve the current process. The last commits to the develop branch nearly doubles performance for me but they're not thouroghly tested, yet.

**Comment by s093294** [comment]
No worries. I am just giving voice to what would be beneficial for us :) 

Thanks for using your time on this cool project.
