### ISSUE TITLE
Performance improvements / crash

### ISSUE THREAD

**Issue by potree** [potree/PotreeConverter#127]
dev branch currently crashes at 705m points

```
INDEXING: 704,000,000 points processed; 218,720,470 points written; 4,256.57 seconds passed
reading D:\dev\pointclouds\opentopography\CA13_SAN_SIM\CA13_data\ot_35120B4423D_1.laz
INDEXING: 705,000,000 points processed; 219,067,746 points written; 4,263.86 seconds passed
reading D:\dev\pointclouds\opentopography\CA13_SAN_SIM\CA13_data\ot_35120B4424A_1.laz
```

could be because of the file ot_35120B4424A_1.laz

**Comment by m-schuetz** [comment]
Crash fixed: https://github.com/potree/PotreeConverter/commit/5b93480908abd6f545587a8c85a01e27a388b69c#diff-392a4d52f359b4e46ca0594f0b804563R102

Was caused by points lying at the max bounds of the bounding box.
