### ISSUE TITLE
Incremental Conversion

### ISSUE THREAD

**Issue by m-schuetz** [potree/PotreeConverter#138]
Implement incremental conversion.
i.e. it should be able to add a new point cloud tile to an already finished conversion.

Things to consider:
- Projection. What if the new point cloud has a different kind of projection?
- Would be nice if the source could be identified for each point. i.e. point[0] was added during the first conversion at [timestamp1], point[1] was added during the second, incremental conversion add [timestamp2]

More thoughts on this @dkastl @sanak ?

**Comment by sanak** [comment]
> Projection. What if the new point cloud has a different kind of projection?

About projection, I think that it is not necessary to consider projection difference.
(If a new data(*.las) projection is different from processed data one, it should be translated by las2las .etc.)

> Would be nice if the source could be identified for each point. i.e. point[0] was added during the first > conversion at [timestamp1], point[1] was added during the second, incremental conversion add [timestamp2]

About timestamp, I am worried that it causes increasing data size.
(Although, I don't know how much bytes are necessary to store timestamp for 1 point...)
Also, some measurement system records laser data from moving object (airplane, vehicle .etc)
by short interval timestamp, so 1 las file includes various timestamp actually in that case.

In my opinion, 2D map tile's "layer" concept may be better to manage long interval
(like yearly) timestamp data.
(I mean "layer" like the following link's `<tileset_name>@<grid_name>`.)
http://mapserver.org/mapcache/services.html

My proposal is as follows:

1. Add "layer" lookup to "cloud.js". (layer number "0" is default.)
<pre>
:,
layers: {
    0: "2014 year data",
    1: "2015 year data"
},
</pre>
2. Add "layer" folders to "data" folder.
<pre>
data
  +- 0 ... layer-0 folder
    +- r
      +- :
  +- 1 ... layer-1 folder
    +- r
      +- :
</pre>

https://github.com/potree/PotreeConverter/issues/12#issuecomment-61464830
> For incremental conversion, there needs to be a function that can resize the octree and reorders the points accordingly.

By the way, about resizing the octree, I think that specifying "max boundary box" as argument
will solve this effectively (not only for development, but also for processing time).
In case of 2D map tiling, resizing or shifting tile is quite rare case.

**Comment by cnyinfei** [comment]
hi, this is my solution:
1. align the bounding boxes. same coordination results same bounding box and sparse cell.
2. multiple octree support. if newly added points outside of old bounding box, add these points to new octree. otherwise update to existing nodes.
3. in potree.pointcloudoctree.update, if the visible geometry extends current bounding box, request neighbor octree.

not implement yet. ;)

**Comment by m-schuetz** [comment]
First successfull incremental conversion(experimental): https://github.com/potree/PotreeConverter/commit/c0dbc434a5d88af8278b25ddee8cc418228489ba

> About projection, I think that it is not necessary to consider projection difference.
(If a new data(*.las) projection is different from processed data one, it should be translated by las2las .etc.)

Yes, the user will have to make sure both sources are in the same coordinate reference system.

> About timestamp, I am worried that it causes increasing data size.
(Although, I don't know how much bytes are necessary to store timestamp for 1 point...)
Also, some measurement system records laser data from moving object (airplane, vehicle .etc)
by short interval timestamp, so 1 las file includes various timestamp actually in that case.

1 byte would be sufficient to store 256 different timestamps. Could be an optional property in case someone wants it. It would also make it possible to remove or replace points with a specific timestamp from the conversion. 

> By the way, about resizing the octree, I think that specifying "max boundary box" as argument
will solve this effectively (not only for development, but also for processing time).
In case of 2D map tiling, resizing or shifting tile is quite rare case

Yes! The commit is doing that now. The bounding box can be specified during the first conversion with the  ```--aabb "minx miny minz maxx maxy maxz"``` argument. The second conversion then adds to the data using the previously specified bounding box.

**Comment by sanak** [comment]
Okay, thanks for information!
I will try to test `incremental_conversion` branch from tomorrow.

**Comment by m-schuetz** [comment]
Ok! You may have to use the potree develop branch to check the results. Both are experimental, just send me a message if you experience difficulties.

**Comment by s093294** [comment]
Came to think of another nice usecase that could be nice to have. For the national data we have in denmark I can download a really huge set of laz (n) files that are each 1km by 1km. Would be rather cool if I could use the converter tool to process them individual to an output folder x_i. 

Then with another tool merge two output folders x_i and x_(i*2+1) to x_(n+i) and this way recursive merge all of it to a large set. 

Would be able to process large sets really fast (given one have cores/pcs enough).

Would something like that be possible given the spec?

**Comment by potree** [comment]
Nlesc did something like this with a previous potreeconverter release. I'm on mobile so i can't give you a link bit you should find it when you search for massive potree converter. They've released a page with the converted ahn2 dataset consisting of 640 billion points.

Incremental conversion is now possible btw. The readme for potree converter contains an example for the initial conversion with an aabb argument and subsequent conversions with the --incremental flag.

**Comment by s093294** [comment]
Thanks. found it. https://github.com/NLeSC/Massive-PotreeConverter

Will see if it works for me

**Comment by potree** [comment]
Good luck! May have to modified for potreeConverter 1.3 though

**Comment by zahed65** [comment]
Hi, I have a laser file with the extension las in the volume of 800 GB, I output with potreeconverter version 2.0.2 , it gives me an error.
I turned this file into smaller pieces and got output. Now i want to merge but i do not know with what command
