### ISSUE TITLE
Use Non-static data member initializers

### ISSUE THREAD

**Issue by cvvergara** [potree/PotreeConverter#150]
@m-schuetz said:
"Non-static data member initializers" and I'd like to use that, if possible:
http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2008/n2756.htm

In point.h:
default values should be 255 for r,g,b,a and 0 for the rest

**Comment by m-schuetz** [comment]
I'll do that one myself in the rewrite branch!
Let's keep the develop branch compatible with older gcc / Visual Studio versions for now.

**Comment by m-schuetz** [comment]
done. liking this very much.
