### ISSUE TITLE
Dynamic Octree without filtering

### ISSUE THREAD

**Issue by deviloper** [potree/PotreeConverter#153]
I'd like to convert a point cloud without point filtering. I think Potree Converter should calculate the number of levels dinamically during conversion pushing the unconverted points to new nested levels. Is it possible? The user should just specify spacing on the first level..

**Comment by m-schuetz** [comment]
This is actually done already in develop or incremental branch. Neither octree depth (-l) nor spacing (-s) have to be specified anymore. If octree depth isn't specified, all points are converted and the octree depth is expanded as needed.
However, the branches are in an experimental state. I plan to merge them to master within the next 2 weeks.

**Comment by deviloper** [comment]
Thank you, this is a very useful feature!


Il 30/08/2015 10:28, Markus Schütz ha scritto:

**Comment by m-schuetz** [comment]
Done with Potree 1.3 release

**Comment by deviloper** [comment]
Great!
