### ISSUE TITLE
PotreeConverter.exe - Entry Point Not Found Error

### ISSUE THREAD

**Issue by JohnNPS8** [potree/PotreeConverter#160]
Hello,

I can't seem to get the newest converter (1.3) to run.  I get this error when I run PotreeConverter.exe

![screenshot233](https://cloud.githubusercontent.com/assets/11506509/9853210/8392b4be-5ad0-11e5-8285-68fcb035c84d.jpg)

I humbly admit my technical ignorance, but I never had this issue on previous iterations, which still seem to work.  Thanks!

**Comment by m-schuetz** [comment]
Hi,

According to this source it may be because you have an old version of the VC++ redestributable installed: http://www.tuniac.org/forum/viewtopic.php?t=102

Try to install the redistributable from here: https://www.microsoft.com/de-de/download/details.aspx?id=48145

Let me know if it works!

**Comment by JohnNPS8** [comment]
Yes, that worked!  Thank you.  

Just crushed a test point cloud out in 5 minutes (145m points to 41m).  Love the new EDL setting, it really helps define the objects!

**Comment by m-schuetz** [comment]
Great! Send me a link when you're putting something online!
