### ISSUE TITLE
1.3 release is not working

### ISSUE THREAD

**Issue by donnyv** [potree/PotreeConverter#161]
I think something is missing from the 1.3 release. It throws this error when i run this.
PotreeConverter.exe 225345_ARL.las -o E:\Temp\Potree_test -p PotreeTest

![image](https://cloud.githubusercontent.com/assets/2224189/9933957/7dd0dcba-5d1c-11e5-874c-e70c18eb736d.png)

I tried the same command with 1.2 and it works fine.

**Comment by m-schuetz** [comment]
Hi, same issue as this: https://github.com/potree/PotreeConverter/issues/160

The 64bit VC2015 distributable from microsoft has to be installed. You can get it here: https://www.microsoft.com/de-de/download/details.aspx?id=48145

**Comment by donnyv** [comment]
Oooooh...I see, Thanks
