### ISSUE TITLE
Why c++14?

### ISSUE THREAD

**Issue by mojovski** [potree/PotreeConverter#168]
Iam having issue compiling the converter. None of my machines has c++14 support yet (using gcc 4.8.x). Is it possible to downgrade this requirement? 
Of course in case the integration of C++14 is not critical.

**Comment by mojovski** [comment]
i guess because laszip is using it?

**Comment by potree** [comment]
It's not because of laszip but because C++11 and C++14 have some nice features that make coding more fun. Please upgrade to gcc 4.9 to compile the latest PotreeConverter.

**Comment by gitunit** [comment]
@mojovski just change to "-std=c++1y" and it should compile
