### ISSUE TITLE
Bad Potree conversion?

### ISSUE THREAD

**Issue by jcurru** [potree/PotreeConverter#170]
Hello. I have created a potree structure using potree 1.3.1, but I think that the conversion is not correct. Here you have a screenshot:

![image](https://cloud.githubusercontent.com/assets/15331938/10742768/287ef116-7c2f-11e5-8ce3-bb28bcdadefc.png)

Another screenshot from a different software

![image](https://cloud.githubusercontent.com/assets/15331938/10742786/43806f08-7c2f-11e5-94e3-288973c3486a.png)

In the first image, you can see, in the center of each "cube", the name of the loaded LAS. It is a 2D software, so different levels overlap. But there are regions of the same level having a very different resolution (point spacing). Please see another screen shot showing the original data at the same region:

![image](https://cloud.githubusercontent.com/assets/15331938/10742846/a20c3480-7c2f-11e5-8798-177911f93449.png)

It's a ver dense LAS, so the points look as lines.

Thanks!

**Comment by m-schuetz** [comment]
Interesting. Would it be possible for you to send me a part of the data for which this problem occurs as well as the command you've used to convert it?
And node r062 has no more child nodes?

**Comment by jcurru** [comment]
Hello, Markus.

Thanks for your answer. Of course I can.

The LAS file is 54Mb weight (4,5M b compressed)..
I send it separately by email.

And the command is:

PotreeConverter.exe LiDARejemplo.las -o C:\PC_2 -s 2 --scale 0.01 --output-format LAS --overwrite (converter version 1.3.1).

But the same problem araised with:

PotreeConverter.exe LiDARejemplo.las -o C:\PC_2 -s 2 -l 5 --scale 0.01 --output-format LAS (converter version 1.3).

I don't know if r062 has specifically more children, but I guess so, because it's a 5 level potree.
As you will see, the problem exists in other places of the LAS.
Maybe the high density of the LAS is part of the problem.

In other hand, I have found another problem: using the same LAS with the same arguments but scale = 0.001 (instead of 0.01) the result is really strange: all the points (which in origin have latitudes of 4.400.000, more or less), are assigned (in the potree structure) a latitude near to -2.000.000. It seems to be also a problem of the converter.

**Comment by m-schuetz** [comment]
I've had some luck with these parameters:

```
\PotreeConverter.exe D:\temp\LiDARejemplo\LiDARejemplo.las -o D:\temp\test -p ejemplo --output-format LAZ --overwrite --scale 0.005
```

And it's also important to set size type from "Adaptive" to "Fixed". The latest major change to the conversion does not fare well with adaptive point size, it seems. 

I'm getting the fine lines with full details, like this:

![image](https://cloud.githubusercontent.com/assets/6705073/10771385/be28d670-7cf0-11e5-8325-dc7bdb01aaa7.png)

I'll have to investigate why --scale 0.001 does not work. 0.005 basically gives you a coordinate precision of 5mm.

**Comment by jcurru** [comment]
"And it's also important to set size type from "Adaptive" to "Fixed"."

I don't see any option to set this in your last converter version.

2015-10-27 21:24 GMT+01:00 Markus Schütz <notifications@github.com>:

> I've had some luck with these parameters:
>
> \PotreeConverter.exe D:\temp\LiDARejemplo\LiDARejemplo.las -o D:\temp\test -p ejemplo --output-format LAZ --overwrite --scale 0.005
>
> And it's also important to set size type from "Adaptive" to "Fixed". The
> latest major change to the conversion does not fare well with adaptive
> point size, it seems.
>
> I'm getting the fine lines with full details, like this:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/6705073/10771385/be28d670-7cf0-11e5-8325-dc7bdb01aaa7.png>
>
> I'll have to investigate why --scale 0.001 does not work. 0.005 basically
> gives you a coordinate precision of 5mm.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/potree/PotreeConverter/issues/170#issuecomment-151633281>
> .
>



-- 
José Antonio Carmena Flores

Aule Actividades SLU
Gerente
www.aule3d.com

**Comment by m-schuetz** [comment]
If you've used the -p option to automatically generate a page you can change it in the generated examples/xxx.js file
If you've adapted the examples/viewer.js file you can do it there: https://github.com/potree/potree/blob/aedb4caa2c4e9d71d53512a1bd30cd543a1f0eb0/examples/viewer.html#L88

**Comment by m-schuetz** [comment]
Found out now why --scale 0.001 does not work.

In las/laz, coordinates are stored as ```(coordinate - offset) / scale```.
Offset is always zero in PotreeConverter when writing to las/laz files. If coordinates are very large and divided by a very low scale, the result will be very large and cause an integer overflow.

Solution: I'll have to add an offset that transforms coordinates towards to origin. 

/ping @rapidlasso (to let you know about this bug in PotreeConverter)

**Comment by jcurru** [comment]
Glad to hear you 've found the problem.
Indeed, my latitude 4.400.000, more or less.
So it's 4.400.000.000 at 0.001 scale
2^32 = 4.294.967.296.
But LAS longs are signed, so the maximum is 2.147.483.648

Et voilá, you are right!

Thanks!!

(Waiting for your anser to the other question (same level, many more
points))

2015-10-28 19:50 GMT+01:00 Markus Schütz <notifications@github.com>:

> Found out now why --scale 0.001 does not work.
>
> In las/laz, coordinates are stored as (coordinate - offset) / scale.
> Offset is always zero in PotreeConverter when writing to las/laz files. If
> coordinates are very large and divided by a very low scale, the result will
> be very large and cause an integer overflow.
>
> Solution: I'll have to add an offset that transforms coordinates towards
> to origin.
>
> /ping @rapidlasso <https://github.com/rapidlasso> (to let you know about
> this bug in PotreeConverter)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/potree/PotreeConverter/issues/170#issuecomment-151952056>
> .
>



-- 
José Antonio Carmena Flores

SRM Consulting SL
www.srmconsulting.es

**Comment by rapidlasso** [comment]
Look in the code of LASlib what '-auto_reoffset' does to pick a useful
offset.

**Comment by jcurru** [comment]
Thanks, Markus.

Are you going to apply that algorithm to generate your potree LAS files?
Otherwise, we find it impossible to use your potree converter technology
for our large, remote LAS dataset, because they should be re-created using
the calculated offset.

Regards.


2015-10-29 1:44 GMT+01:00 Martin Isenburg <notifications@github.com>:

> Look in the code of LASlib what '-auto_reoffset' does to pick a useful
> offset.
> On Oct 29, 2015 2:50 AM, "Markus Schütz" <notifications@github.com> wrote:
>
> > Found out now why --scale 0.001 does not work.
> >
> > In las/laz, coordinates are stored as (coordinate - offset) / scale.
> > Offset is always zero in PotreeConverter when writing to las/laz files.
> If
> > coordinates are very large and divided by a very low scale, the result
> will
> > be very large and cause an integer overflow.
> >
> > Solution: I'll have to add an offset that transforms coordinates towards
> > to origin.
> >
> > /ping @rapidlasso <https://github.com/rapidlasso> (to let you know about
> > this bug in PotreeConverter)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/potree/PotreeConverter/issues/170#issuecomment-151952056
> >
> > .
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/potree/PotreeConverter/issues/170#issuecomment-152041942>
> .
>



-- 
José Antonio Carmena Flores

Aule Actividades SLU
Gerente
www.aule3d.com

**Comment by m-schuetz** [comment]
Hello,

Regarding your problems, the bug and the email correspondence.
Please be aware that this is a free and open source project and I'm investing a lot of my time improving it. There are few sponsors for which I am very thankful, but a lot of it is me doing work for free and for fun. Chasing bugs isn't the fun part of it but obviously necessary. 
I will try to help if someone has a problem or encounters a bug
but I'd like to ask you not to rush me or expect me to provide full time support for free.
If you need a swifter support or certain features, consider writing me for a support deal.

I will upload a fixed version of the converter in the next few days or at some point in the next week.

Apart from the precision issue, the conversion looks correct to me for Potree 1.3.
Some nodes are split further because they contain more points than other nodes.
You have to include the child nodes as well to get full details. 


Best Regards,
Markus

**Comment by jcurru** [comment]
Markus

First I want to say that my English is not very good and I use the Google
translator. Surely you find some slightly strange expressions.

Sorry if I gave the impression of trying to abuse your kindness. Nothing is
further from my intentions. At first I created an issue on GitHub, but then
you answered me by email and I thought you preferred to talk in this way.

We find it very interesting that you are open to a possible deal of
support. If we do not achieve our goals with your current converter, we
will present you an application.

Otherwise, we're glad we could contribute to finding the problem of
overflow due to the data offset, and will work to find a solution to those
nodes that are not expanded into sub-nodes, and look strange when viewed in
two dimensions.

Again we apologize, and we thank the amazing job you did.

Best regards


2015-10-29 9:54 GMT+01:00 Markus Schütz <notifications@github.com>:

> Hello,
>
> Regarding your problems, the bug and the email correspondence.
> Please be aware that this is a free and open source project and I'm
> investing a lot of my time improving it. There are few sponsors for which I
> am very thankful, but a lot of it is me doing work for free and for fun.
> Chasing bugs isn't the fun part of it but obviously necessary.
> I will try to help if someone has a problem or encounters a bug
> but I'd like to ask you not to rush me or expect me to provide full time
> support for free.
> If you need a swifter support or certain features, consider writing me for
> a support deal.
>
> I will upload a fixed version of the converter in the next few days or at
> some point in the next week.
>
> Apart from the precision issue, the conversion looks correct to me for
> Potree 1.3.
> Some nodes are split further because they contain more points than other
> nodes.
> You have to include the child nodes as well to get full details.
>
> Best Regards,
> Markus
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/potree/PotreeConverter/issues/170#issuecomment-152116154>
> .
>



-- 
José Antonio Carmena Flores

SRM Consulting SL
www.srmconsulting.es
