### ISSUE TITLE
Storing projection

### ISSUE THREAD

**Issue by m-schuetz** [potree/PotreeConverter#174]
Projection has to be stored in cloud.js, like

```
{
    projection: "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
}
```

No idea how to transform GeoTiff projection that is often stored in las/laz files automatically to proj4 projection strings.
Probably best to provide a conversion argument for the projection, like

```
.\PotreeConverter.exe <input> -o <outdir> --projection "+proj=utm +zone=10 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
```

For older conversions newly converted data sets without projection, it will be possible to manually add the projection afterwards.

**Comment by qdnguyen** [comment]
any idea how to add proj4 in potree to do conversion?
thx,
