### ISSUE TITLE
Can't Build LAStools on Amazon Linux Operating System

### ISSUE THREAD

**Issue by pihish** [potree/PotreeConverter#175]
I am running an Amazon Linux distro machine and I am getting an error message when running _make_ on the last step of setting up LAStools.  The specific message is:

`c++: error: unrecognized command line option '-std=c++14'`

My gcc version (downloaded and installed through Amazon's distro repo) is 4.8.3 and from the looks of it, it seems to not have the option to compile in c++14.  

Is there anyway to get around this problem here?  Or if not, is there a built version of PotreeConverter I can download onto my machine so I don't have to locally compile it?

**Comment by m-schuetz** [comment]
I believe you'll need at least gcc 4.9.

There is only a windows 64bit build available since I'm not quite familiar with handling binary releases on linux. If you can't update gcc, you can try to compile PotreeConverter 1.2 instead. It's likely slower but potree 1.3 (and the coming 1.4) are backwards compatible with output from PotreeConverter 1.2.

**Comment by talkster5** [comment]
I know this thread is a little old but I just thought I would confirm that you do need gcc 4.9. I built this on Friday on CentOS 7 and it took quite a bit of work but I will try and get a step by step blog post up this week to hopefully make it easier for anyone else in future. 

I had quite a lot of trouble getting gcc 4.9 from any trusted repo so I ended up compiling it from source which isn't too difficult but does take a little bit of time.

**Comment by pihish** [comment]
@talkster5 Never did find a solution to compile in Linux so a post on how you did it would be helpful!

**Comment by jamescorbett** [comment]
You have to use a recent version of gcc, I had to use docker and use Ubuntu:15.10. 

See https://github.com/skytales/PotreeConverter/blob/feature/docker/Dockerfile if it's of any help.

**Comment by Park13** [comment]
Sorry, I have been a bit occupied with other things over the past couple of weeks however I have now finished putting together the list of commands. I just need to write it up into something more meaningful over the weekend and then I will be able to send it over to you.

**Comment by pihish** [comment]
@park13 Hey did you have a chance to put up the guide over the weekend?

**Comment by Park13** [comment]
I am getting there with it but I've had a few projects land on my desk that I wasn't expecting. I will ensure it is up tomorrow though.

**Comment by pihish** [comment]
@Park13 Gracias

**Comment by Park13** [comment]
Hi,
The guide is now online:

https://www.vooservers.com/technical-blog/potree-converter-install/
