### ISSUE TITLE
Missing boost environment variables: cannot build PotreeConverter

### ISSUE THREAD

**Issue by umbe1987** [potree/PotreeConverter#178]
I downloaded boost 1.50.0 and extracted the tar.bz2 into /home/umberto.
After following the instructions in the README.md, I am trying to run the command "cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=~/dev/workspaces/lastools/master/LASzip/dll -DLASZIP_LIBRARY=~/dev/workspaces/lastools/master/LASzip/build/src/liblaszip.so ..".
The terminal gives me this error:

CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1131 (message):
  Unable to find the requested Boost libraries.

  Unable to find the Boost header files.  Please set BOOST_ROOT to the root
  directory containing Boost or BOOST_INCLUDEDIR to the directory containing
  Boost's headers.
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)

-- Boost_INCLUDE_DIRS: Boost_INCLUDE_DIR-NOTFOUND
-- Boost_LIBRARY_DIRS: 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /home/umberto/PotreeConverter/master/PotreeConverter

-- Configuring incomplete, errors occurred!
See also "/home/umberto/PotreeConverter/master/build/CMakeFiles/CMakeOutput.log".

How do I set BOOST_ROOT to the root directory containing Boost or BOOST_INCLUDEDIR to the directory containing Boost's headers? Do I have to do anything after extracting the boot .tar.bz2? Or should I place it in a different dir?
My directories are now:
/home/lastools;
/home/PotreeConverter;
/home/boost_1_58_0.

Working on Ubuntu 14.04, with gcc.-4.9, g++-4.9, boost_1.58.0.

**Comment by cvvergara** [comment]
@umbe1987 
When I want a particular location I do: 
cmake -DBOOST_ROOT:PATH=/usr/local/boost_1_58_0  <other flags>
So for your case maybe this could work
cmake -DBOOST_ROOT:PATH=/home/boost_1_58_0 <other flags>

**Comment by umbe1987** [comment]
Thanks. I added this path but still it cannot find the libraries. Not sure where to look for... Maybe I tried adding also -DBOOST_LIBRARYDIR:PATH=/home/umberto/boost_1_58_0/libs/ but that didn't the trick
The terminal output (without adding -DBOOST_LIBRARYDIR) now is:

CMake Error at /usr/share/cmake-2.8/Modules/FindBoost.cmake:1131 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /home/umberto/boost_1_58_0

  Could not find the following Boost libraries:

          boost_system
          boost_thread
          boost_filesystem
          boost_program_options
          boost_regex

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:8 (find_package)


-- Boost_INCLUDE_DIRS: /home/umberto/boost_1_58_0
-- Boost_LIBRARY_DIRS: 
-- Configuring incomplete, errors occurred!
See also "/home/umberto/PotreeConverter/master/build/CMakeFiles/CMakeOutput.log".

**Comment by umbe1987** [comment]
Is it possible that the library names in my /home/umberto/boost_1_58_0/libs folder are different than what they should be expected? I have "system", "thread", "filesystem",  "program_options", and "regex" instead of the same names with the prefix "boost_" as shown in the output error. Would this be the problem?
Also, if I debug the cmake it gives me "BOOST_LIBRARYDIR = /home/umberto/boost_1_58_0/libs/", which is correct, but the error is the same as the one in the previous comment.

**Comment by m-schuetz** [comment]
Unfortunately I'm realy bad at this build-stuff so I can't realy help you there. :|
I think for me the boost dependencies either worked out of the box on linux or I may have downloaded boost 1.58 using the package managers. 
I'd appreciate if you'd post a how to if you manage to solve this.

**Comment by m-schuetz** [comment]
Instead of downloading the package yourself, try something like apt-get, yum or whichever packet manager is available on your system. 
http://stackoverflow.com/questions/12578499/how-to-install-boost-on-ubuntu

**Comment by umbe1987** [comment]
Thanks a lot!
I removed everything and followed the steps from the beginning installing boost with "sudo apt-get install libboost-all-dev" and it worked!
Only one thing: what's the meaning of the very last BUILD instruction "copy ./PotreeConverter/resources/page_template to your binary working directory? (I am not an expert of informatics terms...)

**Comment by m-schuetz** [comment]
This is for if you want to use PotreeConverter with the --generate-page (-p) option. 
In that case, a potree page will be generated using the contents of the page_template directory. With binary working directory, the directory containing the executable is meant.

**Comment by lukehatfield** [comment]
I had the same error on a mac. I use hombrew as my package manager, so the following command worked for me: `brew install boost`.
Thanks for the post!
