### ISSUE TITLE
Flushing error prepend.bin

### ISSUE THREAD

**Issue by pxp44** [potree/PotreeConverter#183]
Hi,

I'm having issues with: 

FLUSHING: ERROR: boost::filesystem::remove: 
The process can not access the file because it is used by another proces: C:/Apps/PotreeConverter/temp_data/export_3/temp/prepend.bin"

Using: 

PotreeConverter.exe "D:/DemoData/x3.las" -o C:/Apps/PotreeConverter/temp_data/export_3 --overwrite 

Sometimes it quits halfway, sometimes at 90% and sometimes i have no issues at all. 

With larger las files (5Gb) it fails often.

System: i7 3Ghz, 48Gb, 1Tb SSD Windows 10 Pro x64

What can i do to prevent this?

Greetings,

Erwin

**Comment by VictorLambert42** [comment]
Hi,
I'm having the same issues.
I want to use large las files and it fails every time, my system is also Windows 10 Pro x64.
Is there any solution?
Thanks
Victor

**Comment by orzundher** [comment]
Hello,
i'm having the same problem with Windows 7 Enterprise x64

Best Greetings,
Cesar
