### ISSUE TITLE
Features lost on larger dataset, even though all points written to output

### ISSUE THREAD

**Issue by tldv** [potree/PotreeConverter#190]
I have a dataset sized 0.351x0.351x595 in resolution of 0.001, split (along the third dimension) into 4 ply files (due to memory constraints from processing), ~700M points total. I run PotreeConverter 1.3.1, sending it the directory of the data, with levels and spacing unspecified. When 1-3 files are in the folder (so third dimension spans up to 446) everything looks fine, but when all four files are in the folder, so dataset spans full 595 in third dimension, features appear to be lost, even though output says 100% was written to output.

Do I have to do anything different when converting with larger datasets, like manually specifying levels or spacing? It seems all the data is there/written, so am I missing something from a visualization setting? I tried increasing max points to 4M, but solve the problem. 

Thanks in advance for the help.

**Comment by m-schuetz** [comment]
Hi, can you post a screenshot with what you get in potree and what you get in another app where it works as expected? If not here, send me an email to mschuetz@potree.org

Also, check the cloud.js file if scale is 0.001. If it is not, try to convert with the --scale 0.001 argument.

**Comment by tldv** [comment]
Good catch on the scale in cloud.js, it is 0.01 when all four files are in the folder. I'll try manually specifying scale. Thanks a lot for the tip. Cheers.

**Comment by tldv** [comment]
Works great, thanks.
