### ISSUE TITLE
Project OpenStreetMap or Bing maps on point clouds

### ISSUE THREAD

**Issue by Gitbear90** [potree/PotreeConverter#193]
How can I project OpenStreetMap or Bing maps on my point clouds? Or show my point cloud toghter with some imagery or map. Just to have a sense of where my point cloud is located on a map. There is an example at: http://potree.org/demo/experimental/potree_map_projections/examples/viewer_proj.html

**Comment by vudn54** [comment]
very nice

**Comment by MamatsasDhmhtrhs** [comment]
To enable the minimap on Potree v1.6 you just have to **add the projection to your cloud** or to edit the "**cloud.js**" of your converted cloud and add the projection there.

**Comment by nikhilbv** [comment]
@MamatsasDhmhtrhs Hi, I am new to the georeferencing side. So will you provide the steps how to get point cloud referenced and how to get the minimap in potree please

**Comment by MamatsasDhmhtrhs** [comment]
Hello @nikhilbv, 
There are plenty of ways to georeference your point cloud.

To geo-reference the point cloud, you may use the 'Point-pair based alignement' tool, see:
[https://www.cloudcompare.org/doc/wiki/index.php?title=Align](url)
You can use this tool with only one cloud and input the reference points (e.g. GPS ones) manually. 

Another option is to create a cloud with the GCPs and use it as second cloud. You can find  also videos on youtube (simply search for 'cloudcompare georeference' on youtube.

Also it depends on the method you used to capture/create your point cloud if you created it by you own. 

To check if your cloud is georeferenced open it with CloudCompare click on 'Point list picking' and click on your cloud. If you see something like that:

![untitled](https://user-images.githubusercontent.com/39695281/43159983-8e398246-8f8c-11e8-9fc4-c82210af2265.jpg)

The pointcloud is georeferenced.

The minimap will be automaticaly be enabled if you insert the georeference system to your cloud
-or-
You can edit the "cloud.js" file from your converted pointcloud and add the projection there as shown below in PROJ.4 format

![2](https://user-images.githubusercontent.com/39695281/43160592-47ac8cae-8f8e-11e8-9afb-0a61abc081b9.jpg)

(Thats the GGRS87 / Greek Grid. If you want to find yours go to [https://epsg.io/](url))

Thats all.

**Comment by MamatsasDhmhtrhs** [comment]
@nikhilbv 
I can't see your output. Try to reupload it.
What do you mean when you say basetiles ?

Take a look at [https://mamatsasdhmhtrhs.github.io](url) source code

**Comment by nikhilbv** [comment]
Hi,


​Base tiles are the tiles in the minimap. Mine is plain and your minimap
has base tiles.
I am struck with getting that in my minimap.
​

**Comment by nikhilbv** [comment]
Hi,

As I am new to georeferencing side, I did not notice that I had got base
tiles in minimap.
But the code which you gave is for EPSG 4326 or WGS 84 coordinates. How do
I change it to EPSG 3857 or WGS 84 / Pseudo-Mercator coordinates.
Because I have only  EPSG 3857 or WGS 84 / Pseudo-Mercator coordinates as
references.

**Comment by MamatsasDhmhtrhs** [comment]
The last 2 lines from my previous messenge

(Thats the GGRS87 / Greek Grid. If you want to find yours go to https://epsg.io/)

😁

**Comment by ianh88** [comment]
Used epsg.io to grab the proj4 text for the coordinate system in my pointcloud however it is putting the minimap location to a different part of the world, typically the northern hemisphere.

Anyone know if this struggles with minus values?

**Comment by MamatsasDhmhtrhs** [comment]
@ianh88
This shouldn't have any problem with north/ south hemisphere. Are you sure you did the search correctly?

**Comment by ianh88** [comment]
> @ianh88
> This shouldn't have any problem with north/ south hemisphere. Are you sure you did the search correctly?

Hi, sorry missed this one. Yes figured it out. The UTM formatting just wasn't correct. Working fine now.

I would like to have the tiles off by default in the minimap. Do you know of a way to ensure the toggle is set to off in the potree.js file?

ifh88

**Comment by MamatsasDhmhtrhs** [comment]
@ianh88
Just delete the projection from "cloud.js" of the specific cloud. The cloud will remain georeferenced but the tile won't be visible in the minimap.
