### ISSUE TITLE
map coordinates

### ISSUE THREAD

**Issue by giancan** [potree/PotreeConverter#195]
Dear all,
I try to use the new version of potreeconverter to have my georeferenced cloud converted.
I tried several coordinate formats but the map on the top-left side of the automatically generated page does not seem to work and it shows nothing. If I click somewhere, it asks to select tiles with control+left click, but this doesn't seem to work again.
Can you provide some information on how this feature works and what the accepted coordinate format?
Thanks,
G.

**Comment by spatialhast** [comment]
@giancan what OS you use (Windows or Linux)? Can you provide link on example your data? I try convert and describe how I do this.

**Comment by giancan** [comment]
I'm on windows and I use the precompiled binary for 64bit pc.
The following is a working link with an example of cloud converted with that software.
http://photogrammetry.ims.forth.gr/siemens/pointclouds/test3.html

Regards,
G.

**Comment by spatialhast** [comment]
@giancan in convertion command need defined 'projection' parameter in proj4 format (PotreeConverter.exe --help). For example, my las data in EPSG:3857 projection and I need use command like:
`PotreeConverter.exe D:\test\input.las -o C:\OSGeo4W\apache\htdocs\potree\test -p index --projection "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs"`

**Comment by giancan** [comment]
Perfect, this was what I was missing.
Thanks

**Comment by spatialhast** [comment]
@giancan please tell me which camera you used to capture photos and software to create a point clouds?

**Comment by giancan** [comment]
@spatialhast 
I have a Nikon d5200 with a prime lens. I used vsfm+cmpmvs and cloudcompare (all free software) for refinements.
Consider that the cloud I show is a very draft version (not "refined") and downsampled.
Potree is the perfect completion of the dataset and it has no competitors for data sharing, considering also the special features of measurement, cross-sections and visualization.
Cheers,
G.

**Comment by spatialhast** [comment]
@giancan thanks for the info! Yes, potree is good solution.
