### ISSUE TITLE
Issue building on OSX

### ISSUE THREAD

**Issue by nickponline** [potree/PotreeConverter#200]
After building LASzip it creates a `liblaszip.dylib` not a `liblaszip.so`. Then after running

```
cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=../../master/LASzip/dll -DLASZIP_LIBRARY=../../master/LASzip/build/src/liblaszip.so ..
make
```

It fails with:

ld: library not found for -l../..//master/LASzip/build/src/liblaszip.so

**Comment by yuwenhui** [comment]
Can I change `-DLASZIP_LIBRARY=../../master/LASzip/build/src/liblaszip.so` to `-DLASZIP_LIBRARY=../../master/LASzip/build/src/liblaszip.dylib` ?
