### ISSUE TITLE
Trying to improve intensity scale color visualization

### ISSUE THREAD

**Issue by umbe1987** [potree/PotreeConverter#203]
Hi.
I am converting a LAS file with PotreeConverter which has INTENSITY values ranging 2048-2303.
The commands I am using are:
`PotreeConverter.exe myfile.las -f xyzi --intensity-range 2048 2303 -o c:\xampp
\htdocs\my_potree -p test -a INTENSITY --scale 0.0001`

`PotreeConverter.exe myfile.las -f xyzi --intensity-range 2048 2303 -o c:\xampp
\htdocs\my_potree -p test --output-format LAS --source LAS`

When I look in the browser, in both cases I see only white dots (maybe some are imperceptibly super-light gray). Is there a way to apply a sort of strecth or similar to somehow improve my data visualization?
Below are a screenshot of the webpage and the specs of the file I am using as input for the conversion (as coming out from [lasinfo](http://www.cs.unc.edu/~isenburg/lastools/download/lasinfo_README.txt)).
Any answer wuold be greatly appreciated!

![potreeissue](https://cloud.githubusercontent.com/assets/15016826/16798999/f2623948-48ee-11e6-8623-c20075b7b76d.JPG)

reporting all LAS header entries:
  file signature:             'LASF'
  file source ID:             0
  global_encoding:            0
  project ID GUID data 1-4:   00000000-0000-0000-0000-0000000000
  version major.minor:        1.2
  system identifier:          'LAStools (c) by Martin Isenburg'
  generating software:        'PTS by pointzip 1.0 (120723)'
  file creation day/year:     193/2016
  header size:                227
  offset to point data:       313
  number var. length records: 1
  point data format:          0
  point data record length:   20
  number of point records:    83946699
  number of points by return: 83946699 0 0 0 0
  scale factor x y z:         0.0001 0.0001 0.0001
  offset x y z:               531000 5045000 0
  min x y z:                  530480.2723 5045089.8580 163.0299
  max x y z:                  531386.9692 5045804.0075 248.6524
variable length header record 1 of 1:
  reserved             43707
  user ID              'LAStools'
  record ID            2000
  length after header  32
  description          'by LAStools of Martin Isenburg'
reporting minimum and maximum for all LAS point record entries .
  X            -5197277    3869692
  Y              898580    8040075
  Z             1630299    2486524
  intensity        2048       2303
  return_number       1          1
  number_of_returns   1          1
  edge_of_flight_line 0          0
  scan_direction_flag 0          0
  classification      0          0
  scan_angle_rank     0          0
  user_data           0          0
  point_source_ID     0          0
overview over number of returns of given pulse: 83946699 0 0 0 0
histogram of classification of points:
        83946699  never classified (0)

**Comment by umbe1987** [comment]
I managed to achieve what I wanted by rescaling the intensity pixes of the point cloud to 0-255 values (actually they were 2048-2303 originally, whose range is exactly 255), and when I ran the command PotreeConverter.exe myfile_rescale.las -f xyzi --intensity-range 1 254 -o c:\xampp\htdocs\my_potree -p test --scale 0.01 --output-format LAS --source LAS`, everything showed up just fine (see image at the bottom).

To rescale the intensity vaòues I did `las2las.exe -i myfile.las" -o myfile_rescale.las -translate_intensity -2048`, which actually subtracts (sums the negative of) 2048 from each intensity value in the point cloud.
I'd rather not closing this issue, as I would like to have the chance that anybody would answer this question:

_What is the `--intensity-range 2048 2303` argument supposed to do (see my original post)?_

To me, it seems it is not forcing the interval in the specified range (the points look all very whitish). My guess is that if values are (e.g.) greater than 255, the interval render the colors in a 0-65536 ramp (or so), no matter the range specified.

![potreeissuesolved](https://cloud.githubusercontent.com/assets/15016826/16831895/d3ebc088-49a7-11e6-935a-531d8ff8fa09.JPG)

**Comment by lehmannwebdev** [comment]
I had a problem with intensity too. Problem was with setting offset and scale. 
When scale was setup incorrect only color/rgb was available in potree (intensity caused error in js console). 

Solution: 

In potree converter source code:
"intensity = 65535 * (actual_val - offset) / scale"

So, in your situation if you want to use 0-256 intensity scale, you need to setup: 
scale = 65535
offset = 2048

and then your intensity values will be scaled for:
2048 = 0
2303 = 255

Btw. If you have 12 bits of intensity number (0 - 4096), then you should set scale = 1048560 and offset = 0.

**Comment by umbe1987** [comment]
@lehmannwebdev Thanks for the reply. Anyway, why should scale be = 1048560? Does not a 12bit depth mean 4096 maximum combinations of 1s and 0s (2^12)? I am asking because I am quite interested in understanding this aspect.

**Comment by lehmannwebdev** [comment]
12 bit = max 4096 combinations but in potree converter is hardcoded '65535' (16bit)
so, if you want to get intensity from 0 to 255 and calculating function is:
"intensity = 65535 * (actual_val - offset) / scale"

then 
0 = 65535 * (0 -0) / 1048560
255 = 65535 * (4096 -0) / 1048560

**Comment by umbe1987** [comment]
@lehmannwebdev Thanks for clarify! I am now closing the issue.

**Comment by avstjohn** [comment]
> In potree converter source code:
> "intensity = 65535 * (actual_val - offset) / scale"

This seems to be a problem still, and I'm not finding this line of code anywhere in PotreeConverter. Where is this?

**Comment by przemyslaw-szustak** [comment]
Here you are:
[https://github.com/potree/PotreeConverter/blob/86d7aaf09af8796df20bbaa7cee13c2db0a3bedf/PotreeConverter/include/XYZPointReader.hpp#L185](
https://github.com/potree/PotreeConverter/blob/86d7aaf09af8796df20bbaa7cee13c2db0a3bedf/PotreeConverter/include/XYZPointReader.hpp#L185)
