### ISSUE TITLE
Cannot Install and Run on Ubuntu

### ISSUE THREAD

**Issue by EArgen** [potree/PotreeConverter#204]
I've been scouring everywhere, but I can't seem to properly install/use PotreeConverter on a fresh installation of Ubuntu.

Is there a step by step guide somewhere to getting this setup?

For reference, I tried this among other things and it gave me errors at the end:
https://github.com/potree/PotreeConverter/issues/180

I'm also not sure why it is being built in the /usr/bin/ directory, as I have to keep using sudo in order to do anything despite those instructions not including it. I'm not incredibly familiar with Ubuntu, so that might just be on me.

I also did try the guide on the front page, and although I didn't get errors, I could not activate it with anything I tried. There's a chance it was installed correctly but I have no idea how to use it.

Thank you for your help!

**Comment by davijo** [comment]
Hi,

We just made a dev version for docker of the dev branch for https://pointscene.com .

You can set the converter up and running with docker (https://www.docker.com):
install docker:
https://docs.docker.com/engine/installation/linux/ubuntulinux/

and then pull:
docker pull pointscene/potreeconverter

and run (change paths accordingly):
docker run -v /local/path:/data pointscene/docker-potreeconverter PotreeConverter /data/lasdir/ -o /data/output --output-format LAS --scale 0.01 --overwrite

**Comment by EArgen** [comment]
Oh wow, that version looks pretty slick. Thank you, I'll try it now and let you know what happens.

Is there a web hosting application you recommend? XAMPP works great on Windows, but since I'll be ending up in a linux environment with this I'm not sure which to pick for easy startup and testing with Potree.

**Comment by m-schuetz** [comment]
Apache and Nginx are good choices for linux. Both available through package managers. I found apache usually relatively hassle free to set up. It's also the web server used by XAMPP.
https://httpd.apache.org/

**Comment by EArgen** [comment]
Ok, so I'm not sure I'm doing the last part, the run docker part, correctly. I have my test data in Downloads and it is simply called test.las

I tried the following command which did not work:

docker run -v /Downloads/test.las pointscene/docker-potreeconverter PotreeConverter /data/lasdir -o /data/output --output-format LAS --scale 0.01 --overwrite

It returned the error:
Unable to find image 'pointscene/docker-potreeconverter:latest' locally. Then it tried to pull it, and failed.

I'm sure I'm messing something simple up. Thoughts?

**Comment by davijo** [comment]
The mount path seems missing and the docker image was wrong:
https://docs.docker.com/engine/tutorials/dockervolumes/
![image](https://cloud.githubusercontent.com/assets/8625487/16993436/16b42a96-4eac-11e6-9704-362fabe1b6c2.png)

Maybe this helps (-v needs the local and docker folders):
docker run -v /PATH_TO_LOCAL_DATA:/data pointscene/potreeconverter PotreeConverter /data/las_folder -o /data/output --output-format LAS --scale 0.01 --overwrite

**Comment by EArgen** [comment]
Here is my output, it doesn't seem to be grabbing the file no matter what way I try, but at least it's trying now.

docker run -v /Downloads:/data pointscene/potreeconverter PotreeConverter /data/las_folder -o /data/output --output-format LAS --scale 0.01 --overwrite
== params ==
source[0]:         	/data/las_folder
outdir:            	/data/output
spacing:           	0
diagonal-fraction: 	200
levels:            	-1
format:            	
scale:             	0.01
pageName:          	
output-format:     	LAS
projection:        	

AABB: 
min: [3.40282e+38, 3.40282e+38, 3.40282e+38]
max: [-3.40282e+38, -3.40282e+38, -3.40282e+38]
size: [3.40282e+38, 3.40282e+38, 3.40282e+38]

cubic AABB: 
min: [3.40282e+38, 3.40282e+38, 3.40282e+38]
max: [6.80565e+38, 6.80565e+38, 6.80565e+38]
size: [3.40282e+38, 3.40282e+38, 3.40282e+38]

spacing calculated from diagonal: 2.94693e+36
closing writer

conversion finished
0 points were processed and 0 points ( -nan% ) were written to the output. 
duration: 0s

**Comment by davijo** [comment]
Good, so the converter is running. Now just fix the paths and you're all set.

Example (
docker run -v /Downloads:/data pointscene/potreeconverter PotreeConverter /data/ -o /data/output --output-format LAS --scale 0.01 --overwrite

**Comment by davijo** [comment]
Good, so the converter is running. Now just fix the paths and you're all set.

Example (you may need to change the paths):
docker run -v /Downloads:/data pointscene/potreeconverter PotreeConverter /data/ -o /data/output --output-format LAS --scale 0.01 --overwrite

If lucky you'll have your output in /Downloads/output

**Comment by EArgen** [comment]
Figured it out, it wouldn't work without the '~' in front of /Downloads:/data. I also changed paths so my terminal was sitting in ~/Downloads#

I also figured out how to target a specific file, correct me if I'm wrong.
File: test.las
Location: Downloads

docker run -v ~/Downloads:/data pointscene/potreeconverter PotreeConverter /data/test.las -o /data/output --output-format LAS --scale 0.01 --overwrite

/data/ appears to represent what is in the Downloads folder. So when this activates it searches for Downloads/test.las, and creates a folder called 'output' also in the Downloads folder to put it into. I think I was confused on what /data/ meant as I'm not too familiar with Linux as I probably should be.

My only question left is that I can't seem to find a PageName like I could with the Windows version. How do I tell Apache how to get the file?

**Comment by davijo** [comment]
Do you mean the html page? I suppose for that you need additional flags for the converter:
-p [ --generate-page ] arg              Generates a ready to use web page with the given name.

**Comment by EArgen** [comment]
So I entered in:

docker run -v ~/Downloads:/data pointscene/potreeconverter PotreeConverter /data/test.las -o /data/output --output-format LAS --scale 0.01 --overwrite -p PageName

It generated an empty html file called 'PageName.html'.

Is it in the wrong spot?

**Comment by EArgen** [comment]
Still haven't been able to figure out why it isn't creating a page like the Windows version of this would. Is there something more I need to do? The page that is created is completely empty with the settings tried above.

**Comment by EArgen** [comment]
Checking in again. Does anyone know what might be causing this issue?

**Comment by calvinmetcalf** [comment]
you need to copy [that folder](https://github.com/potree/PotreeConverter/tree/master/PotreeConverter/resources/page_template) into the working dir

**Comment by jstarsk** [comment]
@calvinmetcalf wich is the working dir. whet you are working with a docker image?

**Comment by calvinmetcalf** [comment]
@jstarsk I honestly don't remember, it's been a year :)  but docker files doe a have a `WORKDIR` command which might be what I war referring to
