### ISSUE TITLE
Docker Resource Page Template Missing

### ISSUE THREAD

**Issue by EArgen** [potree/PotreeConverter#206]
When using Docker with Ubuntu I'm unable to generate a html page as I would with the Windows setup. You can see my input and error below. It seems to process everything just fine, it simply generates an empty page file. Thoughts?

Input:
docker run -v ~/Downloads:/data pointscene/potreeconverter PotreeConverter /data/test.las -o /data/output --output-format LAS --scale 0.01 –overwrite -p PageName

Error:
Source directory .//resources/page_template does not exist or is not a directory.

**Comment by pogilon** [comment]
I dont get the page template even when running the PotreeConverter locally, any ideas?
