### ISSUE TITLE
visualize one of multiple clouds

### ISSUE THREAD

**Issue by giancan** [potree/PotreeConverter#209]
Hi all,
I like the option to process multiple files (from folder) into a single webpage, but is it possible, when the page is loaded, to isolate one cloud or visualize them all one at time?
Say that I convert 2 clouds together: one for the exteriors and one for the interiors of a building. Can I switch on or off any of the two clouds in the webpage?
Thanks

**Comment by jo-chemla** [comment]
In the scene tab of the potree toolbar, you can choose between which cloud you want to display.

**Comment by umbe1987** [comment]
@jo-chemla sounds interesting! I can't fins any scene tab anyway, could you please tell me where it is more precisely? I would really like to try this feature! I have PotreeConverter 1.3.1 for windows.

**Comment by giancan** [comment]
Dear @jo-chemla ,
indeed the option is there, but I don't understand how to "populate" this menu.
Even if I process (for example) all the clouds from one folder with 1 single potreeconverter command, in the generated page I can see only 1 cloud (and nothing under the Scene tab).
Can you provide us with an example, a string that will generate multiple selectable clouds in a single webpage?
Thanks

**Comment by jo-chemla** [comment]
When you generate the Potree webpage, the sidebar shows a scene tab. You just need to generate each cloud independently (run the potreeconverter command twice, once for each point cloud), and add each cloud in the HTML file (just copy and paste the `viewer.addPointCloud("../other_folder/cloud.js");` line, pointing to the second cloud.js file)

**Comment by umbe1987** [comment]
@jo-chemla Thanks for the hint. Anyway, still can't find the scene tab in the webpage... Here is part of the page, with all the buttons and tabs I have. Again I am using Potreeconvertr 1.3.1 in Windows with the argument -p to generate my webpage.
![scene_tab](https://cloud.githubusercontent.com/assets/15016826/18627775/20c76be8-7e5d-11e6-8de3-0b0f79c3a679.PNG)

**Comment by giancan** [comment]
Dear @jo-chemla,
I did try that but I have two main problems.
Despite the fact that my two clouds are perfectly and reciprocally aligned, when loaded into the webpage with viewer.addPointCloud("../other_folder/cloud.js"); for each of the two, I can notice a sensible shit between one and the other, meaning that they are not completely aligned.
Plus, whether I use one single cloud or two or more, the Scene tab in the sidebar is always empty.

Any suggestions?
Thanks,
G.

**Comment by jo-chemla** [comment]
Hi, Try upgrading to the latest PotreeConverter version? Should not lead to any problems. J.

**Comment by giancan** [comment]
I am using already the last version
PotreeConverter 1.4RC2

**Comment by giancan** [comment]
Dear @jo-chemla 
I also noticed something else. I remember that once I managed to visualize a profile (below the area of the pointcloud) when clipping. The page I generate with the above potreeconverter does not show any profile and does not allow me to clip inside or outside (I have the options but although I change them, nothing actually happens).
Any suggestions or possible fix?

**Comment by jingxa** [comment]
hi ! did u know how to solve it ? i want to convert multiple files into one scene, but 
`converter.exe c:\data -o c:\data_conveted -p all`
,this will show all data ,but it only displays one or hiddens all data; 
In scene tab ,this is only one selection ,i found there is more selections when i add 【 viewer.addPointCloud("../other_folder/cloud.js")】into *.html.
that 's not fantastic,
do you have better idea ?
 thank you !
