### ISSUE TITLE
Negeative Point Cloud

### ISSUE THREAD

**Issue by torehovland** [potree/PotreeConverter#212]
Hello , First of all i just want to say thank you for a wonderfull projeckt!

I have a issue : when i use PotreeConverter and open the web site the point cloud is negative. See image
![neg](https://cloud.githubusercontent.com/assets/13959150/18253596/42a6c942-7396-11e6-8f9b-8c2fa65dc247.PNG)
![not-neg](https://cloud.githubusercontent.com/assets/13959150/18253598/48b8063e-7396-11e6-9897-3ed7c8ff7220.PNG)

The screen shot where the collors are corrected i activated negative colors in windows.

**Comment by umbe1987** [comment]
#rgb Seems similar to this.

**Comment by m-schuetz** [comment]
@torehovland did you also use a PTX file as input?

**Comment by torehovland** [comment]
Yes it looks similar
I used .xyz file, but i wil definitely try out the solutionsin the other post!

Thanks!

**Comment by torehovland** [comment]
@m-schuetz No i used .xyz

**Comment by torehovland** [comment]
@m-schuetz i also used : ./PotreeConverter.exe C:/data.xyz-o C:/potree_converted -p pageName

**Comment by torehovland** [comment]
@m-schuetz Do you have any suggestions

**Comment by torehovland** [comment]
I found a work-around

Import the model to Cload-compare and export it as .las.

Than use potree-converter as normal
