### ISSUE TITLE
Black Points / Tiles

### ISSUE THREAD

**Issue by m-schuetz** [potree/PotreeConverter#214]
Sometimes specific tiles or the whole point cloud end up being black.
This issue is caused because the converter reads the first 1000 points from an input file to decide which color range to use (0-255 vs 0-65000) but some files store lots of black colors before the first colors in 65k range appear, therefore making the converter choose a 0-255 range even though points are stored in 65k range. Observed with 350,000 black points before the first colored point.

**Comment by dioutan** [comment]
Hello M-schuetz,

I have same issue, can you help me to resolve it?

Thanks
