### ISSUE TITLE
Very Small Visualization

### ISSUE THREAD

**Issue by EArgen** [potree/PotreeConverter#216]
![image](https://cloud.githubusercontent.com/assets/20545347/18959688/184d8332-8635-11e6-9588-c1baa618e9de.png)

When I use Potree Converter my results are extremely small, and I am unable to zoom in close enough to get a look at the results. If I get too close the cloud simply disappears. Does anyone know why this might be happening?

**Comment by torehovland** [comment]
Have you tried the `--scale` to scale it up?
