### ISSUE TITLE
Can't make classification filter work

### ISSUE THREAD

**Issue by ipasic** [potree/PotreeConverter#224]
Hello, I am trying to use classification filter on the potree page with the point cloud that I previously classified and converted using PotreeConverter. 
Point cloud is displaying fine on the page but I can't make classification filter work correctly. When I try to turn on and off classes it looks like all points are assigned to class "never classified" even though I previously assigned more classes like ground, high vegetation,... 

I checked in different software if it can recognize classes for my point cloud and it always recognizes it fine but in potree page it just doesn't work. I tried also to export .las file from different software and then convert it again but it didn't help.

Probably I am missing something obvious here, maybe there is some step in between that should be done to make it work fine in potree but I didn't find what it is?

**Comment by larsjacquemetton** [comment]
I'm actually experiencing the similar problem. 
I'm creating a .las file using the LASTools txt2las, when I convert the generated las file back to text from las the classification is preserved but it's gone when I run the las file through the PotreeConverter, or at least I'm experiencing the same effect of every point being assigned to the class "never classified"

**Comment by m-schuetz** [comment]
For classification to work, you'll have to convert to a las/laz octree or specify it as an additional attribute to use in the standard bin format. 
i.e., try to convert with one of the following:

    .\PotreeConverter.exe <input> -o <targetDir> -a RGB CLASSIFICATION
    .\PotreeConverter.exe <input> -o <targetDir> --output-format LAS
    .\PotreeConverter.exe <input> -o <targetDir> --output-format LAZ

**Comment by larsjacquemetton** [comment]
Thanks! The first example line you provided worked great for me.

**Comment by ipasic** [comment]
Yes it works for me too like that! Thanks alot :)

**Comment by yuhangch** [comment]
> For classification to work, you'll have to convert to a las/laz octree or specify it as an additional attribute to use in the standard bin format.
> i.e., try to convert with one of the following:
> 
> ```
> .\PotreeConverter.exe <input> -o <targetDir> --output-attributes RGB CLASSIFICATION
> .\PotreeConverter.exe <input> -o <targetDir> -a RGB CLASSIFICATION
> .\PotreeConverter.exe <input> -o <targetDir> --output-format LAS
> .\PotreeConverter.exe <input> -o <targetDir> --output-format LAZ
> ```

Thanks, Is there a way to get  the full help message in PotreeConverter v2.0.2?
