### ISSUE TITLE
can't use Potreeconverter to tranfer ply

### ISSUE THREAD

**Issue by YAMMAY** [potree/PotreeConverter#227]
WARNING: Potree was unable to identify the operating system and as a result, the directory of the executable.
Using current work dir as executable directory. Make sure to run potree inside the directory with the executable to avoid problems.

**Comment by jingxa** [comment]
Hi, it always stops working when i exec " potreeconverter.exe  *.ply -o d:\output - p name"  on win10,i can't understand what your meanings ,can u help me ? thanks !
