### ISSUE TITLE
Issue with .laz files ?

### ISSUE THREAD

**Issue by nazga** [potree/PotreeConverter#231]
Hello,

Am I the only one having trouble with .laz datafiles output ?

I'm using windows binaries:
- pcl.las => PotreeConverter to bin default format = working
- pcl.laz => PotreeConverter to bin default format = working
- pcl.laz => PotreeConverter to laz format = **not working** (--output-format LAZ)

I tried with multiple datasets and the result is always the same, the point cloud is not displaying:
[imgur picture](http://imgur.com/a/usypd)

**Comment by svenstaro** [comment]
Yes, same issue. There even is a helpful JavaScript trace in the console.

**Comment by nazga** [comment]
Yeah, I did not look at the console the first time!
In fact, for some reason, a line from laslaz.js is dropped while converting data.

You can either:
1. Add it by hand at line 208 of laslaz.js from plasio lib folder if you have already processed your data:

> 	var LAZLoader = function(arraybuffer) {
> 		this.arraybuffer = arraybuffer;
> 		
> 		let workerPath = Potree.scriptPath + "/workers/laslaz-worker.js"; #MISSING LINE
> 		this.ww = Potree.workerPool.getWorker(workerPath);
> 
> 		this.nextCB = null;
> 		var o = this;

2. Copy/Past the right laslaz.js file from Potree 1.5RC release to your PotreeConverter folder, in resources\page_template\libs\plasio\js\
