### ISSUE TITLE
Converting LAS 1.4 Files

### ISSUE THREAD

**Issue by ghost** [potree/PotreeConverter#234]
### Issue ###
When I provide the program with a LAS 1.2 file, it converts as expected and looks great in potree.

When  I provide the program with a LAS 1.4 file, it reads the header information and finishes immediately with zero points processed.

### Reproduction ###
I've encountered the same result with PotreeConverter 1.3.1 and the recent 1.5RC versions on Windows 7
    
1.  run PotreeConverter.exe <path/to/LAS_1.4/file>

### Question ###
I understand that the adoption of LAS 1.4 has been slow, however USGS has released official documentation regarding the LAS 1.4 specifications recently. Is support for LAS 1.4 planned in the near future? 

#### program output (LAS 1.4) ####
    C:\Tools\PotreeConverter_1.3.1_win7.x64>PotreeConverter.exe "C:\Users\tpendergras
    == params ==
    source[0]:              C:\Users\tpendergrass\Desktop\TEMP\LAS Test\Santa_Row.las
    outdir:                 C:/Users/tpendergrass/Desktop/TEMP/LAS Test/Santa_Row.las
    spacing:                0
    diagonal-fraction:      250
    levels:                 -1
    format:
    scale:                  0
    pageName:
    output-format:          BINARY
    
    AABB:
    min: [6.14e+06, 1.9425e+06, 122.25]
    max: [6.14125e+06, 1.94375e+06, 860.1]
    size: [1,249.99, 1,249.99, 737.85]
    
    cubic AABB:
    min: [6.14e+06, 1.9425e+06, 122.25]
    max: [6.14125e+06, 1.94375e+06, 1,372.24]
    size: [1,249.99, 1,249.99, 1,249.99]
    
    spacing calculated from diagonal: 8.66018
    READING:  C:\Users\tpendergrass\Desktop\TEMP\LAS Test\Santa_Row.las
    closing writer
    
    conversion finished
    0 points were processed and 0 points ( -na,n(i,nd)% ) were written to the output.
    duration: 0.016s
    
    C:\Tools\PotreeConverter_1.3.1_win7.x64>

According to the lasinfo output, the LAS file I am using was generated from GeoCue LAS Updater.

**Comment by jyoung84** [comment]
That's farther than I got. Processing 1.4 files crashes for me immediately.
