### ISSUE TITLE
Zero points converted (LAS and PLY)

### ISSUE THREAD

**Issue by vadnart1** [potree/PotreeConverter#237]
Hi,  I'm having issues converting large 9GB LAS (4.2GB PLY) file.  Potree responds with "0 points weree processed").  I've used successfully on several other LAS outputs but all were below 4GB.  is this an issue with +9GB LAS file or something else.

Thanks in advance for any help.

Here's the output of PotreeCOnverter  (Windows 10) 

PotreeConverter1.5RC2>potreeconverter "D:\pointcloud\9247\d2_4_g1\9247_ds2_4g1.ply" -q NICE -p "9247ds2-4g1"
== params ==
source[0]:              D:\pointcloud\9247\d2_4_g1\9247_ds2_4g1.ply
outdir:                 D:/pointcloud/9247/d2_4_g1/9247_ds2_4g1.ply_converted
spacing:                0
diagonal-fraction:      200
levels:                 -1
format:
scale:                  0
pageName:               9247ds2-4g1
output-format:          BINARY
projection:

AABB:
min: [3.40282e+38, 3.40282e+38, 3.40282e+38]
max: [-3.40282e+38, -3.40282e+38, -3.40282e+38]
size: [3.40282e+38, 3.40282e+38, 3.40282e+38]

cubic AABB:
min: [3.40282e+38, 3.40282e+38, 3.40282e+38]
max: [6.80565e+38, 6.80565e+38, 6.80565e+38]
size: [3.40282e+38, 3.40282e+38, 3.40282e+38]

spacing calculated from diagonal: 2.94693e+36
closing writer

conversion finished
0 points were processed and 0 points ( -na,n(i,nd)% ) were written to the output.
duration: 0.882s

**Comment by svenstaro** [comment]
You have to give it a LAS with version 1.2 instead of 1.4.

**Comment by Mrvain77** [comment]
I have the same issue with 1.2 LAS. Here is the output, anyone knows whats going wrong? 

D:\Potree1.6>potreeconverter.exe d:\Dropbox (FMT)\FMT TBC\Kynningsrud\Karlskoga\Realworks\project_cloud.las -o D:\Dropbox (FMT)\FMT TBC\Kynningsrud\Karlskoga\Sketchup\potree --generate-page karlskoga
== params ==
source[0]:              d:\Dropbox
source[1]:              (FMT)\FMT
source[2]:              TBC\Kynningsrud\Karlskoga\Realworks\project_cloud.las
outdir:                 D:\Dropbox
spacing:                0
diagonal-fraction:      200
levels:                 -1
format:
scale:                  0
pageName:               karlskoga
projection:

AABB:
min: [3.40282e+38, 3.40282e+38, 3.40282e+38]
max: [-3.40282e+38, -3.40282e+38, -3.40282e+38]
size: [3.40282e+38, 3.40282e+38, 3.40282e+38]

cubic AABB:
min: [3.40282e+38, 3.40282e+38, 3.40282e+38]
max: [6.80565e+38, 6.80565e+38, 6.80565e+38]
size: [3.40282e+38, 3.40282e+38, 3.40282e+38]

spacing calculated from diagonal: 2.94693e+36
closing writer

conversion finished
0 points were processed and 0 points ( -naán(iánd)% ) were written to the output.
duration: 8.629s
