### ISSUE TITLE
Problems with high coordinates rev2

### ISSUE THREAD

**Issue by RyanJWalker** [potree/PotreeConverter#247]
It seems the 1.5RC has the high coordinate value floating point issue manifesting again.  A dataset in the UTM coordinate system, with Northings in the millions, jitters and shakes for a few seconds when the camera is moved.  The same dataset converted with 1.4RC candidate is fine.  It doesn't seem to be truncating values at all, so the point cloud looks normal apart from the jittery screen.
Any thoughts?  
Thanks

**Comment by potree** [comment]
Try to use the 1.5RC potree release instead of generating the page with PotreeConverter. Or you can try the dev branch.
It seems there is an issue with the page that's deployed witht the converter.

**Comment by RyanJWalker** [comment]
Yes, using the latest build of Potree from the main branch fixes this.  This is related to: https://github.com/potree/potree/issues/320
