### ISSUE TITLE
Resource file error

### ISSUE THREAD

**Issue by alee156** [potree/PotreeConverter#249]
OS: Ubuntu 16.04
Installation method: Same as wiki

My working directory has the PotreeConverter executable in it which I use by the ``` ./PotreeConverter ``` command. Everything works, I get my cloud.js file etc. But while I copied the contents of the ./PotreeConverter/resources/page_template by literally doing ``` cp -r ./PotreeConverter/resources/page_template ``` , when using the -p generate html flag I get the following error: 

```
PotreeConverter/PotreeConverter/resources/page_template does not exist or is not a directory.

```
Since my executable is called PotreeConverter it will not let me create a folder called PotreeConverter. I tried changing the name of the executable but I get the same error above just adjusted for the new name.

**Comment by emqiongwu** [comment]
I  have the same problem. Any ideas?

**Comment by fnagel** [comment]
Had the same issue. You need to copy the `resources/page_template` folder in your PotreeConverter executable directory. Make sure the `resources` is on the same level as the executable. I copied the files to my `-o` (output) folder which is wrong.

**Comment by spiladon** [comment]
Had the same issue. Solution: PotreeConverter [-input] -o [-outputDir] -p someName. The outputDir should for example "/home/kristofer/dev/workspaces/PotreeConverter/master/PotreeConverter/resources/page_template/ " or additionaly ".../page_template/pointclouds"

**Comment by spiladon** [comment]
Had the same issue. Solution: PotreeConverter [-input] -o [-outputDir] -p someName. The outputDir should for example "/home/kristofer/dev/workspaces/PotreeConverter/master/PotreeConverter/resources/page_template/ " or additionaly ".../page_template/pointclouds"
