### ISSUE TITLE
Segmentation Fault in Ubuntu

### ISSUE THREAD

**Issue by eokeeffe** [potree/PotreeConverter#25]
Getting a segmentation fault when trying to run the program , seems to happen immediately 

Output:
Segmentation fault (core dumped)

Hardware
Ubuntu 14.04 LTS 64 bit
CMake 2.8

**Comment by Madity** [comment]
I am also facing the same error!
Can you please elaborate on how to work around?
My issue is after compiling, it generated an executable file named "PotreeConverter" in "./build/PotreeConverter/".
Now whenever I try to run using commands mentioned below! Its gives segmentation fault always
![screenshot from 2015-05-12 12 43 18](https://cloud.githubusercontent.com/assets/7779634/7581780/a50b71a0-f8a4-11e4-9feb-df9b783f9577.png)
