### ISSUE TITLE
using scalar field

### ISSUE THREAD

**Issue by giancan** [potree/PotreeConverter#251]
Dear Potree developers,
I have a pointcloud that I want to visualize online (with potreeconverter).
The pointcloud has RGB values and another field with a scalar information (namely the difference from the comparison with a scan of the same object in another moment).
How could I make use of this extra field? I mean, I should I save the cloud and which parameters should I use for conversion? The cloud can be saved as PLY or xyz with RGB and Scalar Field information.
Thanks

**Comment by gbivins** [comment]
I have a similar situation. I have xyz scalar1,scalar2,scalar3, ....scalarN. I'd like to import these as attributes but it's not clear how to do this.

**Comment by pogilon** [comment]
same here

**Comment by pravinshinde825** [comment]
I have almost same situation, I have RGB values and a scalar field. I want to provide option to switch between scalar field and RGB.
