### ISSUE TITLE
English measures

### ISSUE THREAD

**Issue by interiors3d** [potree/PotreeConverter#253]
Is there any option to switch to english measures instead of metric system?

**Comment by interiors3d** [comment]
nobody can help on this?

**Comment by denizhosgor** [comment]
You can add this code to html file. 
After this lines
> viewer.setPointBudget(1*1000*1000);
> viewer.loadSettingsFromURL();

insert this
`viewer.setLengthUnit('in');`

**Values**
Meter = m
Feet = ft
Inch = in

**Comment by interiors3d** [comment]
@denizhosgor 
I tried to insert it but the model didn't load...here is actual code:
		viewer.setPointBudget(1*1000*1000);
		
		document.title = "PotreeViewer";
		viewer.setEDLEnabled(false);

I miss "viewer.loadSettingsFromURL();" code...tried to load it too. But not worked. What's wrong?
Thanks for helping!

**Comment by denizhosgor** [comment]
This code is not necessary "viewer.setPointBudget(110001000);"
You can add only this code "viewer.setLengthUnit('in');"

And 
i have a mistake on this "viewer.setPointBudget(110001000);" 
correct one is "viewer.setPointBudget(1*1000*1000);"

**Comment by denizhosgor** [comment]
1 * 1000 * 1000 ignore spaces

**Comment by interiors3d** [comment]
Is not working..if I add that code the model dosen't show up. I attached the full html file can you please check where is not working?
Thanks a lot

[mpantogn.zip](https://github.com/potree/PotreeConverter/files/1204510/mpantogn.zip)

**Comment by denizhosgor** [comment]
i m using potree 1.5 linux version. i tried to solve the problem but i couldn't. 
On potree 1.5 you can use this code "**viewer.setLengthUnit('in');**"

[index.zip](https://github.com/potree/PotreeConverter/files/1204666/index.zip)

**Comment by interiors3d** [comment]
Ok, will download it and try there. Thanks a lot!
