### ISSUE TITLE
build fails when run 'make' on Ubuntu Server 14.04.5

### ISSUE THREAD

**Issue by spatialhast** [potree/PotreeConverter#255]
Ubuntu Server 14.04.5, PotreeConverter 1.5
gcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
boost: Version: 1.54.0.1ubuntu1

Installation steps:
```
Install Boost / cmake / build-essential
$ sudo apt-get install libboost-dev libboost-system-dev libboost-thread-dev libboost-filesystem-dev libboost-program-options-dev libboost-regex-dev
$ sudo apt-get install cmake build-essential

Install gcc/g++ 4.9
$ sudo add-apt-repository ppa:ubuntu-toolchain-r/test
$ sudo apt-get update
$ sudo apt-get install gcc-4.9 g++-4.9 cpp-4.9
$ gcc --version
$ cd /usr/bin
$ sudo rm gcc g++ cpp
$ sudo ln -s gcc-4.9 gcc
$ sudo ln -s g++-4.9 g++
$ sudo ln -s cpp-4.9 cpp

Install LAStools
$ git clone https://github.com/m-schuetz/LAStools.git
$ cd LAStools/LASzip
$ mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ make

$ git clone https://github.com/potree/PotreeConverter.git
$ cd PotreeConverter
```

when I run command:
`$ sudo make && sudo make install`
I receive error
```
Scanning dependencies of target PotreeConverter
[  9%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/SparseGrid.cpp.o
[ 18%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PointAttributes.cpp.o
[ 27%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/BINPointReader.cpp.o
/home/opengeo/PotreeConverter/PotreeConverter/src/BINPointReader.cpp:6:35: fatal error: experimental/filesystem: No such file or directory
 #include <experimental/filesystem>
								   ^
compilation terminated.
make[2]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/src/BINPointReader.cpp.o] Error 1
make[1]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/all] Error 2
make: *** [all] Error 2
```

How do you install it and run it on Ubuntu Server 14.04.5 (or Ubuntu Server 16.04.2 )?

**Comment by potree** [comment]
Hi, please check the build instructions here: https://github.com/potree/PotreeConverter

You'll need to call cmake for the PotreeConverter too and after that make, without make install.
Cmake will append some flags to the compile and linker commands that hopefully resolves the experimental/filesystem issue. If it doesn't, maybe try a newer version of g++.

**Comment by spatialhast** [comment]
Hi!
now I repeat all installation actions from build instructions but I receive the same error
video: http://fs13.fex.net/get/891424638707/27040512/d3592f8a/Video_001.1.mp4
`gcc (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4`

Then I updated gcc version to `gcc (Ubuntu 5.4.1-2ubuntu1~14.04) 5.4.1 20160904` - and PotreeConverter build succesfully.
gcc 5.4.1 installation on Ubuntu Server 14.04.5:
```
$ sudo add-apt-repository ppa:ubuntu-toolchain-r/test
$ sudo apt-get update
$ sudo apt-get install gcc-5 g++-5
$ sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 60 --slave /usr/bin/g++ g++ /usr/bin/g++-5
```


Thanks!

**Comment by spatialhast** [comment]
when I run command 
`PotreeConverter -i ~/point_cloud/tonnel.xyz -o ~/kh -p index`
I receive error message:
```
...
  --show-skybox
  --material                             RGB, ELEVATION, INTENSITY, INTENSITY_GRADIENT, RETURN_NUMBER, SOURCE, LEVEL_OF_DETAIL
ERROR: invalid material name specified
```
Then after running command with '--material SOURCE' option:
`PotreeConverter -i ~/point_cloud/tonnel.xyz -o ~/kh --material SOURCE -p index`
I receive error message:
`Segmentation fault (core dumped)`

**Comment by pogilon** [comment]
@spatialhast  you should add "--material RGB" if it contains RGB information and it should work. It did with me. Look at the options for --material. Good luck!

**Comment by potree** [comment]
H, should have been usign RGB as the default, will have to check that again.

**Comment by potree** [comment]
--material is now RGB by default in develop.
