### ISSUE TITLE
Build on OS X Fails

### ISSUE THREAD

**Issue by seahawks8** [potree/PotreeConverter#256]
attempting to build 1.31 on OS X.
have installed CMAKE (command line utility), have installed and built LASTOOLS.

fails due to not finding 'experimental/filesystem'

any help would be greatly appreciated. thanks,

`Scanning dependencies of target PotreeConverter
[  8%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/BINPointReader.cpp.o
clang: warning: -Z-reserved-lib-stdc++: 'linker' input unused
clang: warning: -lm: 'linker' input unused
/Users/bettercallsaul/dev/workspaces/potreeconverter/master/PotreeConverter/src/BINPointReader.cpp:6:10: fatal error: 
      'experimental/filesystem' file not found
#include <experimental/filesystem>
         ^
1 error generated.
make[2]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/src/BINPointReader.cpp.o] Error 1
make[1]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/all] Error 2
make: *** [all] Error 2`

**Comment by potree** [comment]
What compiler are you using? Should be working with the

**Comment by seahawks8** [comment]
I have not specified the compiler. Just followed the instructions from the home screen https://github.com/potree/PotreeConverter

I am a bit of a noob. I have installed homebrew and cmake. perhaps this is the issue, the compiler is not specified.

**Comment by seahawks8** [comment]
I am using apple clang 8

-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/bettercallsaul/dev/workspaces/PotreeConverter/master/build

**Comment by michaelchanwahyan** [comment]
sorry to bother you.
how is this issue fixed?
I'm having the same error ...

**Comment by seahawks8** [comment]
no worries, I was using a super old Macbook pro. 2009 I believe.
anyways our older mac's don't support it (OSX version). so the fix was not using a super old OSX.
