### ISSUE TITLE
 Can We install Potree Converter on Ubuntu 16.04 ?  

### ISSUE THREAD

**Issue by ahmadshabbir2468** [potree/PotreeConverter#261]
Hi, 
**Sir I try both branches ? Master & And fix_fstream(https://github.com/anttiviljami/PotreeConverter/tree/fix_fstream)**  
When i uses master branch it throws these error 
**Errors**
[  8%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/SparseGrid.cpp.o
[ 16%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/stuff.cpp.o
In file included from /usr/bin/master/PotreeConverter/src/stuff.cpp:1:0:
/usr/bin/master/PotreeConverter/include/stuff.h:17:35: fatal error: experimental/filesystem: No such file or directory
 #include <experimental/filesystem>
                                   ^
compilation terminated.
PotreeConverter/CMakeFiles/PotreeConverter.dir/build.make:86: recipe for target 'PotreeConverter/CMakeFiles/PotreeConverter.dir/src/stuff.cpp.o' failed
make[2]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/src/stuff.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'PotreeConverter/CMakeFiles/PotreeConverter.dir/all' failed
make[1]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

 **and same When I try to Use ? fixfstream it Throws these Errors** 

[ 85%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/Vector3.cpp.o
[ 92%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PTXPointReader.cpp.o
/var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp: In constructor ‘PTXPointReader::PTXPointReader(std::string)’:
/var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:83:18: error: use of deleted function ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’
     this->stream = fstream(*(this->currentFile), ios::in);
                  ^
In file included from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:0:
/usr/include/c++/4.9/fstream:779:11: note: ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_fstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.9/fstream:779:11: error: use of deleted function ‘std::basic_iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<char>&)’
In file included from /usr/include/c++/4.9/fstream:38:0,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/istream:795:11: note: ‘std::basic_iostream<char>& std::basic_iostream<char>::operator=(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_iostream
           ^
/usr/include/c++/4.9/istream:795:11: error: use of deleted function ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’
/usr/include/c++/4.9/istream:58:11: note: ‘std::basic_istream<char>& std::basic_istream<char>::operator=(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.9/istream:58:11: error: use of deleted function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.9/ios:44:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.9/ios:42:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/bits/ios_base.h:795:5: error: ‘std::ios_base& std::ios_base::operator=(const std::ios_base&)’ is private
     operator=(const ios_base&);
     ^
In file included from /usr/include/c++/4.9/ios:44:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.9/fstream:38:0,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/istream:795:11: error: use of deleted function ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’
     class basic_iostream
           ^
In file included from /usr/include/c++/4.9/istream:39:0,
                 from /usr/include/c++/4.9/fstream:38,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/ostream:58:11: note: ‘std::basic_ostream<char>& std::basic_ostream<char>::operator=(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.9/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>& std::basic_ios<char>::operator=(const std::basic_ios<char>&)’
In file included from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:0:
/usr/include/c++/4.9/fstream:779:11: error: use of deleted function ‘std::basic_filebuf<char>& std::basic_filebuf<char>::operator=(const std::basic_filebuf<char>&)’
     class basic_fstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.9/fstream:72:11: note: ‘std::basic_filebuf<char>& std::basic_filebuf<char>::operator=(const std::basic_filebuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.9/ios:43:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/streambuf:810:7: error: ‘std::basic_streambuf<_CharT, _Traits>& std::basic_streambuf<_CharT, _Traits>::operator=(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       operator=(const basic_streambuf&) { return *this; };
       ^
In file included from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:0:
/usr/include/c++/4.9/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
/var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp: In member function ‘void PTXPointReader::scanForAABB()’:
/var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:99:51: error: use of deleted function ‘std::basic_fstream<char>::basic_fstream(const std::basic_fstream<char>&)’
         fstream stream = fstream(files[i], ios::in);
                                                   ^
In file included from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:0:
/usr/include/c++/4.9/fstream:779:11: note: ‘std::basic_fstream<char>::basic_fstream(const std::basic_fstream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_fstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.9/fstream:779:11: error: use of deleted function ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’
In file included from /usr/include/c++/4.9/fstream:38:0,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/istream:795:11: note: ‘std::basic_iostream<char>::basic_iostream(const std::basic_iostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_iostream
           ^
/usr/include/c++/4.9/istream:795:11: error: use of deleted function ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’
/usr/include/c++/4.9/istream:58:11: note: ‘std::basic_istream<char>::basic_istream(const std::basic_istream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_istream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.9/istream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.9/ios:44:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/bits/basic_ios.h:66:11: note: ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.9/ios:42:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/bits/ios_base.h:792:5: error: ‘std::ios_base::ios_base(const std::ios_base&)’ is private
     ios_base(const ios_base&);
     ^
In file included from /usr/include/c++/4.9/ios:44:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/bits/basic_ios.h:66:11: error: within this context
     class basic_ios : public ios_base
           ^
In file included from /usr/include/c++/4.9/fstream:38:0,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/istream:795:11: error: use of deleted function ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’
     class basic_iostream
           ^
In file included from /usr/include/c++/4.9/istream:39:0,
                 from /usr/include/c++/4.9/fstream:38,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/ostream:58:11: note: ‘std::basic_ostream<char>::basic_ostream(const std::basic_ostream<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_ostream : virtual public basic_ios<_CharT, _Traits>
           ^
/usr/include/c++/4.9/ostream:58:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
In file included from /usr/include/c++/4.9/fstream:38:0,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/istream:795:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
     class basic_iostream
           ^
In file included from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:0:
/usr/include/c++/4.9/fstream:779:11: error: use of deleted function ‘std::basic_ios<char>::basic_ios(const std::basic_ios<char>&)’
     class basic_fstream : public basic_iostream<_CharT, _Traits>
           ^
/usr/include/c++/4.9/fstream:779:11: error: use of deleted function ‘std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)’
/usr/include/c++/4.9/fstream:72:11: note: ‘std::basic_filebuf<char>::basic_filebuf(const std::basic_filebuf<char>&)’ is implicitly deleted because the default definition would be ill-formed:
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
In file included from /usr/include/c++/4.9/ios:43:0,
                 from /usr/include/c++/4.9/istream:38,
                 from /usr/include/c++/4.9/fstream:38,
                 from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:
/usr/include/c++/4.9/streambuf:802:7: error: ‘std::basic_streambuf<_CharT, _Traits>::basic_streambuf(const std::basic_streambuf<_CharT, _Traits>&) [with _CharT = char; _Traits = std::char_traits<char>]’ is private
       basic_streambuf(const basic_streambuf& __sb)
       ^
In file included from /var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:1:0:
/usr/include/c++/4.9/fstream:72:11: error: within this context
     class basic_filebuf : public basic_streambuf<_CharT, _Traits>
           ^
/var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp: In member function ‘bool PTXPointReader::doReadNextPoint()’:
/var/www/html/PotreeConverter/PotreeConverter/src/PTXPointReader.cpp:216:26: error: use of deleted function ‘std::basic_fstream<char>& std::basic_fstream<char>::operator=(const std::basic_fstream<char>&)’
             this->stream = fstream(*(this->currentFile), ios::in);
                          ^
PotreeConverter/CMakeFiles/PotreeConverter.dir/build.make:350: recipe for target 'PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PTXPointReader.cpp.o' failed
make[2]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PTXPointReader.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'PotreeConverter/CMakeFiles/PotreeConverter.dir/all' failed
make[1]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

Kindly Help Me  i try same on Windows and it working fine but on linux it is not working  apart from this problem can you share command how we can run this ON ubuntu

**Comment by ahmadshabbir2468** [comment]
**I switch gcc 4.9  to gcc 5.4 
and Facing this error** 

[  8%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PotreeConverter.cpp.o
In file included from /var/www/html/PotreeConverter/PotreeConverter/src/PotreeConverter.cpp:11:0:
/var/www/html/PotreeConverter/PotreeConverter/include/LASPointReader.h:10:24: fatal error: laszip_api.h: No such file or directory
compilation terminated.

PotreeConverter/CMakeFiles/PotreeConverter.dir/build.make:134: recipe for target 'PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PotreeConverter.cpp.o' failed
make[2]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PotreeConverter.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'PotreeConverter/CMakeFiles/PotreeConverter.dir/all' failed
make[1]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by denizhosgor** [comment]
https://github.com/potree/PotreeConverter/issues/180#issuecomment-321788311
