### ISSUE TITLE
intensityScale not calculated correctly

### ISSUE THREAD

**Issue by headart** [potree/PotreeConverter#263]
The potree converter is not functioning correctly when an Intensity Range is specified. The following line:

https://github.com/potree/PotreeConverter/blob/0c8d08480310d55fa2d2dae500a2771d30e246e9/PotreeConverter/include/XYZPointReader.hpp#L68

needs to be changed to:

https://github.com/potree/PotreeConverter/blob/ce40b22ddf2d9506b2faedb413ee6f51e5d3e9c6/PotreeConverter/include/XYZPointReader.hpp#L66

In it's current implementation the _intensityScale_ does not correctly take into account the lower value when not set to 0. For example when the _intensityRange_ is set as follows **[-4, 4]** and **[2, 4]** it will calculate _intensityScale_ to be **4** when it should in actual fact be **8** and **2** respectively.   

I tried to push this commit about a year ago but it was rejected when it failed the travis-CI test which wasn't implemented when i initially committed: [https://github.com/potree/PotreeConverter/commit/ce40b22ddf2d9506b2faedb413ee6f51e5d3e9c6](url)

**Comment by potree** [comment]
The link leads to "page not found".

I'm a bit confused because ``intensityScale = ìntensityRange[1] - intensityRange[0]``` sounds right to me whereas colorScale is the one that needs to be changed to do the same thing that intensityScale does?

**Comment by headart** [comment]
Sorry about that I seem to have gotten myself confused and the original commit I tried to push didn't go through but seems to have been fixed since then anyway.

the original line used to be this:
`intensityScale = (float)intensityRange[1];`
