### ISSUE TITLE
Segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by spatialhast** [potree/PotreeConverter#265]
I install PotreeConverter on Ubuntu Server 16.04.3 using https://github.com/potree/PotreeConverter/issues/180#issuecomment-322482676 instructions.

When I run conversion command:
`$ PotreeConverter -i vrs.las -o ~/tonnel -p index --material RGB`
I receive error:
`Segmentation fault (core dumped)`

Test data: https://senseflycom.s3.amazonaws.com/datasets/ebee-rtk/point%20cloud/vrs_accuracy_2_5cm_densified_point_cloud.zip

**Comment by potree** [comment]
Does it work without the -p argument?

**Comment by spatialhast** [comment]
For test data https://senseflycom.s3.amazonaws.com/datasets/ebee-rtk/point%20cloud/vrs_accuracy_2_5cm_densified_point_cloud.zip when I use command
`$ PotreeConverter -i vrs.las -o ~/test -p index --material RGB`
I receive the error: 
![image](https://user-images.githubusercontent.com/3269617/29324667-a27f96da-81ed-11e7-8640-7becb9048319.png)
When I run command without '-p index' option
`$ PotreeConverter -i vrs.las -o ~/test --material RGB`
conversion work succesfully.

I have 'xyz' file (10.3Gb, from laser scanner), - this file I succesfully convert using PotreeConverter 1.4 version.
Now I try convert this file using updated PotreeConverter 1.5 version using command:
`$ PotreeConverter -i test.xyz -o ~/test01 --material RGB`
I receive error:
![image](https://user-images.githubusercontent.com/3269617/29324917-801e5292-81ee-11e7-8ae6-d8f7b2ee8b52.png)
Also some error for another types of material (INTENSITY, SOURCE)

**Comment by potree** [comment]
Did you copy ```PotreeConverter/resources``` to the directory of the binary?

**Comment by spatialhast** [comment]
I did not copy earlier `PotreeConverter/resources` to the directory of the binary.
Now I copy `~/PotreeConverter/PotreeConverter/resources` to `~/PotreeConverter/build/PotreeConverter`
but the error remained

**Comment by quams** [comment]
I have the same problem. Compiled on a bare Ubuntu 16.04 LTS server, when I run PotreeConverter it segfaults:

```
jan@sv-mockup:[potree_test] $ ./contrib/PotreeConverter/build/PotreeConverter/PotreeConverter -i test/shipwreckSmoothedCloud_03.ply -o public/ 
== params ==
source[0]:         	test/shipwreckSmoothedCloud_03.ply
outdir:            	public/
spacing:           	0
diagonal-fraction: 	200
levels:            	-1
format:            	
scale:             	0
pageName:          	
projection:        	

Segmentation fault (core dumped)
```

It seems to be a problem in the file reader:
```
an@sv-mockup:[potree_test] $ strace ./contrib/PotreeConverter/build/PotreeConverter/PotreeConverter -i test/shipwreckSmoothedCloud_03.ply -o public/
execve("./contrib/PotreeConverter/build/PotreeConverter/PotreeConverter", ["./contrib/PotreeConverter/build/"..., "-i", "test/shipwreckSmoothedCloud_03.p"..., "-o", "public/"], [/* 21 vars */]) = 0
brk(NULL)                               = 0x228f000

(...)

write(1, "== params ==\n", 13== params ==
)          = 13
write(1, "source[0]:         \ttest/shipwre"..., 55source[0]:         	test/shipwreckSmoothedCloud_03.ply
) = 55
write(1, "outdir:            \tpublic/\n", 28outdir:            	public/
) = 28
write(1, "spacing:           \t0\n", 22spacing:           	0
) = 22
write(1, "diagonal-fraction: \t200\n", 24diagonal-fraction: 	200
) = 24
write(1, "levels:            \t-1\n", 23levels:            	-1
) = 23
write(1, "format:            \t\n", 21format:            	
) = 21
write(1, "scale:             \t0\n", 22scale:             	0
) = 22
write(1, "pageName:          \t\n", 21pageName:          	
) = 21
write(1, "projection:        \t\n", 21projection:        	
) = 21
write(1, "\n", 1
)                       = 1
stat("test/shipwreckSmoothedCloud_03.ply", {st_mode=S_IFREG|0755, st_size=27815798, ...}) = 0
stat("test/shipwreckSmoothedCloud_03.ply", {st_mode=S_IFREG|0755, st_size=27815798, ...}) = 0
stat("test/shipwreckSmoothedCloud_03.ply", {st_mode=S_IFREG|0755, st_size=27815798, ...}) = 0
open("test/shipwreckSmoothedCloud_03.ply", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0755, st_size=27815798, ...}) = 0
read(3, "ply\nformat binary_little_endian "..., 4096) = 4096
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0} ---
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)
```

Before I am going to dig deeper I would like to know if I inadvertently did something stupid...

**Comment by tomomano** [comment]
I also experience the segmentation fault error when trying to load .ply file. I am using the latest release (version 1.5), and  my computer is running Ubuntu 16.04 LTS.

I also installed the complied version (version 1.5) for Windows on my Windows 7 machine, and I seem to experience the same error: segmentation fault when trying to load .ply file.

I also tried version 1.3.1 on my Windows 7 machine, and this version was able to load .ply was without any problems.

Any ideas/methods to fix?

**Comment by WHAAAT** [comment]
I have the exact same issue. 
I'm running Ubuntu 16.04 and also tried the docker Image. 
For me its not possible to read *.ply data (ASCII nor BINARY)

**Comment by ahmadshabbir2468** [comment]
XYZ FILES are Not Process 

./PotreeConverter.exe C:/wamp64/www/PotreeConverter2/PotreeConverter_1.5_windows_x64/teknikrum_finger_a_fine**.xyz** -o C:/wamp64/www/PotreeConverter2/PotreeConverter_1.5_windows_x64 --generate-page pageName


![xuz files](https://user-images.githubusercontent.com/24982349/31122700-475ab25a-a856-11e7-997a-c1bf1811cee8.PNG)

**Comment by mpampana** [comment]
This may help you https://github.com/potree/PotreeConverter/pull/283

**Comment by EmilWine** [comment]
Hi,
I'm using Ubuntu 16.04. Had the same issue with segmentation fault. 
In the main.cpp file line 72 you'll find: args.addArgument("source,i,", "input files");
remove the extra comma so it looks like this:   args.addArgument("source,i", "input files");
This ended the segmentation fault issues for me.
Thanks

**Comment by fgilic** [comment]
Similary to @EmilWine's suggestion, after `PotreeConverter` in command I define input file without `-i` flag. So instead `PotreeConverter -i inputFile.laz ...` I use `PotreeConverte inputFile.laz ...` which in my case solved segmentation fault problem.

**Comment by sebiegli** [comment]
Strangely the solution from **fgilic** solved the problem for me too. (Ubuntu 18.04):

This doesn't work (Segmentation fault):
`PotreeConverter -i inputFile.las`

This works:
`PotreeConverter inputFile.las`
