### ISSUE TITLE
PotreeConverter crashes in Windows 10 when attempting to process

### ISSUE THREAD

**Issue by joakimfj** [potree/PotreeConverter#269]
Every time I attempt processing a ply file, PotreeConverter.exe crashes, with the Windows 10 error message "PotreeConverter.exe has stopped working".

**Comment by joakimfj** [comment]
This seems to have something to do with my files that I input. Using PLY files from RealityCapture.

**Comment by potree** [comment]
What about las files as input?

**Comment by joakimfj** [comment]
RealityCapture sadly does not output LAS. I will try XYZ, but Im doubtful. Only two options I have

**Comment by joakimfj** [comment]
Odd thing is, I cant convert files, but a friend of mine has no problems with the same files.

**Comment by champ8242** [comment]
I have the same issue, Windows 10, las input, error message "PotreeConverter.exe has stopped working"
I will download source and compile to see if I can debug

**Comment by MrLesh** [comment]
Same thing here...it crushes

**Comment by robjlg** [comment]
PotreeConverter.exe 1.5  stops work on windows 7 64 bits.  

I could not find an way to get it working. Version 1.5 RC works fine!

Any  wrong argument stops, can't display any error messages.  -h displays help.

Has anyone found some way to get it working?

Thank you

**Comment by robjlg** [comment]
OK,   it works for LAS file.  It crash for PLY files on input

**Comment by jingxa** [comment]
system : win10
problem : *.ply 
i can't convert *..ply files ,why ? it stops working when i convert,? do u solve it ?

**Comment by jingxa** [comment]
i find a problem
i just convert ply file by potreeconverter_1.4 ,then i works well !
but 1.5 works bad !
is it a bug ???

**Comment by lostoy** [comment]
bug in https://github.com/potree/PotreeConverter/blob/master/PotreeConverter/src/stuff.cpp#L226
,should 

return icompare(tstr, suffix) != 0;

**Comment by mpampana** [comment]
#283 @lostoy
