### ISSUE TITLE
Point Budget values not visibly changing "fidelity" of point cloud ?

### ISSUE THREAD

**Issue by vadnart1** [potree/PotreeConverter#273]
Hi,  
Not sure if I'm doing something wrong but  using v1.5 and tried to change the point budget values but does not appear to change the "fidelity" of the point cloud image.  even sliding up to max 5Mil points on a ~2GB LAS point cloud.

Comparing v1.5 against v1.4 , adjusting point budget in v1.4 shows visible increase in the fidelity of the point cloud; , in other words the point cloud image shows more detail at 5M points vs say 1M points in v1.4.  I don't see any visible changes in v1.5 on the same LAS .

Same results across  Chrome (default), Safari, and Edge.

I'm using the standard potree convert parameters :   
   potreeconverter "D:\pointcloud\my_pointcloud.las" -q NICE -p "my_pointcloud" -o "d:\pointcloud\my_pointcloud"

Thanks in advance for any help.

**Comment by Giedrius1991** [comment]
Apparently i have the same problem.
