### ISSUE TITLE
I have a problem about "namePage.html:45 Uncaught ReferenceError: Potree is not defined"

### ISSUE THREAD

**Issue by jingxa** [potree/PotreeConverter#275]
i built a namePage.html according to 【 `./PotreeConverter.exe C:/pointcloud.las -o C:/xampp/htdocs/potree --generate-page pageName`】 

but i had a error 👎 :
```
window.viewer = new Potree.Viewer(document.getElementById("potree_render_area"));
# namePage.html:45 Uncaught ReferenceError: Potree is not defined
```

i don't how to solve it ? can u help me ? thanks!

**Comment by Just5D** [comment]
I meet the same problem
