### ISSUE TITLE
creating page but not showing material option

### ISSUE THREAD

**Issue by smatubber** [potree/PotreeConverter#277]
please help. i'm new
i'm converting the las file using Potree Converter
./PotreeConverter.exe C:/data.las -o C:/potree_converted -p pageName

but it is not showing the material choice option in the viewer like this
![capture](https://user-images.githubusercontent.com/32445570/31065193-6275e6fe-a6f8-11e7-86a7-42d566e700fa.PNG)

also I wan't to make the toolset like the following
![capture2](https://user-images.githubusercontent.com/32445570/31065229-8d230e22-a6f8-11e7-8778-b8335454c430.PNG)

**Comment by jingxa** [comment]
maybe your soft version is low ,you should update  it such as 1.5rc

**Comment by matubbers** [comment]
i actually have 1.5 latest version but still facing this problem...

how can i have a page like this?
![image](https://user-images.githubusercontent.com/32445570/32412660-e83e5b68-c228-11e7-9b3a-300b8793e59c.png)

**Comment by jingxa** [comment]
i just know a little, in my 1.5 version , material is change , i change it in scene tab , 
![](https://github.com/jingxa/imagesbar/blob/master/temp/multiplepotree.png?raw=true)
like arrow, click it you will find a "attribute selection "that you can select RGB and so on !
can you understand me?

**Comment by jingxa** [comment]
and i have a problem ,do you know how to solve it ?#284,
can you help me ?
