### ISSUE TITLE
undefined symbol: laszip_create

### ISSUE THREAD

**Issue by ahmadshabbir2468** [potree/PotreeConverter#280]
Hi,
I try to install laszip with potree but suddenly it give me this Error and Every thing is stuck 
Please Guide 

symbol lookup error: PotreeConverter: undefined symbol: laszip_create

Either it is Some Variable Or something else 

Guide please 
here is the same case as mine 
https://github.com/potree/PotreeConverter/issues/187

**Comment by AlbionS** [comment]
did you find the error or a solution ?
