### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by GinaVulpes** [potree/PotreeConverter#282]
I have a new issue with the converter. Even though it works fine with .las and .laz files it does not convert .ply or .txt files. Whenever I try to convert one of those files (even the test files) I get a segmentation fault:

```
source[0]:         	ripple_bin.ply
outdir:            	/Users/ginaVulpes/Desktop/PCtut/potree-1.3/resources/pointclouds/jupyter_test
spacing:           	0
diagonal-fraction: 	200
levels:            	-1
format:            	
scale:             	0
pageName:          	
projection:        	

Segmentation fault: 11
```

I think I might be doing something wrong. Any ideas?

**Comment by mpampana** [comment]
https://github.com/potree/PotreeConverter/pull/283 I made a pull request. It seems to fix this problem.

**Comment by GinaVulpes** [comment]
Thank you so much! This solved my problem!!

**Comment by shuait** [comment]
how does that solved your problem? I downloaded the potreeConverter today and compiled it with gcc-5,  I got the same error message like this:

== params ==
source[0]:         	/home/shuait/Dropbox/ReidAndLoc/NCB/ply_files/cranebay.ply
outdir:            	/home/shuait/PotreeConverted/
spacing:           	0
diagonal-fraction: 	200
levels:            	-1
format:            	
scale:             	0
pageName:          	NCB
projection:        	

Segmentation fault (core dumped)

how can I fix this?

**Comment by mpampana** [comment]
@shuait they have not checked my pull request yet, so it is not in the official repository. check my pull request here: #283 
It may solve your problem.

**Comment by shuait** [comment]
Thanks @mpampana,  I hope they will merge it soon. I found a workaround to that problem by using cloud compare to convert my PLY files to LAS.

**Comment by GinaVulpes** [comment]
In any case, you do not need to wait. You can either download/clone the file from mpampana  and then recompile, or make the changes to the files yourself and then re-compile (with the right compiler).
