### ISSUE TITLE
low question about mulitle files in one scene

### ISSUE THREAD

**Issue by jingxa** [potree/PotreeConverter#284]
i 'm a beginner,i just show pointclouds in potree.
 ###  then i want to put multiple files in one scene,
### i can find all data ,but i can't operate like below;

![](https://github.com/jingxa/imagesbar/blob/master/temp/multiplepotree.png?raw=true)

### it can show  one or more pointclouds ,but i only  show or hidden like below:

![](https://github.com/jingxa/imagesbar/blob/master/temp/onepotree.png?raw=true)

---
And question 2:
 ### i convert a file by PotreeConverter,, all pointclouds are black in html, but it is beautiful in open source CloudCompare:
【black in potree 】
![](https://github.com/jingxa/imagesbar/blob/master/temp/blade_black.png?raw=true)
【perfect in CloudCompare】
![](https://github.com/jingxa/imagesbar/blob/master/temp/blade_compare.png?raw=true)

---
looking forward to a reply!

**Comment by jingxa** [comment]
anybody who can tell me the command?? i 'm glad to thank you !

**Comment by Giedrius1991** [comment]
try to add --output-format LAS
like this:  PotreeConvert.exe c:\data --output-format LAS -o c:\output -p page

**Comment by jingxa** [comment]
@Giedrius1991 hello , i want to convert multiple files into one scene, but there is a problem that all data become one pointcloud,
i just want to have more choices , for example, i have 4 pointclouds in one scene,like  above pictures, i can select pointcloud 1 such as lion1 , and don't show others
![](https://github.com/jingxa/imagesbar/blob/master/temp/multiplepotree.png?raw=true)

**Do u have good idea? i dont know what command can directly generate that?**

if u cant understand me , u can try below link.
[](http://potree.org/demo/potree_1.5/examples/multiple_pointclouds.html)
