### ISSUE TITLE
PotreeConverter 1.5RC: Uncaught TypeError: Cannot read property 'laslaz' of undefined

### ISSUE THREAD

**Issue by rapidlasso** [potree/PotreeConverter#290]
Tried to use PotreeConverter 1.5RC because of [this issue](https://github.com/potree/PotreeConverter/issues/285) with the crashing '[--list_of_files](https://github.com/potree/PotreeConverter/issues/285)' option in PotreeConverter 1.5. But no points are shown in the portal and the console reports this error here:

Uncaught TypeError: Cannot read property 'laslaz' of undefined
    at new LAZLoader (laslaz.js:208)
    at new LASFile (laslaz.js:298)
    at Potree.LasLazLoader.loadData [as parse] (potree.js:2665)
    at XMLHttpRequest.xhr.onreadystatechange (potree.js:2650)

**Comment by m-schuetz** [comment]
Will give this a look in the next few days!

**Comment by rapidlasso** [comment]
If the (probably simple) bug in '--list-of-files' could be fixed in version
1.5 then the need to look at this bug will disappear (at least for me).
