### ISSUE TITLE
IE11 support?

### ISSUE THREAD

**Issue by libakdk** [potree/PotreeConverter#291]
Hi

I can't view potree point clouds with Internet Explorer (IE11) when created with 1.5RC. previous v1.3 works fine

How can I get it to work in IE11?

Rgds

**Comment by zhangliyong16** [comment]
I have tested: IE11 edge mode is supported with potree.

**Comment by m-schuetz** [comment]
As a warning, it probably won't work in either IE or Edge starting with Potree 1.6.
That's becaue a lot has changed in the renderign pipeline and unfortunately, some WebGL things are not supported. Since it's a WebGL issue, babel won't help either.
