### ISSUE TITLE
Running PotreeConverter in docker

### ISSUE THREAD

**Issue by JGasp** [potree/PotreeConverter#292]
Am trying to use [massive potree converter](https://github.com/NLeSC/Massive-PotreeConverter) but am unable to run Potreconverter in docker. It returns following error message
> ERROR: filesystem error: cannot canonicalize: No such file or directory [/data1/execution/tile_0_0_potree_converter/PotreeConverter] [/data1/execution/tile_0_0_potree_converter]

I posted more detailed issue [here](https://github.com/NLeSC/Massive-PotreeConverter/issues/16)

**Comment by adamsteer** [comment]
Hi @JGasp that’s an issue with how the massivepotreeconverter image is used. I propose closing this issue, its better discussed in the MPC repo. @m-schuetz ?
