### ISSUE TITLE
segfault when input file is not first arg

### ISSUE THREAD

**Issue by nmgeek** [potree/PotreeConverter#293]
If I put any option (including -i) as the first option I get a segfault caused by attempting to index an empty vector at this line:

    https://github.com/potree/PotreeConverter/blob/master/PotreeConverter/src/main.cpp#L225

I stepped through the debugger and it looks like this line is the culprit:

 https://github.com/potree/PotreeConverter/blob/master/PotreeConverter/lib/arguments/arguments.hpp#L190

It inserts an argument with an empty vector and with a key of "" which matches the 'source' argument.

**Comment by rwfrenz20** [comment]
I've found various sets of arguments that cause this seg fault, e.g. the latest one:

"./PotreeConverter --source ~/testdata/Block000072.las -o ~/testdata/potree --output-attributes INTENSITY --material INTENSITY -p Block000072 -output-format LAZ"

I can't find any reason that the empty key insert is necessary - I have a local branch that removes it that has been working fine for me for a while.
