### ISSUE TITLE
Save Changes on Web Page

### ISSUE THREAD

**Issue by matheusmarquezin** [potree/PotreeConverter#300]
I'm trying to save the measurements, notes etc .. That are created by the web page of potree, I found a form of  editing the html but needed to do in an automatic way via code

**Comment by matheusmarquezin** [comment]
Or a method that loads the json file with the measurements that were previously made would also help

**Comment by MadhavEsDios** [comment]
Hi, were you able to solve the problem, I too want to save the measurements, etc. that I make. ?
