### ISSUE TITLE
points are black/empty

### ISSUE THREAD

**Issue by parkygis** [potree/PotreeConverter#304]
hi,
thanks for the great work.  it is amazing.  as a newbie, I have some simple questions.
1. I converted las file as bin, laz, las files, but all turned out black color.  I would like to colorized point by height.  are there any ways to do?
2. I test it in my local computer(another computer), but the generated Html file does not show any.. it is empty.  however, I can see points from the viewer.html(example folder).  I set my localhost environment with IIS.  does anyone had/has the same issue?

thanks in advance.

**Comment by djc1234** [comment]
in relation to point 1 I've had similar this morning  try adding: 
 --material ELEVATION to colour by elevation

PotreeConverter.exe C:/pointcloud.las -o C:/xampp/htdocs/potree --material ELEVATION --generate-page pageName

Worked for me!

with point 2 it explains http://potree.org/getting_started.html about the reasons for needing the local host (security policies in browsers)

**Comment by ZulfitriOthman** [comment]
Hi

I'm newly to the las and potree, I'm having trouble with converting the las, i keep convert PotreeConverter.exe D:\lidarfile\SEAVIEW_WITH_ROOF_10mm.las -o D:\lidarfile\potree_output file-name and there's always 1 missing file which is the could.js

after i convert every i only received metadatajson, logtxt, hierachyjson and octree.bin
