### ISSUE TITLE
Potree doesn´t recognise some classification codes

### ISSUE THREAD

**Issue by robertdbuckley** [potree/PotreeConverter#309]
Hi,

I have a Las file v1.2 which has been classified according to 2 -ground, 7 - noise, 13 -wire and 20 reserved.
When I use covert with the following command:
PotreeConverter.exe ..\..\lidar_testdaten\*.las -o ..\..\lidar_testdaten\www -p index.html --material ELEVATION --output-attributes RGB CLASSIFICATION 
..not all of the classication filters are translated into the potree viewer.Only ground is working. I assume I must manually define the classification filters for this to work? Is there any documentation showing how to do this or is there something  have to do before running the potreeConverter?

**Comment by antoinebio** [comment]
https://github.com/potree/potree/issues/538

**Comment by brendwal** [comment]
Can you tell me WHERE you can find all the commandline arguments for PotreeConverter?  I can't find any of the arguments and possible parameters.  thank you so much!

**Comment by EjectorSeat** [comment]
Commandline arguments are listed and explained in the readme of the PotreeConverter: https://github.com/potree/PotreeConverter

Also "PotreeConverter.exe --help" does the trick
