### ISSUE TITLE
PotreeConverter has stopped working 

### ISSUE THREAD

**Issue by kole2b** [potree/PotreeConverter#312]
Hello, i have an error wich make me crazy, when i  put this line in my node command prompt : 
`PotreeConverter.exe C:\User\Desktop\myfile.las -o D:\work\potree\renders --generate-page my_test`
An HTML file is created but it is empty. And when i put `-i`  just before the fire location
like that : `PotreeConverter.exe -i C:\User\Desktop\myfile.las -o D:\work\potree\renders --generate-page my_test`
windows (the win10) says that PotreeConverter has stopped working. 
Any idea ? 
PS : i'm new on git so i'm sorry if i dont respect codes or stuff like that

**Comment by wrenoud** [comment]
It looks like your first issue with the empty html may be duplicated by #328.

The second issue of getting a crash when ussing the `-i` options I was just able to duplicated. It also crashes with the use of the alias `--source`.
