### ISSUE TITLE
Keep the original index of each point

### ISSUE THREAD

**Issue by VioletteA** [potree/PotreeConverter#316]
Hello, 

For a project, I **really really need** to be able to know, for each point of the octree, its original index (i.e. its position in the PLY file **before** conversion). If necessary, I can add a column to the ply corresponding to this value (as shown below).

![exempleplyindex](https://user-images.githubusercontent.com/21361485/40623679-5bc27afe-62a8-11e8-9658-cb9ad5fd4ab2.jpg)

During the conversion, this attribute is not kept, and I don't see any option to do it. I tried to modify BINPointWriter.hpp for that as well as BinaryDecoderWorker.js, without any success so far. The idea was to add this value as an attribute of the pointcloud, but I get the following error: "_Uncaught RangeError: byte length of Float32Array should be a multiple of 4_".

Do you know how I could proceed to know the original index of a selected point from the viewer ?? 

Thanks in advance

--------------------------------------------------------------------------------
**EDIT 05.31.2018 :** 

I finally managed to keep the index during the conversion by PotreeConverter. By modifying BinaryDecoderWorker.js I can now access this new array on the client side. Nevertheless I face a really weird problem:
In the parse function of Potree.BinaryLoader, if I name the new attribute _"index"_, the point cloud loads correctly, and the attribute is stored in the **_geometry.index_** field (Fig.A). But if I name it otherwise (for example "_originalIndex_"), the attribute is well stored in **_geometry.attributes.originalIndex_**, but the point cloud no longer loads correctly, instead I just have a line (Fig.B).
I must have missed something important, I apologize if it is a noob question, or if it is not properly github-formatted... Any suggestion is welcome!

![bugattrname](https://user-images.githubusercontent.com/21361485/40788580-b4d7e6fc-64f0-11e8-9aad-025d1f3da724.jpg)

**Comment by VioletteA** [comment]
Well, I eventually found the solution, it was a shader problem. I close this issue.

**Comment by juzhao1** [comment]
Help, I added an extra column to the pcd file to store the original index, but it keeps giving an error when converting to potree
`libc++abi: terminating due to uncaught exception of type nlohmann::detail::type_error: [json.exception.type_error.302] type must be number, but is null`

I don't know C++, please tell me how to solve this problem,
thanks!
