### ISSUE TITLE
FLUSHING: ERROR: filesystem error: status: File name too long 

### ISSUE THREAD

**Issue by salishaukat** [potree/PotreeConverter#317]
FLUSHING: ERROR: filesystem error: status: File name too long [/home/ubuntu/openpitmine.e57_a4a4bb5c-6ba8-4919-948c-922f2fe54aba/data/r/62460/32235/30555/16624/06172/74540/03604/16605/34054/02064/46360/60205/33455/27446/64700/01204/17365/44235/53352/06357/45077/75333/00666/35707/24456/04351/45576/61174/27106/43550/60376/26206/51024/26000/11702/06644/05346/55107/51107/77532/37152/65147/76320/25362/01210/53513/77466/44726/10372/60064/r62460322353055516624061727454003604166053405402064463606020533455274466470001204173654423553352063574507775333006663570724456043514557661174271064355060376262065102426000117020664405346551075110777532371526514776320253620121053513774664472610372600644.bin]

Having this kind of issue

**Comment by courageon** [comment]
That is one heck of a file name. I've just come across this issue as well. The converter's naming convention seems to issue these lengthy file names when points are extremely disproportionately distributed. In my case I had several thousand points at the same location. 
If this is your case, the best bet is to disallow multiple points at the same location in your pre-processing.
If your points are just super close together (but not the same), try increasing the "scale" argument in the converter. Too small a sale causes the converter to quantize away that precious precision resulting in my original case where the points just wind up all being plopped at the same location.

**Comment by courageon** [comment]
Actually, just found out that setting the "--level" argument will prevent potree from generating past a certain depth, preventing errors like this.
