### ISSUE TITLE
make fails on CentOS 7

### ISSUE THREAD

**Issue by vvovvo** [potree/PotreeConverter#318]
I'm trying to build PotreeConverter on CentOS7 and get the following error. Would appreciate any advice. 

$ sudo make
Scanning dependencies of target PotreeConverter
[  9%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/BINPointReader.cpp.o
/usr/local/src/PotreeConverter/master/PotreeConverter/src/BINPointReader.cpp:6:35: fatal error: experimental/filesystem: No such file or directory
 #include <experimental/filesystem>
                                   ^
compilation terminated.
make[2]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/build.make:59: PotreeConverter/CMakeFiles/PotreeConverter.dir/src/BINPointReader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:79: PotreeConverter/CMakeFiles/PotreeConverter.dir/all] Error 2
make: *** [Makefile:117: all] Error 2

**Comment by nerdinand** [comment]
See https://github.com/potree/PotreeConverter/issues/260
