### ISSUE TITLE
PotreeConverter generates me empty HTML file without any error/warning

### ISSUE THREAD

**Issue by ghost** [potree/PotreeConverter#328]
Hello guys, I am so sorry that I must open issue again. :(

Anyway, I run this command:

    PotreeConverter /home/user/Desktop -o /home/user/Desktop/mypage  --page-template /home/user/Desktop/resources --projection 4326  --generate-page pagename

And I get the output: 

    == params ==
    source[0]:         	/home/user/Desktop
    outdir:            	/home/user/Desktop
    spacing:           	0
    diagonal-fraction: 	200
    levels:            	-1
    format:            	
    scale:             	0
    pageName:          	pagename
    projection:        	4326

    AABB: 
    min: [410502, 5,0107e+06, -20,98]
    max: [411675, 5,0119e+06, 236,19]
    size: [1173,08, 1201,81, 257,17]

    cubic AABB: 
    min: [410502, 5,0107e+06, -20,98]
    max: [411703, 5,0119e+06, 1180,83]
    size: [1201,81, 1201,81, 1201,81]

    spacing calculated from diagonal: 10,408
    READING:  /home/user/Desktop/pt000009.las
    INDEXING: 1000000 points processed; 1000000 points written; 1,084 seconds passed
    INDEXING: 2000000 points processed; 2000000 points written; 1,947 seconds passed
    INDEXING: 3000000 points processed; 3000000 points written; 2,817 seconds passed
    INDEXING: 4000000 points processed; 4000000 points written; 3,693 seconds passed
    READING:  /home/user/Desktop/pt000005.las
    INDEXING: 5000000 points processed; 5000000 points written; 4,507 seconds passed
    INDEXING: 6000000 points processed; 6000000 points written; 5,334 seconds passed
    INDEXING: 7000000 points processed; 7000000 points written; 6,213 seconds passed
    INDEXING: 8000000 points processed; 8000000 points written; 7,125 seconds passed
    INDEXING: 9000000 points processed; 9000000 points written; 8,057 seconds passed
    READING:  /home/user/Desktop/pt000008.las
    INDEXING: 10000000 points processed; 10000000 points written; 8,967 seconds passed
    FLUSHING: 0,785s
    INDEXING: 11000000 points processed; 11000000 points written; 10,681 seconds passed
    INDEXING: 12000000 points processed; 12000000 points written; 11,473 seconds passed
    INDEXING: 13000000 points processed; 13000000 points written; 12,299 seconds passed
    INDEXING: 14000000 points processed; 14000000 points written; 13,249 seconds passed
    INDEXING: 15000000 points processed; 15000000 points written; 14,27 seconds passed
    READING:  /home/user/Desktop/pt000011.las
    INDEXING: 16000000 points processed; 16000000 points written; 15,079 seconds passed
    INDEXING: 17000000 points processed; 17000000 points written; 15,937 seconds passed
    INDEXING: 18000000 points processed; 18000000 points written; 16,912 seconds passed
    INDEXING: 19000000 points processed; 19000000 points written; 17,789 seconds passed
    INDEXING: 20000000 points processed; 20000000 points written; 18,738 seconds passed
    FLUSHING: 0,993s
    INDEXING: 21000000 points processed; 21000000 points written; 20,989 seconds passed
    READING:  /home/user/Desktop/pt000007.las
    INDEXING: 22000000 points processed; 22000000 points written; 22,075 seconds passed
    INDEXING: 23000000 points processed; 23000000 points written; 23,089 seconds passed
    INDEXING: 24000000 points processed; 24000000 points written; 24,087 seconds passed
    INDEXING: 25000000 points processed; 25000000 points written; 24,967 seconds passed
    INDEXING: 26000000 points processed; 26000000 points written; 25,857 seconds passed
    INDEXING: 27000000 points processed; 27000000 points written; 26,798 seconds passed
    INDEXING: 28000000 points processed; 28000000 points written; 27,817 seconds passed
    READING:  /home/user/Desktop/pt000001.las
    INDEXING: 29000000 points processed; 29000000 points written; 28,621 seconds passed
    READING:  /home/user/Desktop/pt000003.las
    INDEXING: 30000000 points processed; 30000000 points written; 29,353 seconds passed
    FLUSHING: 1,298s
    INDEXING: 31000000 points processed; 31000000 points written; 31,478 seconds passed
    INDEXING: 32000000 points processed; 32000000 points written; 32,401 seconds passed
    INDEXING: 33000000 points processed; 33000000 points written; 33,231 seconds passed
    INDEXING: 34000000 points processed; 34000000 points written; 34,091 seconds passed
    INDEXING: 35000000 points processed; 35000000 points written; 35,088 seconds passed
    READING:  /home/user/Desktop/pt000002.las
    INDEXING: 36000000 points processed; 36000000 points written; 36,056 seconds passed
    READING:  /home/user/Desktop/pt000006.las
    INDEXING: 37000000 points processed; 37000000 points written; 36,953 seconds passed
    INDEXING: 38000000 points processed; 38000000 points written; 37,949 seconds passed
    INDEXING: 39000000 points processed; 39000000 points written; 38,863 seconds passed
    READING:  /home/user/Desktop/pt000004.las
    INDEXING: 40000000 points processed; 40000000 points written; 39,9 seconds passed
    FLUSHING: 3,701s
    INDEXING: 41000000 points processed; 41000000 points written; 44,768 seconds passed
    INDEXING: 42000000 points processed; 42000000 points written; 45,929 seconds passed
    INDEXING: 43000000 points processed; 43000000 points written; 47,154 seconds passed
    closing writer

    conversion finished
    43900524 points were processed and 43900524 points ( 100% ) were written to the output. 
    duration: 49,194s

Anyway, on the output, I get everything and folder page_template, but html files are empty. :(
Like on picture: [https://imgur.com/a/g1o4szB](url) My pointcloud folder is about 700mb, so conversion was good. I though its because of so much files, and I try to generate .html from one .las file, but the output was same.

I read issues about empty html files, but all that people have an error because of the template file, and I dont have it. I am really confused.

**Comment by demsham** [comment]
did you figure out what the problem was? i also get a 'successful' run but an empty html file
```
== params ==
source[0]:              C:/Users/username/Documents/1.las
outdir:                 C:/Users/username/Documents/potree_out/
spacing:                0
diagonal-fraction:      200
levels:                 -1
format:
scale:                  0
pageName:               1-v3
projection:

processing following attributes:
POSITION_CARTESIAN
RGBA
classification
gps-time
intensity
number of returns
return number
source id

AABB: {
        "min": [230000.000000, 392500.000000, 145.060000],
        "max": [232499.990000, 393889.380000, 206.620000],
        "size": [2499.990000, 1389.380000, 61.560000]
}

cubicAABB: {
        "min": [230000.000000, 392500.000000, 145.060000],
        "max": [232499.990000, 394999.990000, 2645.050000],
        "size": [2499.990000, 2499.990000, 2499.990000]
}

total number of points: 3,851,560
spacing calculated from diagonal: 21.6505
READING:  C:/Users/username/Documents/1.las
INDEXING: 1,000,000 of 3,851,560 processed (25%); 1,000,000 written; 0.628 seconds passed
INDEXING: 2,000,000 of 3,851,560 processed (51%); 2,000,000 written; 1.247 seconds passed
INDEXING: 3,000,000 of 3,851,560 processed (77%); 3,000,000 written; 1.871 seconds passed
closing writer

conversion finished
3,851,560 points were processed and 3,851,560 points ( 100% ) were written to the output.
duration: 5.128s
```

**Comment by Yes-Jumby** [comment]
maybe you forget to put html page_template into the executablepath.
