### ISSUE TITLE
Decresing my points too much

### ISSUE THREAD

**Issue by jlguariglia** [potree/PotreeConverter#331]
Hi guys,

So when I convert to a page, it decreases my points to 0.3%.

I lose a lot of quality on that.

Any clue?

Thanks

**Comment by awake040** [comment]
Can you share more information regarding the exact process and the point cloud you try to convert? How many points does the las file have and do you have the displayed point value at maximum?

**Comment by fnorf** [comment]
Provide your command line please. Provide details on how you determined the reduction to 0.3% of your original points.
