### ISSUE TITLE
Issues with page_template and creating a *.html-file from any directory

### ISSUE THREAD

**Issue by ghost** [potree/PotreeConverter#332]
Hi guys. I was about to run following command (I've added PotreeConverter to my $PATH already) in ~/pclouds/las:

PotreeConverter test.las -o testdir -p testpage

While the process seems to output the files for the potree viewer, I don't get any html-page displayed. It works when I do it the way MadhavEsDios did in this: https://github.com/potree/PotreeConverter/issues/314 but on the long run, I'll need to run it from multiple folders.

I've tried copying the resources folder, the contents of the resources folder and basically every other combination to ~/pclouds and ~/pclouds/las to no avail.

What do I have to do to make PotreeConverter produce an html file when ran from any working directory?

Thanks in advance!

**Comment by rphillips91** [comment]
Having the same issue, cannot find any solution on the web either

**Comment by spiladon** [comment]
Had the same issue. Solution: PotreeConverter [-input] -o [-outputDir] -p someName. The outputDir should for example "/home/kristofer/dev/workspaces/PotreeConverter/master/PotreeConverter/resources/page_template/ " or additionaly ".../page_template/pointclouds"
