### ISSUE TITLE
Setting viewer parameter in HTML file

### ISSUE THREAD

**Issue by Tofoillote** [potree/PotreeConverter#333]
Hi,

I'm deeply drawning in viewer parameter tinkering.

As to simplify workflow in order to produce quick and efficient point cloud viewing, I just wanna open my HTML file in navigator (afetre potree-converting them), set my desired viewing settings (nod size, point budget, EDL, FOV, Gamma, brightness, etc ...) then when having some good settings done, just export the whole parameter in some file (assuming json ?) in order to copy/paste then in the original HTML.

This way should be, definitively, an easy one to provide "site ready" point cloud for those who just need to display them without learning the whole java thing or github nor programming.

So, question is about : can it be added to next potree development ?

is this can be done by another way ? (in this case please provide some clues)

**Comment by awake040** [comment]
I needed something comparable to that so I decided to have different page template folders and I just use a different page template for different tasks. I've set up everything in the viewer_template.html and altered sidebar.html and potree.js to alter it according to my needs. So the "default" after converting the las file is already set up in a viewer with my preferences.
