### ISSUE TITLE
Build 0.9.0 error on windows10

### ISSUE THREAD

**Issue by zf223669** [potree/PotreeConverter#334]
I have met a problem when i compiling the Carla v-0.9.0: 
the promt error below:
Failed to build Boost.Build engine.
Please consult bootstrap.log for further diagnostics.

    -[install_boost]: [BOOTSTRAP ERROR] An error ocurred while executing "bootstrap.bat".
    -[install_boost]: Exiting with error...

**Comment by RoadToML** [comment]
Having this issue too. Did u find out how to fix this? 

cheers
