### ISSUE TITLE
Rendering Point Clouds by classification rather than RGB, like Open Topography symbology

### ISSUE THREAD

**Issue by rphillips91** [potree/PotreeConverter#338]
Hello guys! I've managed to make some point clouds thanks to [Issue #224](https://github.com/potree/PotreeConverter/issues/224), using this command;
`.\PotreeConverter.exe <input> -o <targetDir> --output-attributes RGB CLASSIFICATION`

I noticed when filtering ground points only, it is still coloured green. e.g. 
![rgb_classification](https://user-images.githubusercontent.com/36900458/46589693-2cb4f100-cb09-11e8-8fa4-79fc13339ab9.PNG)

This is the symbology (referencing) Open Topography 3D Point Cloud Viewer that I was after;
![open_topo_potree](https://user-images.githubusercontent.com/36900458/46589717-64239d80-cb09-11e8-8e5b-2ab41dbe9fe5.PNG)

I tried these commands, unfortunately all of them rendered point clouds with one classification, unclassified displaying a grey-black point cloud, please see image below;

`.\PotreeConverter.exe <input> -o <targetDir> -a CLASSIFICATION`
`.\PotreeConverter.exe <input> -o <targetDir> --output-format LAS`

![classification_potree](https://user-images.githubusercontent.com/36900458/46589766-1f4c3680-cb0a-11e8-8cf2-09ea2e546930.PNG)

Is it possible to render point clouds like the Open Topography example, using Potree Converter?
Many thanks

**Comment by rphillips91** [comment]
C:/a/potree/PotreeConverter_1.6_windows_x64/PotreeConverter.exe  C:/a/points.las -o C:/xampp/htdocs/potree --output-attributes CLASSIFICATION --material CLASSIFICATION --generate-page classificationtest

**Comment by mariamsajadian** [comment]
I have exactly the same problem, but unfortunately I could not find any solution??!! :(

**Comment by jrjdavidson** [comment]
rphillips91 comment helped me understand how to process opentopography data, cheers for this
