### ISSUE TITLE
Bus error: 10

### ISSUE THREAD

**Issue by stephenpardy** [potree/PotreeConverter#34]
Trying the converter on one of the resources included with potree on Mac OSX 10.9 produces result:
"Bus error: 10" and no outputs.
How I am calling the program:
./PotreeConverter_exe lion_takanawa.ply -o test_output/

And I am not sure if this helps, but these are the warnings I get during compilation:
~/Code/PotreeConverter/PotreeConverter/src/PotreeConverter.cpp:118:3: warning: delete called on
      'PointReader' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
                delete reader;
                ^
~/Code/PotreeConverter/PotreeConverter/src/PotreeConverter.cpp:170:3: warning: delete called on
      'PointReader' that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
                delete reader;
                ^
2 warnings generated.
[ 75%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/PotreeWriter.cpp.o
~/Code/PotreeConverter/PotreeConverter/src/PotreeWriter.cpp:69:2: warning: delete called on 'PointReader'
      that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
        delete reader;
        ^
~/Code/PotreeConverter/PotreeConverter/src/PotreeWriter.cpp:92:1: warning: control may reach end of non-void
      function [-Wreturn-type]
}
^
~/Code/PotreeConverter/PotreeConverter/src/PotreeWriter.cpp:148:1: warning: control may reach end of
      non-void function [-Wreturn-type]
}
^
~/Code/PotreeConverter/PotreeConverter/src/PotreeWriter.cpp:168:4: warning: delete called on 'PointReader'
      that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
                        delete reader;
                        ^
~/Code/PotreeConverter/PotreeConverter/src/PotreeWriter.cpp:176:3: warning: delete called on 'PointWriter'
      that is abstract but has non-virtual destructor [-Wdelete-non-virtual-dtor]
                delete writer;
                ^
5 warnings generated.

**Comment by m-schuetz** [comment]
Did you solve this problem or does it still persist?

**Comment by stephenpardy** [comment]
Just pulled the new changes and am no longer getting this error.

**Comment by irealva** [comment]
@stephenpardy Hi stephen, would you mind sharing how you got Potree to run on mac? How did you get the PotreeConverter_exe executable. I've got all the right dependencies and followed the installation instructions here: https://github.com/potree/PotreeConverter

thanks!

**Comment by stephenpardy** [comment]
@irealva As far as I can remember, I followed the Linux instructions and installed from source using the provided CMakeList.txt.
However, I have upgraded a few things since I last installed and I just double checked now and it is not working anymore. I didn't end up using this program, so I don't think I can help you. Sorry!
