### ISSUE TITLE
Point-Attribute GPS_TIME is not stored in LAS-Output Files

### ISSUE THREAD

**Issue by BenjaminLoesch** [potree/PotreeConverter#340]
Hi

First of all thank you very much for creating Potree! it's amazing!

I just wanted to let you know, that theres a bug (or missing feature) in LAS writing.

I called PotreeConverter.exe with the following arguments:
PotreeConverter.exe <my_in_path> -o <my_out_path> --output-attributes GPS_TIME -f LAS --overwrite

It seems that the GPS-TIME information is not stored in created LAS-files.
Conversion to bin format works fine including gps-timestamps.

Beni

**Comment by wemamawe** [comment]
I also have this problem, When I used ColoudCompare to view LAS tiles, the GPS TIME always is 0, obviously it is error.

**Comment by wemamawe** [comment]
when we read the code of converter, we found that it used format 1.2 of las and point format 2 to write file, so it does not contain gps time , then we changed  some code ,and pulled to the develop branch, now it works fine with gps time attribute.

**Comment by zjj321** [comment]
las point format is 2,it will ok to change it to 3
