### ISSUE TITLE
incremental PotreeConverter failed  with writeToDisk error

### ISSUE THREAD

**Issue by gmaillet** [potree/PotreeConverter#345]
My point cloud is too large to be converted in one time and it failed in incremental mode during the flushing. This seems to be related with this test:
https://github.com/potree/PotreeConverter/blob/685ef56a7864ea2a9781b2ab61580f11f0983d29/PotreeConverter/src/PotreeWriter.cpp#L315
Without it, the conversion doesn't stopped and the result seems to be good.
What does it mean? Is my input data corrupted? 
Can this test generate a simple warning rather than an exit?

**Comment by omil** [comment]
is there any way to resume the converting. i stopped running conversion after 130k points and wanted to resume later, but now i have error on flushing: FLUSHING: writeToDisk 34,933 != 11,482

**Comment by regsagp** [comment]
seems this is because the temporary file "/temp/prepend.bin" was not deleted at last flushing
