### ISSUE TITLE
convert las file with PointSourceId attribute

### ISSUE THREAD

**Issue by jubru** [potree/PotreeConverter#349]
Hi Markus,
I want to convert a LAS file with PointSourceId attribute. I use "-a PointSourceId" argument but nothing is create in the data. I have tested the command with pentagon data : 
https://mega.nz/#!HEd1EDhZ!HTX8uRGCh8dwt3JRTNByYau42qhQJ01sOn3QXbe1TKM 
![capture](https://user-images.githubusercontent.com/12160142/51348720-b0d12a00-1aa3-11e9-909e-44dd8a5508f9.JPG)

Best regards
Julien

**Comment by neilrackett** [comment]
The only way we could find to get this to work with PotreeConverter was to use the `--output-format LAS` or `LAZ` option, but this seems to have a negative impact on the overall performance of the point cloud (lower FPS, etc).

@jubru Did you ever find a solution using the default binary format?
