### ISSUE TITLE
hidden tools windows

### ISSUE THREAD

**Issue by geoxluca** [potree/PotreeConverter#352]
Hi everybody
I would like to know if is it possible to hidden all tool command. So to leave the page only for a simple viewer and not also an interrogation page.
How I can do it?
Thank you

**Comment by EmmanuelAmann** [comment]
Just click on the square : )
If you want to remove permanently you must modify HTML file.

**Comment by geoxluca** [comment]
ahahah ... yes my idea is, delete permanently the tools
how can I modify html file?
what is the codice to remove?

**Comment by geoxluca** [comment]
DONE, thank you
