### ISSUE TITLE
 PotreeConvert to convert abnormal color

### ISSUE THREAD

**Issue by zouyue8898** [potree/PotreeConverter#356]
Hello,
I am a software developer from China and have encountered some problems in using the Potree framework.
We use **FARO's scanning** device to shoot and use Faro Sence to export files in .**xyz** format.
We use PotreeConvert to convert .xyz to a bin file.
The conversion commands are as follows:
_PotreeConverter.exe D:\faro\wuxu\SCENE_Scan_087.xyz -o C:\faro\PotreeConverted -p leida --overwrite --material RGB_
But when loading, the **color is abnormal.**
We have not found a solution on [github.](
Please inform us about the treatment, thank you.

**Comment by digimatspa** [comment]
Same problem here. Did you find a solution?
Thank you
