### ISSUE TITLE
Measuring areas give a false result

### ISSUE THREAD

**Issue by anasovic** [potree/PotreeConverter#357]
Hello, I'm trying to use the area measuring tool but it gives me a false result? Can you help me to correct this issue!
![False result area measure](https://user-images.githubusercontent.com/14891655/54623502-eaa2ba80-4a6b-11e9-8f5d-fe4cbc2261c7.jpg)

Thanks

**Comment by anasovic** [comment]
I'm trying to solve the problem and I think that the area measurement script doesn't take the "Z" attribute in the calculation so could you show me where the calculation script is located?
![Area problem](https://user-images.githubusercontent.com/14891655/54674034-dc03e400-4afb-11e9-84b2-125f89770cfd.jpg)
Thanks

**Comment by vadnart1** [comment]
Hi @anasovic, all , we are are having the same issue with area measurements.   just curious if you were able to resolve.  any help would be greatly appreciated.

thanks,
Dave

    
![potree-area-tool](https://user-images.githubusercontent.com/26193375/60991466-31186f80-a310-11e9-813d-a15ca55badab.jpg)

**Comment by anasovic** [comment]
Sorry @vadnart1 I didn't succeed to resolve the problem! I hope somebody will help us with this issue!
