### ISSUE TITLE
Adding measurements and similar stuff.

### ISSUE THREAD

**Issue by DusanTomic** [potree/PotreeConverter#358]
Hi,

I configure how to convert file and put that file on web server to see that file.
All is fine but I have one doubt, how to add points, measurements, links, images and other stuff in that point cloud?

What file I need to change?

Or what I need to do?

Thank you.

**Comment by hudsonchase** [comment]
@DusanTomic 

Did you have any success in adding additional functionality? I have the .html file working from xampp and am trying to extend it with the ability to measure/reclassify/etc.
