### ISSUE TITLE
Openmap button will not work

### ISSUE THREAD

**Issue by m2ed** [potree/PotreeConverter#361]
I use potreeconverter with the following string (please note, I have no idea what I'm doing, this is all trial and error)

./PotreeConverter.exe H:/potree/import/vannverket.las -o h:/potree/export --generate-page Vannverket2 --edl-enabled -- title Vannverket --projection "+proj=longlat +zone=1 +datum=WGS84 +no_defs"

The OpenMap-button appears under the menu "hamburger" button, however it does not work.

I've been looking and searching for how to make the map work, but I simply cant... 

I have attempted to find places to inject coordinates, but to no avail.

Please, in exact terms, explain to me how I can get the map to work, and if needed - how I can add coordinates to the pointcloud so this works... I am having tremendous difficulty and I'm wasting a lot of time now being able to figure this out. Thanks.

**Comment by bouthaynabakkouchi** [comment]
Hi, post your html code here
