### ISSUE TITLE
Source directory ./resources/page_template does not exist or is not a directory.

### ISSUE THREAD

**Issue by GHoogerwerf** [potree/PotreeConverter#369]
I keep getting this output while running Potree:

C:\>C:/Potree/PotreeConverter E:/***/***/3d/T3.las  -o E:/Converted -p 9c216d14-a4ac-4ad4-ebc1-1fe66a5b01e9
== params ==
source[0]:              E:/***/***
source[1]:              t3/3d/T3.las
outdir:                 E:/Converted
spacing:                0
diagonal-fraction:      200
levels:                 -1
format:
scale:                  0
pageName:               9c216d14-a4ac-4ad4-ebc1-1fe66a5b01e9
output-format:          BINARY
projection:

AABB:
min: [3,40282e+38, 3,40282e+38, 3,40282e+38]
max: [-3,40282e+38, -3,40282e+38, -3,40282e+38]
size: [3,40282e+38, 3,40282e+38, 3,40282e+38]

cubic AABB:
min: [3,40282e+38, 3,40282e+38, 3,40282e+38]
max: [6,80565e+38, 6,80565e+38, 6,80565e+38]
size: [3,40282e+38, 3,40282e+38, 3,40282e+38]

spacing calculated from diagonal: 2,94693e+36
Source directory ./resources/page_template does not exist or is not a directory.
closing writer

conversion finished
0 points were processed and 0 points ( -na.n(i.nd)% ) were written to the output.
duration: 0,018s

**Comment by siamonas** [comment]
`C:>C:/Potree/PotreeConverter E:///3d/T3.las -o E:/Converted -p 9c216d14-a4ac-4ad4-ebc1-1fe66a5b01e9`
`== params ==`
`source[0]: E://`
`source[1]: t3/3d/T3.las`

As you can see above you have entered as input file `E:///3d/T3.las`. You might have mistakenly put two more slashes over there.

I think you need `E:/3d/T3.las`.
