### ISSUE TITLE
Creating the executable PotreeConverter on Windows. (I know that I can dowload the .exe but I want to build it myself) 

### ISSUE THREAD

**Issue by AlbionS** [potree/PotreeConverter#370]
Hi I would be very grateful if someone could help me compile the project. 
I know that I can download the .exe I've already tried the .exe and I know how it works, I used it to convert some las files. But I want to generate it myself because I would like to make some modifications just to understand it better how it works.  

So I am using Windows 10, I have installed cmake, and Visual Studio 2017.

I follow the steps from the readme.
when I run : cmake -G "Visual Studio 15 2017 Win64" .  
Everything seems to be generated correctly : 

-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.10240.
-- The C compiler identification is MSVC 19.16.27034.0
-- The CXX compiler identification is MSVC 19.16.27034.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Cydis/Desktop/workspaces/lastools/master/LASzip/build

So normally the LASzip library should be working fine !!

In the readme we should set two environment variables : 
**set LASZIP_INCLUDE_DIRS=D:\dev\workspaces\lastools\master\LASzip\dll** this one is properly generated , I can find it in my folder where it was generated (P.S: I changed the path to  C:/Users/Cydis/Desktop/workspaces . . .) but this one 

**set LASZIP_LIBRARY=D:\dev\workspaces\lastools\master\LASzip\build\src\Release\laszip.lib** does not exist, it is not generated, I cannot find it in my folder. 
When I ran cmake -G "Visual Studio 15 2017 Win64" earlier a I  had no error message as you saw the message before so normaly laslib.lib should be somewhere in  the folder or somwhere else !!. 

However  I set the LASZIP_LIBRARY even though it does not exist in my lastools folder (hoping that somehow it will work)  and follow the other steps. 

Strangely I can **cmake -G "Visual Studio 15 2017 Win64" -DLASZIP_INCLUDE_DIRS=%LASZIP_INCLUDE_DIRS% -DLASZIP_LIBRARY=%LASZIP_LIBRARY%  ..\**  without having any error : 

-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.10240.
-- The C compiler identification is MSVC 19.16.27034.0
-- The CXX compiler identification is MSVC 19.16.27034.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/Cydis/Desktop/workspaces/PotreeConverter/master/build

So normally now I should be able to see the PotreeConverter.exe (or any other .exe) but it is not generated and I dont have any error while I cmake. 

Since I dont have any .exe I open the potree.sln (this one is generated) so it opens on the Visual Studio:
![visualstudio Potree](https://user-images.githubusercontent.com/29225486/65681021-6c495580-e058-11e9-9b4f-ecd6402db53b.png)

I try to build from visual studio and it says that "laszip_api.h" does not exit, I add it manually and still it does not work.

I think its because when i cmake lastools that variable laszip.lib is not generated.

I hope someone can help me !!

**Comment by bouthaynabakkouchi** [comment]
hello, 
I have the same thing!
Did you find a solution ?

**Comment by AlbionS** [comment]
No I did not find a solution ! So I am using the executable that is given by Potree. But I have the same problem for Ubuntu, I thing something is missing in their explanation !!! @bouthaynabakkouchi

**Comment by jwcde** [comment]
#311
