### ISSUE TITLE
Lastools make error "-std=c++14" with gcc 4.9.2-6 installed

### ISSUE THREAD

**Issue by nicox77** [potree/PotreeConverter#377]
Hi,
I've got troubles during the installation of Lastools , at the "make" part 

[root]# make
[  5%] Building CXX object src/CMakeFiles/laszip.dir/arithmeticdecoder.cpp.o
c++: erreur: unrecognized command line option ‘-std=c++14’
make[2]: *** [src/CMakeFiles/laszip.dir/build.make:59: src/CMakeFiles/laszip.dir/arithmeticdecoder.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:79: src/CMakeFiles/laszip.dir/all] Error 2
make: *** [Makefile:117: all] Error 2

I saw that the "-std=c++14" issue can come from gcc version, but mine is 4.9 now as required (It has been ugraded from 4.8 to 4.9). I'm on CENTOS 7
So well, I'm blocked , if someone have any ideas or tips many thanks !
Nico

**Comment by potree** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0. The new version includes laszip and precompiled windows lib/dll files.

**Comment by chs1234** [comment]
ㄱㅐ새끼들아 설치좀 도와줘라 진짜
