### ISSUE TITLE
[PotreeConverter_1.7PRE] Empty html files with -p command

### ISSUE THREAD

**Issue by dVurpillot** [potree/PotreeConverter#379]
Hello,

When I try to generate a webpage with the -p command, the html file produced is empty.

Best regards,

**Comment by m-schuetz** [comment]
Hi,

Potree is not yet bundled in this prerelease of the converter, so -p won't work.

**Comment by rcorbari** [comment]
Hello, so how to make a ready html page to upload with the converted file?

**Comment by potree** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0. PotreeConverter 2.0 currently doesn't have the option to automatically generate a page, but it is on the roadmap.
