### ISSUE TITLE
FLUSHING: ERROR: rename(p1, p2): invalid arguments: operation not permitted

### ISSUE THREAD

**Issue by Lux3d** [potree/PotreeConverter#380]
Hi, I’m trying to convert pointclouds. Small clouds with up to 50 million points are not the problem, but with bigger clouds the conversion stops at differnt stages, mostly above 50 million processed points with a flushing error!
I have tried several converter versions and differnt settings, but the problem is always the same.

(Platform is: Win64 2x xeon CPU, 128 GB RAM, GTX 1080 ti)  

P:\>PotreeConverter.exe "P:\clouds\oginal.las" -o "P:\converted" -p "nid" -l "10" --projection "+proj=utm +zone=32N +ellps=GRS80 +datum=ETRS89 +units=m +no_defs"
== params ==
source[0]:              P:\clouds\oginal.las
outdir:                 P:\converted
spacing:                0
diagonal-fraction:      200
levels:                 10
format:
scale:                  0
pageName:               nid
projection:             +proj=utm +zone=32N +ellps=GRS80 +datum=ETRS89 +units=m +no_defs

processing following attributes:
POSITION_CARTESIAN
RGBA
intensity
number of returns
return number
source id

AABB: {
        "min": [321487.806000, 5617917.139000, 232.079000],
        "max": [322022.511000, 5618464.127000, 419.724000],
        "size": [534.705000, 546.988000, 187.645000]
}

cubicAABB: {
        "min": [321487.806000, 5617917.139000, 232.079000],
        "max": [322034.794000, 5618464.127000, 779.067000],
        "size": [546.988000, 546.988000, 546.988000]
}

total number of points: 322.264.102
spacing calculated from diagonal: 4,73705
READING:  P:\clouds\oginal.las
INDEXING: 1.000.000 of 322.264.102 processed (0%); 1.000.000 written; 3,083 seconds passed
INDEXING: 2.000.000 of 322.264.102 processed (0%); 2.000.000 written; 4,869 seconds passed
INDEXING: 3.000.000 of 322.264.102 processed (0%); 3.000.000 written; 6,583 seconds passed
INDEXING: 4.000.000 of 322.264.102 processed (1%); 4.000.000 written; 8,544 seconds passed
INDEXING: 5.000.000 of 322.264.102 processed (1%); 5.000.000 written; 10,242 seconds passed
INDEXING: 6.000.000 of 322.264.102 processed (1%); 6.000.000 written; 11,962 seconds passed
INDEXING: 7.000.000 of 322.264.102 processed (2%); 7.000.000 written; 13,57 seconds passed
INDEXING: 8.000.000 of 322.264.102 processed (2%); 8.000.000 written; 15,275 seconds passed
INDEXING: 9.000.000 of 322.264.102 processed (2%); 9.000.000 written; 17,255 seconds passed
INDEXING: 10.000.000 of 322.264.102 processed (3%); 10.000.000 written; 18,97 seconds passed
FLUSHING: 8,899s

...

INDEXING: 221.000.000 of 322.264.102 processed (68%); 221.000.000 written; 723,507 seconds passed
INDEXING: 222.000.000 of 322.264.102 processed (68%); 222.000.000 written; 726,197 seconds passed
INDEXING: 223.000.000 of 322.264.102 processed (69%); 223.000.000 written; 728,803 seconds passed
INDEXING: 224.000.000 of 322.264.102 processed (69%); 224.000.000 written; 730,708 seconds passed
INDEXING: 225.000.000 of 322.264.102 processed (69%); 225.000.000 written; 732,56 seconds passed
INDEXING: 226.000.000 of 322.264.102 processed (70%); 226.000.000 written; 734,554 seconds passed
INDEXING: 227.000.000 of 322.264.102 processed (70%); 227.000.000 written; 736,574 seconds passed
INDEXING: 228.000.000 of 322.264.102 processed (70%); 228.000.000 written; 738,529 seconds passed
INDEXING: 229.000.000 of 322.264.102 processed (71%); 229.000.000 written; 740,511 seconds passed
INDEXING: 230.000.000 of 322.264.102 processed (71%); 230.000.000 written; 742,487 seconds passed
FLUSHING: ERROR: rename(p1, p2): invalid arguments: operation not permitted

**Comment by sihame95** [comment]
Hi Lux3d I'm facing the same problem right now. I would like to know if you succeed to solve the problem. because i'm really struggling here with this error i don't know the reason

**Comment by Lux3d** [comment]
Hi sihame95, 
it´s working now.
I decimated and saved the clouds with just 3 decimal places.

**Comment by Lux3d** [comment]
... and deleted most of the scalar fields.

**Comment by sihame95** [comment]
Hi Lux3d what do you mean by " I decimated the clouds " ?
Because now i can convert the point clouds with potree convertor while keeping the options of RGB and INTENSITY but when i try to add this to my php code and shell_exec it does not work i dont know why !! do you have any idea about that
