### ISSUE TITLE
Build fails on OS X Catalina

### ISSUE THREAD

**Issue by nickponline** [potree/PotreeConverter#381]
The error I receive is:

```
PotreeConverter/PotreeConverter/src/PotreeWriter.cpp:298:20: error: non-const lvalue reference to
      type 'Potree::Point' cannot bind to a temporary of type 'Potree::Point'
                                        writer->write(reader->getPoint());
```

**Comment by kpj** [comment]
See https://github.com/potree/PotreeConverter/issues/382#issuecomment-559613216

**Comment by potree** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on.

At the moment, there are only windows builds available, though.
