### ISSUE TITLE
FLUSHING: ERROR: attribute reader not implemented: Amplitude

### ISSUE THREAD

**Issue by rcorbari** [potree/PotreeConverter#385]
Hello,

I'm trying to convert a .las file of 38.000.000 of points.

After the first 10M I get the first flushing, then at 20M I get the following error:

`FLUSHING: ERROR: attribute reader not implemented: Amplitude
`
How can I solve this issue?

Thanks.

**Comment by potree** [comment]
Hi, 

PotreeConverter has been replaced by a complete rewrite, PotreeConverter 2.0. I'm closing this since PotreeConverter 1.7 won't be developed anymore and this bug may no longer apply. Feel free to open a new issue if PotreeConverter 2.0 still fails.
