### ISSUE TITLE
Option -i does not work with PotreeConverter compiled on Windows (works on linux though)

### ISSUE THREAD

**Issue by alexisheloir** [potree/PotreeConverter#387]
I could not convert point clouds using PotreeConverter on windows until I removed the "-i" ```
argument prefix before the input file argument in the PotreeCOnverter command line on Windows.

On windows :
`PotreeConverter -i input.pts -o outputDir`
does not work while
`PotreeConverter input.pts -o outputDir`

Works.

This behavior is not consistent with the documentation nor with the behavior of PotreeCOnverter under LInux.

**Comment by rboulkhi** [comment]
I do indeed experience the same behaviour on my Windows machine. I confirm additionally that the issue does not occur on my ubuntu OS.

**Comment by sheikware** [comment]
Fixed in PR #335. Not sure why that was never merged... issue occurs on Linux when using --source as well when not first argument.

**Comment by potree** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. The requested feature or issue may not apply to PotreeConverter 2.0, either because it is fixed or the feature is not yet ported.
