### ISSUE TITLE
--incremental option error

### ISSUE THREAD

**Issue by Vagabun** [potree/PotreeConverter#389]
Hi!
Recently I've encountered with a strange incremental conversion error:

`ERROR: Invalid PointAttribute name: 'name'`

I'm using `-aabb` option as README recommends, any thoughts on what can be a problem?

**Comment by potree** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. The requested feature or issue may not apply to PotreeConverter 2.0, either because it is fixed or the feature is not yet ported.
