### ISSUE TITLE
Blank page while trying to host pointclouds on my website

### ISSUE THREAD

**Issue by guilhermegiandoni** [potree/PotreeConverter#390]
Hello guys, i'm getting this 

![image](https://user-images.githubusercontent.com/60268377/73192522-e9203500-4107-11ea-9865-a4dae4c5e5d1.png)

I thought it was an error in patching, but my html file looks ok:

![image](https://user-images.githubusercontent.com/60268377/73192639-14a31f80-4108-11ea-90de-fd5fb4ec172b.png)

what am i missing?

**Comment by potree** [comment]
Please check the errors in your dev console. This often happens if the imports are wrong.
