### ISSUE TITLE
error: 'memcpy' was not declared in this scope at BINPointReader

### ISSUE THREAD

**Issue by satoshimiya** [potree/PotreeConverter#391]
In the process of building PotreeConverter by Mac OSX High Sierra (10.13.6), I have got the error below. Are there anyone facing the same issue??

------
Scanning dependencies of target PotreeConverter
[  8%] Building CXX object PotreeConverter/CMakeFiles/PotreeConverter.dir/src/BINPointReader.cpp.o
/PotreeConverter/src/BINPointReader.cpp: In member function 'virtual bool Potree::BINPointReader::readNextPoint()':
/PotreeConverter/src/BINPointReader.cpp:182:64: error: 'memcpy' was not declared in this scope
     memcpy(target.data(), (buffer + offset), attribute.byteSize);
                                                                ^
make[2]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/src/BINPointReader.cpp.o] Error 1
make[1]: *** [PotreeConverter/CMakeFiles/PotreeConverter.dir/all] Error 2
make: *** [all] Error 2
-----

**Comment by m-schuetz** [comment]
Interesting, works fine for me in Visual Studio. Can you try this here: https://stackoverflow.com/questions/24850479/memcpy-was-not-declared-in-this-scope

Try replacing ```memcpy``` with ```std::memcpy```, and if that still doesn't work, try adding ```#include <cstring>```

**Comment by satoshimiya** [comment]
thanks! it worked!
