### ISSUE TITLE
Hierarchy files duplicate information

### ISSUE THREAD

**Issue by sheikware** [potree/PotreeConverter#392]
When writing the hierarchy files (*.hrc) and there are enough points to require nested folders, the hierarchy file in the root directory will contain information about the first level in the next nested folders.

As an example, assume hierarchy step size is 5.
- r04266 gets moved into subdirectory. Subdirectory includes r04266.hrc, r04266.{laz}, r042661.{laz}, r0426610.{laz}, etc. 
- When you go through the breadth search tree in r.hrc, you will get information about r042661.{laz} and any other r04266x.{laz} files...
- When you go through the breadth search tree in r04266.hrc, you get redundant info about r042661.{laz} and any other r04266x.{laz} files...

I assume this is a bug and I was able to make a fix to generate without the redundancy (can get information from all files, etc) but I did see that messes up the rendered as it doesn't appear to then load...

Any reason for this behavior?

**Comment by m-schuetz** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, which stores all points in a single file.
