### ISSUE TITLE
HTML config "as is"

### ISSUE THREAD

**Issue by EmmanuelAmann** [potree/PotreeConverter#394]
Hello everyone,
I am not a programmer, but still a happy potree user.
Currently I am looking at how I could move, rotate, change the point budget, point size, attribute, volume clip and so on ... AND THEN SAVE ALL THESE PARAMETERS so that I can edit my HTML quickly and easily before uploading it again.
Any idea?
Thanks All

**Comment by m-schuetz** [comment]
Hi, please have a look at the http://potree.org/potree/examples/load_project.html demo of the latest version of Potree. It may support at least some of the attributes.
