### ISSUE TITLE
forget to update leaf nodes bounding box

### ISSUE THREAD

**Issue by cugxy** [potree/PotreeConverter#397]
You seem to forget to update the bounding boxes of the leaf nodes.
the code may be on PotreeWriter.cpp line 173

**Comment by m-schuetz** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. The requested feature or issue may not apply to PotreeConverter 2.0, either because it is fixed or the feature is not yet ported.
