### ISSUE TITLE
not exists folder resorces release 1.7 PRE

### ISSUE THREAD

**Issue by carlos00027** [potree/PotreeConverter#398]
i don't speak english sorry.

but not exists folder in file  zip of the release PotreeConverter 1.7 PRE but in the version 1.6 yes.

**Comment by m-schuetz** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. The requested feature or issue may not apply to PotreeConverter 2.0, either because it is fixed or the feature is not yet ported.
