### ISSUE TITLE
Convert .e57

### ISSUE THREAD

**Issue by sechanbask** [potree/PotreeConverter#399]
Hello,

I register scan with RECAP PRO. So my workflow is quite long :

- Register with RECAP
- Export in .e57 file
- Open with Cloudcompare
- Export in las file
- Convert with potree convert 

To simplify it, I would like to convert .e57 to potree. Is it possible ?

**Comment by AlbionS** [comment]
you can convert it to las with https://github.com/LAStools/LAStools/blob/master/bin/e572las_README.txt and you take the las and convert it to Potree with PotreeConverter
