### ISSUE TITLE
Maps background and volume in Potree

### ISSUE THREAD

**Issue by EucentreMM** [potree/PotreeConverter#400]
Dear all,
I have converted one of our pointcloud (.las/.laz) using PotreeConverter version 1.6 
I have some questions related to some of the features of Potree:
1) I have noticed that the interesting feature of annotations is not apparently present in our Viewer.  Is it present only in some particular version of Potree?
2) Our point cloud is geo-referenced, we were able to visualize the minimap in the viewer. How is it possible to visualize also the map in the background - None(Cesium)? Is there a specific string code to add during the conversion?
3) Is it possible to measure the volume of a portion of point cloud selected? From our preliminary test, It seems that the “Volume measurement” box show the volume of the box and not of the portion of point cloud selected by the box. 

Thank you in advance.
Martina

**Comment by m-schuetz** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. The requested feature or issue may not apply to PotreeConverter 2.0, either because it is fixed or the feature is not yet ported.
