### ISSUE TITLE
Add Support .pcd files

### ISSUE THREAD

**Issue by spacemanspiff0211** [potree/PotreeConverter#401]
Hey, 
Is there any plan to support pcd files generated from point cloud library?

**Comment by spacemanspiff0211** [comment]
If you could point me to any documentation/guide lines, Im willing to contribute  to this.

**Comment by SwiftWinds** [comment]
Also looking for this

**Comment by brawer** [comment]
@spacemanspiff0211 This [JavaScript implementation](https://gitlab.com/taketwo/three-pcd-loader) might be a good starting point. For what it’s worth, this [StackOverflow post](https://stackoverflow.com/questions/44635130/is-there-a-specification-for-the-pcd-file-format) says there’s no real documentation for the PCD format, only an apparently incomplete [description](http://pointclouds.org/documentation/tutorials/pcd_file_format.php) that’s currently unreachable but got snapshotted by the [Internet Archive](https://web.archive.org/web/20191020171559/http://pointclouds.org/documentation/tutorials/pcd_file_format.php). The C++ library at pointclouds.org seems like it would be a rather massive dependency, so it might be easier to write a parser from scratch.

**Comment by m-schuetz** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. The requested feature or issue may not apply to PotreeConverter 2.0, either because it is fixed or the feature is not yet ported.
