### ISSUE TITLE
Does anyone know how to install PotreeConverter on LUNIX using WINE. 

### ISSUE THREAD

**Issue by AlbionS** [potree/PotreeConverter#402]
Does anyone know how to install PotreeConverter on LUNIX using WINE ?

I've tried but some of the dll are missing. I tried to add them but yet i get the same error.

Did anyone install it using WINE ?

I am unable to compile it on Unix, the exemple that is given is not working. Too many things missing and it is from 2015. That's why I am trying to run the executable of Windows on Ubuntu through WINE

**Comment by m-schuetz** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. The requested feature or issue may not apply to PotreeConverter 2.0, either because it is fixed or the feature is not yet ported.
