### ISSUE TITLE
Isn't it an endless loop once steped into node->level == currentLevel ?

### ISSUE THREAD

**Issue by muyanchen-zen** [potree/PotreeConverter#408]
https://github.com/potree/PotreeConverter/blob/36cabdf53ff5ed89c338e314f0ea6b2d09a70636/PotreeConverter/src/PotreeWriter.cpp#L398

**Comment by m-schuetz** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. The requested feature or issue may not apply to PotreeConverter 2.0, either because it is fixed or the feature is not yet ported.
