### ISSUE TITLE
Performance issue Indexing speed is getting slow

### ISSUE THREAD

**Issue by nmenu** [potree/PotreeConverter#409]
Hi,

Any ideas why the indexing of points is getting so slow after a while ?

I start indexing at a decent speed the first 10 to 20 mio points are indexing fine at a decent speed, then, suddenly, for the later points, indexing becomes vers slow.

Only CPU seems to work hard, Ram usage is flat, disc access, low, GPU almost non existent...

![potree_indexing_speed](https://user-images.githubusercontent.com/43078753/84754580-df1ca700-afc0-11ea-862b-ba95f0a57591.png)

First 1'000'000 take around 3.5 seconds, at 20'000'000 we are at around 40 sec, suddenly around 26'000'000 it take 219 sec., up to more than 2000 sec. at 30'000'000. 

Processing large dataset take forever. Is this performance issue expected ? Anyworkaround or fix ?
Thx. Nicolas

**Comment by m-schuetz** [comment]
Some decrease in indexing speed is expected, but that's way too much. Not sure what's happening but there is a chance that the point cloud is structured in a way that is highly unfavourable for potree. Things that affect or help performance of the converter:

* If your point cloud is sorted in morton order or stored in individual tiles of around 1-50 million points, conversion will be faster
* Conversely, if points are completely shuffled, conversion will be very slow
* Point clouds with a very large extent but with most points concentrated in a small region can slow conversion speed down considerably. 

Could you perhaps send me a link to the data set with just the first 40 million points?

**Comment by nmenu** [comment]
Hi Markus,

You are right I am unsure what happened with this original point cloud but I recreate a fresh LAS with CloudCompare, and now the potreeconverter worked perfectly fine and fast.

The original cloud I was working with was a structured E57 converted to LAS, and now I went from an unstructure PTS to LAS, and this time, it works perfect.

Thanks for your help and thumbs up for Potree ! You are a genius++

**Comment by vadnart1** [comment]
Hi Markus, all,

I have the same exact problem.  I have an .e57 LiDAR that I've converted using e572las to a .laz then trying to run potreeconvert.

![image](https://user-images.githubusercontent.com/26193375/84968398-02884480-b0dc-11ea-8ad2-af053023e292.png)

here are the links to the files. 
1.  [converted laz file using e572las.  note its 111MB](https://optelos-data.s3.amazonaws.com/test/gg00000002.laz)
2. [orignal e57 file.  note 843MB ](https://optelos-data.s3.amazonaws.com/test/1_gg002.e57)

by the way this is part of a 105GB LiDAR w/ 131 scans that I am trying to convert and view in Potree.
