### ISSUE TITLE
Potree.js PointAttributes assignment

### ISSUE THREAD

**Issue by fpirotti** [potree/PotreeConverter#412]
I managed to compile Potree 1.8 for linux - at first it did not find the "page_template" - I had to copy the parent folder "resources" directly in root path (/resources/page_template) and everything worked - but points are not loaded. 

Checking the page debugger it shows that the attributes seem not to be assigned correctly in the Potree.js file

![immagine](https://user-images.githubusercontent.com/1391292/87906486-fe48a180-ca62-11ea-85cd-381ecf577c43.png)

**Comment by m-schuetz** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0, and the old version will no longer be worked on. The requested feature or issue may not apply to PotreeConverter 2.0, either because it is fixed or the feature is not yet ported.
