### ISSUE TITLE
Loss of attributes: "GPS time", "Scan angle" and "User data" in LAZ/LAS format.

### ISSUE THREAD

**Issue by fcespedes-pathway** [potree/PotreeConverter#413]
Hi, When I run PotreeConverter.exe with the following way:
PotreeConverter.exe C:\example.laz -o C:\potree_converted --output-attributes GPS_TIME --output-format LAZ --overwrite

the information "GPS time", "Scan angle" and "User data" always appears as zero in the output files.

It should be noted that I did tests with the last 3 versions labeled "Pre-release" to date (1.6_2018_07_29, 1.7PRE, 1.7beta) and I obtained the same result in all one.

Any help in this regard is appreciated. thanks.

**Comment by m-schuetz** [comment]
Hi,

Closing this because PotreeConverer 1.7 is now replaced by a complete rewrite, PotreeConverter 2.0. The 3 attributes are handled by the new converter, but user data has no proper visualization in Potree, yet.
