### ISSUE TITLE
OpenStreetMap arrow rotated 180 degrees

### ISSUE THREAD

**Issue by bisenberger** [potree/PotreeConverter#414]
I exported a dense cloud from Agisoft Metashape to potree (*.zip). The coordinate system for the Metashape chunk is WGS 84/ UTM zone 40N. The OpenStreetMap in Potree shows the correct location, but the arrow that indicates the viewing direction is off 180 degrees.

![image](https://user-images.githubusercontent.com/69024075/89040468-750a5800-d309-11ea-9b26-59d49d4542d4.png)

http://digital-mapping.net/potree/wadi_doka.html

**Comment by m-schuetz** [comment]
Hi, that's not an arrow but rather an indication of the view frustum.

**Comment by bisenberger** [comment]
Hi m-schuetz,
That makes perfect sense.

Potree is really cool. I wish I had found it sooner. It is the best way I have found to present my Agisoft Photoscan/Metashape photogrammetry.

Thank you so much for making it available.
Bill

**Comment by m-schuetz** [comment]
You're welcome, glad to hear you've got god experiences with it!
