### ISSUE TITLE
@adrianokamo I've been working on a lot of PHP lately, so forgive me if I've forgotten proper command line inputs. However, I think I see a couple issues already.

### ISSUE THREAD

**Issue by adrianokamo** [potree/PotreeConverter#423]
Thank you very much I think you can solve the problem since it is something difficult for me, although it seems easy to enter command lines without being familiar.

**Comment by midnight-dev** [comment]
Looks like you accidentally opened a new issue. You should see an option to close this issue. Go ahead and close it so it doesn't cause any confusion. You can look in your notifications to find old issues like the one you originally posted in.
