### ISSUE TITLE
Missing VCRUNTIME140_1.dll

### ISSUE THREAD

**Issue by Marcuzzo77** [potree/PotreeConverter#424]
Hi, I have a problem when I launch the version 2.0 executable, it sends me an error. Miss the following dll:
VCRUNTIME140_1.dll
Any suggestions?

**Comment by midnight-dev** [comment]
Most people probably already have VC++ runtimes installed, but if it's a necessary dependency, maybe it should be included in the readme.

Were you able to fix this by installing 2017/2019 Visual C++ redistributable? Also, were you using Windows 10, or was it an older version like Windows 7? 

_The more info, the better. Someone might have a similar problem in the future, and details in this thread could help._
