### ISSUE TITLE
Size Octree

### ISSUE THREAD

**Issue by FrenchTrott** [potree/PotreeConverter#428]
Hi !
I test potree 2.0 converter.

I just discovered two weird things.
the generated octree.bin file is 3Go while the input file is less than 500Mo. 
File https://fromsmash.com/hWqBSFE~Kc-ct

And also if in the input of the converter we give it a folder; it does the conversion but stops before the end.

Are these two bugs?

Thanks !

**Comment by m-schuetz** [comment]
Fixed, build available here: https://github.com/potree/PotreeConverter/releases/tag/2.0.1
