### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by FrenchTrott** [potree/PotreeConverter#436]
Hi markus,

Thanks for new release.

2 questions : 

- is it planned to pass in the input a txt file with the list of files to convert?

- Have you planned a kind of potreeextractor to extract a box from the bin file to regenerate a las / laz file for example?

**Comment by potree** [comment]
> Have you planned a kind of potreeextractor to extract a box from the bin file to regenerate a las / laz file for example?

Yes, there are already some initial results: https://www.youtube.com/watch?v=aWCgsLejKq4

> is it planned to pass in the input a txt file with the list of files to convert?

Not planned, no. The converter needs a bounding box so if the input is a text file, it'd need to do one full pass to compute the bounding box and convert it into a more suitable format first. At this point, it'd already be possible to use another application that can convert the text file into a las file.

**Comment by FrenchTrott** [comment]
fine, and server side to extract ?

**Comment by m-schuetz** [comment]
Initially, it will only be client side. The binaries that do the exctraction could be integrated into a server side application, though.

**Comment by midnight-dev** [comment]
@FrenchTrott It sounds like you were asking about inputting a _list_ of LAS files in text format like you could with converter 1.7. Was that it or did you mean a list of points in a text file?

Just double checking.
