### ISSUE TITLE
Projection not output in metadata.json

### ISSUE THREAD

**Issue by sc0tt0** [potree/PotreeConverter#439]
I've noticed the mini potree map not displaying in las files that were processed using v2.0. It seems the "projection" value is not output in metadata.json, where it was in previous versions (cloud.js). If this is by design, how to restore the map in potree viewer?

**Comment by potree** [comment]
Hi, 

Projection isn't ported yet but there are two possible workarounds for now:

First one: In the callback of loadPointCloud, set the projection string before adding the point cloud to the scene:
```
Potree.loadPointCloud(url, name, e => {
	...

	pointcloud.projection = "...";
	
	scene.addPointCloud(pointcloud);

	...
});
```

Second one: Just speculating here but you should be able to manually set the projection string in the metadata.json file. 

Let me know if this works. The projection parameter of the converter will be reimplemented soon.

**Comment by sc0tt0** [comment]
Yes setting the point cloud projection in code works. Thank you
