### ISSUE TITLE
List Octree

### ISSUE THREAD

**Issue by FrenchTrott** [potree/PotreeConverter#446]
Hello Markus,
is there a solution to have the list and the coordinates of each octree?
Thank you in advance,

**Comment by m-schuetz** [comment]
I don't quite understand. If you want to get a list of the pointclouds, you can call
```viewer.scene.pointclouds```
and to get a list of positions:
```viewer.scene.pointclouds.map(p => p.position)```

**Comment by FrenchTrott** [comment]
thanks, but I'm talking about each octree node. ;)

**Comment by m-schuetz** [comment]
for the visible nodes: ```viewer.scene.pointclouds[0].visibleNodes``` 

For the other nodes, you'll have to implement an octree traversal starting from pointcloud.root and traversing into node.children. However, not the whole hierarchy is loaded at runtime, only parts that are needed. 

CPotree is corrently in development and it loads all nodes, see [PotreeLoader](https://github.com/potree/CPotree/blob/develop/include/PotreeLoader.h)
