### ISSUE TITLE
Can't load two 2.0 format pointclouds in the same page the way you can with 1.7 clouds.   I can load one 2.0 , and additional 1.7 format clouds.

### ISSUE THREAD

**Issue by smcavoy12** [potree/PotreeConverter#449]
I've found that I can't load two 2.0 format pointclouds in the same page the way you can with 1.7 clouds.   I can load one 2.0 , and additional 1.7 format clouds.

So This works:
https://pointcloud.ucsd.edu/Villa_Arianna.html

This works:
https://pointcloud.ucsd.edu/Pompeii.html

Combining the "leturl =" blocks on top of eachother gives an error
https://pointcloud.ucsd.edu/Multi_2p01.html

![error3](https://user-images.githubusercontent.com/13354749/92774623-84da7a80-f352-11ea-8f6e-13ec89067f2b.PNG)

_Originally posted by @smcavoy12 in https://github.com/potree/PotreeConverter/issues/443#issuecomment-690560358_

**Comment by potree** [comment]
Hi, the problem here is that url is declared two times. "let" doesn't allow that. You'll have to give them different names, e.g., url1, url2.

**Comment by potree** [comment]
Alternatively, you can also encapsulate both parts into { } blocks.


```javascript
{
	let url = "pointclouds/Villa_Arianna/metadata.json";
	Potree.loadPointCloud(url).then(e => { 
		let pointcloud = e.pointcloud;
		let material = pointcloud.material;
		
		material.activeAttributeName = "rgba";
		material.minSize = 2;
		material.pointSizeType = Potree.PointSizeType.ADAPTIVE;
		material.shape = Potree.PointShape.CIRCLE;
		
		viewer.scene.addPointCloud(pointcloud);
		viewer.fitToScreen();

	});
}

{
	
	let url = "pointclouds/Pompeii/metadata.json";
	Potree.loadPointCloud(url).then(e => { 
		let pointcloud = e.pointcloud;
		let material = pointcloud.material;
		
		material.activeAttributeName = "intensity";
		pointcloud.material.intensityRange = [0,65535];
		material.minSize = 2;
		material.pointSizeType = Potree.PointSizeType.ADAPTIVE;
		material.shape = Potree.PointShape.CIRCLE;
		
		viewer.scene.addPointCloud(pointcloud);
		viewer.fitToScreen();

	});
}
```

**Comment by smcavoy12** [comment]
AH, perfect thank you! the braces worked perfectly.
