### ISSUE TITLE
Version 2.0 generates only metadata.json for some PTX and PLY files

### ISSUE THREAD

**Issue by dsroshan** [potree/PotreeConverter#454]
I am using a PC with an Intel Core i3-6006U CPU and 4 GB of RAM. I tried to convert a few sample files from libE57 and The Stanford 3D Scanning Repository using PotreeConverter 2.0. All I am getting is just a metadata.json inside the chunks directory and the following converter output.

```
#threads: 4
flags:
#paths: 0

output attributes:
name                              offset    size
================================================
================================================
                                               0
================================================
cubicAABB: {
        "min": [inf, inf, inf],
        "max": [-nan(ind), -nan(ind), -nan(ind)],
        "size": [-inf, -inf, -inf]
}
#points: 0
total file size: 0.0 bytes
target directory: 'pump.ptx_converted'
maxPointsPerChunk: 0

=======================================
=== COUNTING
=======================================
tStartTaskAssembly: 0.000002s
countPointsInCells: 0.021885s
finished counting in 0s
=======================================
createLUT: 0.069134s

=======================================
=== CREATING CHUNKS
=======================================
distributePoints0: 0.000306s
distributePoints1: 0.000649s
finished creating chunks in 0s
=======================================

=======================================
=== INDEXING
=======================================
```

Here are two of those files I just tried to convert:
- [pump.ptx](https://drive.google.com/file/d/1xPRLZ5tXqiYjcXnB3aQSGTeiV-weLeMs/view?usp=sharing) (90 MB)
- [armadillo.ply](https://drive.google.com/file/d/1lJ8kgrnbWia7yB96zr50w6sZfkcfR673/view?usp=sharing) (6.59 MB)

**Comment by m-schuetz** [comment]
Hi, PotreeConverter only supports las/laz files. You can convert them to las/laz with Cloud Compare.

**Comment by dsroshan** [comment]
I saw this [page](https://libraries.io/github/potree/PotreeConverter) saying that the PotreeConverter can build a potree octree from las, laz, binary ply, xyz or ptx files. Does the older version 1.7 support ptx and ply files?

**Comment by m-schuetz** [comment]
Not sure about 1.7, but 1.6 did support ply files.

**Comment by dsroshan** [comment]
What about ptx files? Does 1.6 support it too?

**Comment by dsroshan** [comment]
Okay. Thanks for the quick reply @m-schuetz .
