### ISSUE TITLE
Generate link for classes rendering 

### ISSUE THREAD

**Issue by Ben29980** [potree/PotreeConverter#456]
Hello Potree community,
Is There any possibility to generate a link such as classification schemes, but for rendering classification material ?
I tried this but not worked 

>let schemes = [
						{name: "RAINBOW", icon: `${Potree.resourcePath}/icons/gradients_rainbow.png`},
						{name: "SPECTRAL", icon: `${Potree.resourcePath}/icons/gradients_spectral.png`},
						{name: "YELLOW_GREEN", icon: `${Potree.resourcePath}/icons/gradients_yellow_green.png`},
						{name: "PLASMA", icon: `${Potree.resourcePath}/icons/gradients_plasma.png`},
						{name: "GRAYSCALE", icon: `${Potree.resourcePath}/icons/gradients_grayscale.png`},
						{name: "CLASSIFICATION", icon: `${Potree.resourcePath}/icons/gradients_rainbow.png`},
					];

**Comment by m-schuetz** [comment]
You'll have to customize the user interface to do that. It's not directly part of potree.

**Comment by Ben29980** [comment]
Hello Succeeded by changing the 

> // Create title element with jquery
> 					let elTitle = $(`
> 						<span>
> 						 MNE 
> 						<img title="Elevation" name="action_elevation" src="${Potree.resourcePath}/icons/profile.svg" class="annotation-action-icon"/>
> 						/ Ortho + MNE <img title="RGB and Elevation" name="action_both" src="${Potree.resourcePath}/icons/rgb_elevation.png" class="annotation-action-icon"/>
> 						/ Ortho <img title="RGB" name="action_rgb" src="${Potree.resourcePath}/icons/rgb.svg" class="annotation-action-icon"/>
> 						/ Classification <img title="CLASSIFICATION" name="action_classification" src="${Potree.resourcePath}/icons/rgb.svg" class="annotation-action-icon"/>
> 						
> 					</span>`);

Then:
```
elTitle.find("img[name=action_classification]").click( () => {
					viewer.scene.pointclouds.forEach( pc => pc.material.pointColorType = Potree.PointColorType.CLASSIFICATION );
				});
```
