### ISSUE TITLE
How to Call for Compression

### ISSUE THREAD

**Issue by smcavoy12** [potree/PotreeConverter#459]
Hi! I'm eager to use the new compressed format, how would I call it? Apologies if I'm not seeing it documented.

is it something like:
--output-format BROTLI ?

Thanks!
-Scott

**Comment by potree** [comment]
Hi, it's "--encoding BROTLI" but the exact format is not yet set in stone. I'd be glad if you could give it a try, though, and report your results. It's not quite as efficient as LAZ, but usually compresses down to at least 1/3rd of the size with many also compressing down to 1/4th. 

Your case might be a bit special though, so I'm very curious to learn how it works out for you. The main thing that laz does that makes it work so well with your data is that it predicts the next coordinate from the previous coordinates, and your coordinates are almost perfectly predictable. The brotli compressed format in Potree does not do that so it likely won't work nearly as good. 

In any case, please give it a try and let me know of the results!

**Comment by smcavoy12** [comment]
Thanks! I'll email you with our compression comparisons.
