### ISSUE TITLE
Support for *.ply files

### ISSUE THREAD

**Issue by AnasHamed73** [potree/PotreeConverter#460]
The older version of the converter (1.7) runs the conversion job for *.ply files without any issues, but I cannot get the new converter to work with such files. It instantly terminates in _indexer.cpp_ with a segmentation fault which is a result of the _metadata.json_ file not containing the required properties, which, in turn, is due to the absence of a dedicated .ply file reader (or at least that's what my guess is). It doesn't seem to have a problem with *.las files, though.

Are *.ply files supported in version 2, or is it still a work in progress? I can see that the older version had a dedicated _PlyPointReader_ for .ply files, but there doesn't seem to be one in version 2.

For clarification, I ran the converter like so:
`./PotreeConverter -i ./file.ply -o ./out`
The output is depicted below
![ply_conversion](https://user-images.githubusercontent.com/23470786/94975296-406c7580-04df-11eb-9a0f-b3381924d5fc.png)

**Comment by m-schuetz** [comment]
Hi, 

PotreeConverter 2 only work with las and laz. Please use tools like CloudCompare or lastools to convert them from ply to las. Maybe PDAL works as well?

**Comment by han1396735592** [comment]
Does version 2.0 have plans to support ply format?
