### ISSUE TITLE
No compression with --encoding brotli

### ISSUE THREAD

**Issue by Jean-Roc** [potree/PotreeConverter#461]
Hi, I've been trying release 2.0.2 win64 with the --encoding brotli parameter (found it in your twitter) but the output stays lossless, is this the correct way to do it ?

regards,
JR

**Comment by m-schuetz** [comment]
Try upper case, "--encoding BROTLI".  It's not entirely set in stone, yet, but if you try it, let me know of the results. You'll also need to get the lattest release, 2.0.2.

**Comment by Jean-Roc** [comment]
The upper case did it ! It took 35s instead of 16s for 70M points from a laz file with poisson sampling, the result compression rate is 27%
