### ISSUE TITLE
Add or remove data in octree.bin

### ISSUE THREAD

**Issue by FrenchTrott** [potree/PotreeConverter#464]
Hi,
Is it planned to be able to add or remove parts of the point cloud in the octree.bin afterwards?
In short, edit the octree.bin
Thanks in advance,

**Comment by m-schuetz** [comment]
Not planned since it's a rather large effort. [CPotree](https://github.com/potree/CPotree) will soon be able to apply filter operations on Potree 2.0 point clouds, and store the result in las files.
