### ISSUE TITLE
Black Points / Tiles 

### ISSUE THREAD

**Issue by dioutan** [potree/PotreeConverter#465]
Hello ,
I only have black points after conversion, can you help me to resolve it?
I use PotreeConverter 2.0.1.

Thanks

**Comment by m-schuetz** [comment]
Does it help if you select a different attribute in the sidebar? "Scene -> pointclouds -> xxx -> Attribute"

If not, please post or send a link to a hosted web page that I can take a look at.

**Comment by dioutan** [comment]
Yes I tried, but I want the rgb, and this one is all black,
At the moment  I work locally, I can send you a link to download the cloud?

**Comment by dioutan** [comment]
Here is the download link

https://www.transfernow.net/04lH7M102020

Thanks a lot

**Comment by dioutan** [comment]
Hello Makus,

Here the hosted web page that you can take a look at.

http://cai-etudis.fr/Iteuil_Part3_sans_arbres_5f846770c8d9a/pointclouds.html

Thank you !

**Comment by potree** [comment]
Thanks!

According to metadata.json, all rgb color values are zero, see min and max. Not sure why this would happen, the converter should be copying the original unaltered rgb values. Can you send me a link to the las or laz file?

```
{
	"name": "rgb",
	"description": "",
	"size": 6,
	"numElements": 3,
	"elementSize": 2,
	"type": "uint16",
	"min": [0, 0, 0],
	"max": [0, 0, 0]
}
```

**Comment by dioutan** [comment]
Thank you for your answer,

Here a link to my las file,

https://www.transfernow.net/ARJ7Jm102020

**Comment by potree** [comment]
Your las file does not have colors.
