### ISSUE TITLE
Black pointclouds and unable to read XYZ

### ISSUE THREAD

**Issue by HTBernard** [potree/PotreeConverter#466]
Hi, I've been trying to convert a part of a project in LAS format and I went through some issues I've been trying to fix since an hour :

1 - I'm not sure to get what format PotreeConverter can get in input, I tried LAS, LAZ and XYZ but it seems unable to resolve XYZ type, as it find 0 points in the file. Is there any other type ? I think I also saw EPT format

2 - Now the main point, with LAS and LAZ type, all I can get is a fully black point cloud, I tried few things I saw in other topics but nothing seems to be the answer. Does anyone been through this ?

**Comment by potree** [comment]
* Make sure that your las file actually as rgb data. If it has, also try changing the attribute in the sidebar to "rgba". See https://github.com/potree/PotreeConverter/issues/465
* If that doesn't work, please upload a working html web page somewhere.
* If I can't find an issue with the web page, please send me the las/laz file. XYZ is not supported.

**Comment by HTBernard** [comment]
Hi, for the black pointcloud, the issue #465 was the answer in fact thanks a lot !

Have a good day !
