### ISSUE TITLE
Ubuntu can't find PotreeConverter command

### ISSUE THREAD

**Issue by BeardyMan37** [potree/PotreeConverter#470]
I managed to build and make PotreeConverter successfully in Ubuntu 20.04 without any error. But now, when trying out the command, ubuntu says it can't find the command PotreeConverter. Any help will be appreciated.

**Comment by midnight-dev** [comment]
Just making sure, you're trying to run `PotreeConverter` in the path that it was compiled to, right? You should be able to see the file with `ls`. 

If you see it but it just won't run, try making it executable and running it with a relative path (Linux can be stubborn about this). 

That is, when you're in the correct working directory: 

`sudo chmod +x PotreeConverter`
`./PotreeConverter YOUR-OPTIONS`

If you can't find the file, then there may be bigger problems here.

**Comment by BeardyMan37** [comment]
Yeah, it worked now. I thought PotreeConverter would be globally installed. My mistake. Thanks for the prompt reply.

**Comment by midnight-dev** [comment]
If it was an independent program, I'd suggest placing it in a bin folder. But this isn't a lone application... A couple of its features are dependent on the files around it, like the HTML page generator. I think it's generally a good idea to keep things simple and place it somewhere on your desktop in a directory that's easy to remember. 

You _can_ modify the bash terminal to look elsewhere by adding a line to the configuration file, but the name of the file escapes me right now. And it's easy to forget that you added a path to _every_ scope, so I'd still recommend just making a simple path in your home dir so you can easily refer to it like: `~/pc/PotreeConverter YOUR-OPTIONS`

Happy converting!
