### ISSUE TITLE
[Converter2] visibility issue

### ISSUE THREAD

**Issue by HeadLessHUN** [potree/PotreeConverter#475]
Hi there!

I converted a few clouds with the 2.0 converter these are georeferenced clouds in the EPSG23700 coordinatesystem. which has a boundary of these 
Projected bounds:
421391.21 48212.58
934220.63 366660.88

My cloud is around the center. las precision has been set to 0.0001 
684692.78 201865.84
if i calculate correctly it is out of range for int32.

If i try to convert with brotli then the viewer cannot load the cloud at all, byteoffset error during position attriubte loading. Without brotli it can be viewed, but half of the points are aligned on a single line, maybe 0,0,0 or int maximum. i don't know it.

So my question is that the issue is with my precision? if yes can i modify it without reconvert? 

Sorry but the clouds are confident so i cannot share it with you.

**Comment by potree** [comment]
If points are on a single line, it's usually because x and y are in polar coordinates, and z is in meters. Can you confirm that all coordinates are in meters?

**Comment by HeadLessHUN** [comment]
I can confirm that everything is in meters. but in the laz file i came across with a resolution warning, which i was not notified during writing with pdal.
WARNING: stored resolution of max_x not compatible with x_offset and x_scale_factor: 6XXXXX.36174871004
WARNING: stored resolution of max_y not compatible with y_offset and y_scale_factor: 2XXXXX.95396192808
WARNING: stored resolution of max_z not compatible with z_offset and z_scale_factor: 1XX.88563855622283

i preprocess the clouds with pdal. i subsample, and merge them before potree convert. I used auto offset, but i might need some manual offset value as well.. I hate georeferenced clouds and their big numbers :+1: 

So i think the integer overflow happens here somewhere, but the strange things is that i can view, successfuly if it is converted with 1.7 format. and can be viewed perfectly in other viewers, like cloud compare

**Comment by HeadLessHUN** [comment]
I rescaled the cloud to precision 0.0003 in my calculation it would be enough to cover this coordante system.
but the issue is the same, mybe i just mislead you with the line thing, Im not sure it is there and if there is not my main issue i think here is a picture with converted with 2.0.2 As i zoom in to the cloud some other points are loaded, but not much.
![image](https://user-images.githubusercontent.com/10095691/98717552-842f8600-238d-11eb-9779-dde97ebb51f1.png)
seems like the octree nodes get downloaded i can see it in the network view, they get downloaded and as i move around there ar more nodes gets loaded, but no point cloud.

this is the same cloud from same source files except it is converted with 1.7 (addedd a clipping volume to hide its shape)
![image](https://user-images.githubusercontent.com/10095691/98718370-a70e6a00-238e-11eb-8acd-3fd82e07833e.png)

**Comment by potree** [comment]
Unfortunately I can't really tell what causes this issue from just the images. If there is any way to send them to me, I can take a look at the issue.

**Comment by HeadLessHUN** [comment]
Oh my oh my. It was an issue with the webserver all along... i used a one click webserver without an issue till now but from now on i'll be using nginx on windows as well. Thank you for your help.

Default enoding and brotli works as well. Just in case somebody come across with tis the webserver was mongoose.
