### ISSUE TITLE
Converter not running correctly on win 10

### ISSUE THREAD

**Issue by lastshot-E** [potree/PotreeConverter#491]
use cmd 
Converter.exe D:\pointclouds\1608255034200.las  -o D:\pointclouds\data_converted11 --generate-page pageName

Expect to generate a lot of small bin files and some sample HTML, JS files 

Actually, generate hierarchy.bin ,metadata.json,octree.bin,tmpChunkRoots.bin
have no html files and octree.bin too big.

is that correctly ?

**Comment by Hutch07** [comment]
That is correct.  PotreeConverter 2.0 only makes those files.  Make sure you follow the instructions in potree  _In Potree, modify one of the examples with following load command:_  If you download the latest PotreeDesktop you should be able to view these files.
[PotreeDesktop](https://github.com/potree/PotreeDesktop)

**Comment by lastshot-E** [comment]
tks for your answer, can you tell me which PotreeConverter's version can generate like example lion_takanawa_las?
split a big las files to many small las files and index file cloud.js.

**Comment by midnight-dev** [comment]
@lastshot-E You want [PotreeConverter 1.7](https://github.com/potree/PotreeConverter/releases/tag/1.7). The older version has better caching behavior **but** it is single threaded and is significantly slower during conversion than version 2.0 and up. Also, operations like uploading the LAS/LAZ/binary files to your server can be much, much slower if you have many files.

Hope this helps. Good luck.

**Comment by lastshot-E** [comment]
tks for your answer,it works to me
