### ISSUE TITLE
Cannot start PotreeConverter on Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by joseluislandivars** [potree/PotreeConverter#500]
I followed these instructions to install Potree

`$ sudo apt-get install python-software-properties git
$ sudo apt-get install build-essential cmake g++
$ sudo apt-get install libboost-all-dev
$ sudo apt-get install cmake-curses-gui
$ sudo apt-get install gcc

LAStools:
$ git clone https://github.com/m-schuetz/LAStools.git
$ cd LAStools/LASzip
$ mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release ..
$ make

Potree Converter:
$ git clone https://github.com/potree/PotreeConverter.git
$ cd PotreeConverter
$ mkdir build && cd build  
$ sudo cmake -DCMAKE_BUILD_TYPE=Release -DLASZIP_INCLUDE_DIRS=/home/ubuntu/LAStools/LASzip/dll -DLASZIP_LIBRARY=/home/ubuntu/LAStools/LASzip/build/src/liblaszip.so ..
$ sudo make
$ sudo make install
$ sudo ln -s ~/LAStools/LASzip/build/src/liblaszip.so /usr/lib
$ PotreeConverter -h`

I believe everything went well, but when I execute PotreeConverter -h. I get :
`PotreeConverter: command not found`

**Comment by Takieddinex** [comment]
Hey, I have the same problem if you could tell me how did you do to make it start please
