### ISSUE TITLE
What's the coordinate system of boundingBox in the file named cloud.js 

### ISSUE THREAD

**Issue by tequila1227** [potree/PotreeConverter#502]
I want to know the coordinate system of tightBoundingBox in the file named cloud.js.

Here is the content of this file:

```js
{
    "version": "1.7",
    "octreeDir": "data",
    "points": 177042450,
    "boundingBox": {
        "lx": -63.312386108398438,
        "ly": -108.20909936523438,
        "lz": -3.2015465030670167,
        "ux": 74.74178178405762,
        "uy": 29.845068527221686,
        "uz": 134.85262138938905
    },
    "tightBoundingBox": {
        "lx": -63.312386108398438,
        "ly": -108.20909936523438,
        "lz": -3.2015465030670167,
        "ux": 74.74178178405762,
        "uy": 29.845068527221686,
        "uz": 134.85262138938905
    },
    "pointAttributes": [
        "POSITION_CARTESIAN",
        "COLOR_PACKED",
        "NORMAL_OCT16"
    ],
    "spacing": 0.95646733045578,
    "scale": 0.001,
    "hierarchyStepSize": 5,
    "hash": -8125634920082186753
}
```

Moreover, I want to transform it to the WGS84 system to get the longtitude and latitude value of the point consists of (lx,ly,lz) and the point consists of (ux,uy,uz).

How can I make a transformation?

**Comment by ditlef** [comment]
The PotreeConverter outputs data in the coordinates system of the input files.
To get Lat/Lon you should convert the input data.
There are several tools available for LAS coordinate conversion.
Don't be tempted to do your own conversion of the outputs.
