### ISSUE TITLE
Problem with any version after 1.6 

### ISSUE THREAD

**Issue by somemetalfan** [potree/PotreeConverter#515]
I was having a problem with what seemed to be intensity, that has been reported, (from what I've found), two other times in Potree's issues:
https://github.com/potree/PotreeConverter/issues/203
https://github.com/potree/PotreeConverter/issues/295
Where everything appeared either all white with the desktop version and all black with the code. With las2las I altered the intensity to 256 but still no change in potree.
I ran: "PotreeConverter.exe $file -o $dir --material INTENSITY --output-attributes INTENSITY --generate-page index" and nothing happened. But ran the exact same thing with PotreeConverter 1.6 and it worked. 
This was the representation with the problem:
![image](https://user-images.githubusercontent.com/55692456/116291836-f43f9600-a78c-11eb-8bd0-cc43436ddb3b.png)

and without:
![image](https://user-images.githubusercontent.com/55692456/116290613-9199ca80-a78b-11eb-81aa-83acfef51463.png)

What should I be doing to get PotreeConverter 2.1 to work?

**Comment by smcavoy12** [comment]
There's a known issue with this, 1.6 used to automatically scale the intensity range, now with everything else we need to specify it. try adding a line like this under the material section of of the pointcloud loader coade

`

material.activeAttributeName = "intensity";
pointcloud.material.intensityRange = [0,65535];

`

**Comment by midnight-dev** [comment]
Keep in mind that CLI parameters have changed since 2.0+ is a new major version. The same commands should work between 1.6 and 1.7 **but not** between 1.6 and 2.1. See #512 for a list of acceptable parameters. I think setting the material at runtime with the snippet above should do the trick, but the intensity range should also be set manually if it's appearing completely black.

**Comment by JoseGoncalves** [comment]
May I know why the `--material` parameter was dropped in 2.1?
It would be helpful for users that want to visualize pointclouds with only intensity to have a way to set this in PotreeConverter, instead of having to tune the generated web page.
