### ISSUE TITLE
BoundingBox value is wrong

### ISSUE THREAD

**Issue by Davidwang007** [potree/PotreeConverter#582]
potree file format: v2.0

The metadata.json file created by this converter ,used potree file format v2.0 。

The boundingBox values in this file are not crrect， and this lead to wrong octree sub node result when rendering with camera.  any one else has the same problem ?

   "boundingBox": {   
                "min": [-220.08323669433594, -203.12521362304688, -46.790615081787109], 
                "max": [274.00614929199219, 290.96417236328125, 447.29877090454102]
        },

**Comment by rdk01** [comment]
I also get the wrong bounding box with the new converter.  The position attribute contains correct values, but the bounding box has different values. 

```
{
	"version": "2.0",
	...
	"boundingBox": {
		"min": [-21311, 536, -1685], 
		"max": [-2622, 19225, 17004]
	},
	...
	"attributes": [
		{
			"name": "position",
			"description": "",
			"size": 12,
			"numElements": 3,
			"elementSize": 4,
			"type": "int32",
			"min": [-21311, 536, -1685],
			"max": [-2622, 4575, 1363]
		},
		...
	]
}

```

**Comment by Davidwang007** [comment]
at last got the reason,the point position should add the offset value. thanks for all .
