### ISSUE TITLE
Multi-core support

### ISSUE THREAD

**Issue by dkastl** [potree/PotreeConverter#60]
It may decrease the processing time if multi-core processors would be supported.

**Comment by chiccorusso** [comment]
Is OpenMP (http://openmp.org/wp/) a feasible option?

**Comment by ghgr** [comment]
I think it would be more scalable to be able to append points to an existing tree. And then just:
for i in *.las; do ./Potreeconverter --final-tree final_tree $i; done
You could even store the final_tree in a shared folder, and run it in a cluster.

**Comment by s093294** [comment]
Beeing able to combine the result of several call to potreeconverter would be nice. Such one can distribute the conversion of a large point cloud given in parts of larger grid.

**Comment by m-schuetz** [comment]
I also think that parallel conversion of multiple converter instances and merging afterwards could work well.

**Comment by randomluck17** [comment]
Are there any advancements in this area? I'm currently working with point clouds in *.laz format over 20 GB each with point clouds up to 60 GB each and it takes ages. I'd also be fine with a workaround and have looked here and there but don't have enough knowledge to even know what to do exactly.

**Comment by m-schuetz** [comment]
Currently working on a complete rewrite of the converter. It'll be much faster and produce ~3 files instead of thousands to millions of files. Will still take a month or two and with some luck our grant proposal will be accepted, which means we'll get to make it even faster in the future.

**Comment by m-schuetz** [comment]
Closing this here since this issue is a bit outdated, and support for it is coming soon..
