### ISSUE TITLE
Issue While Building Potree 1.6 in Ubuntu 22.04 jammy version

### ISSUE THREAD

**Issue by paidiakileswar** [potree/PotreeConverter#654]
![image](https://github.com/potree/PotreeConverter/assets/155959310/9b82046f-e7eb-4258-8e34-8a82e797cf87)

My commands :
```
wget https://github.com/potree/PotreeConverter/archive/refs/tags/1.6.zip
unzip 1.6.zip
cd PotreeConverter-1.6
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release \
         -DLASZIP_INCLUDE_DIRS=/usr/include/laszip \
         -DLASZIP_LIBRARY=/usr/lib/liblaszip.so \
         -DCMAKE_INSTALL_PREFIX=/usr
make && make install
```

**Comment by paidiakileswar** [comment]
Solved


I included 
`#include<limits>`


In header
AABB.h

Hence it solved the issue

Thanks for no reply 🙃

**Comment by youhuiji** [comment]
> Solved
> 
> I included `#include<limits>`
> 
> In header AABB.h
> 
> Hence it solved the issue
> 
> Thanks for no reply 🙃

Could you please share the compiled binary file？
