### ISSUE TITLE
Better output to stdout

### ISSUE THREAD

**Issue by chiccorusso** [potree/PotreeConverter#88]
I think that the textual output should be more concise and automatically readable, for example to allow it to be feeded to a graphing software like gnuplot to make some performance charts.

**Comment by m-schuetz** [comment]
Do you have some specific suggestions? 
There's also this relevant issue about different log levels: https://github.com/potree/PotreeConverter/issues/19

**Comment by chiccorusso** [comment]
Well, I just think that every line should have the same structure, like
```
processed 123000 points in 567.897 seconds
```
just to be sure that relevant information (points and time) are always on the same columns.

**Comment by m-schuetz** [comment]
Sounds good. Maybe also also with the number of points that have been written and a semicolon to seperate each measure, like this:

```
123,000,000 points processed; 45,678 points written; 234.456 seconds passed
```

**Comment by chiccorusso** [comment]
Yeah. I'd prepend a label with the phase, in case of multiple phase conversion. By now, for example I am working on tiling:
```
tiling: 123,000,000 points processed; 45,678 points written; 234.456 seconds passed
indexing: 123,000,000 points processed; 45,678 points written; 234.456 seconds passed
```

**Comment by m-schuetz** [comment]
Ok, I'll do this today. 
And in the course of it, also fix the points written number (https://github.com/potree/PotreeConverter/issues/86)

**Comment by m-schuetz** [comment]
Done: https://github.com/potree/PotreeConverter/commit/7de13ca60927eb168ba564343489466ebef30bff

Output looks like this, now:

```
reading D:\temp\points_written\lion_takanawa_oriented.las
INDEXING: 1,000,000 points processed; 284,813 points written; 4.305 seconds passed
INDEXING: 2,000,000 points processed; 592,936 points written; 9.034 seconds passed
INDEXING: 3,000,000 points processed; 936,978 points written; 14.276 seconds passed
INDEXING: 4,000,000 points processed; 1,322,288 points written; 19.722 seconds passed
closing writer

conversion finished
4,018,390 points were processed and 1,336,814 points ( 33.2674% ) were written to the output.
duration: 20.408s
```
