### ISSUE TITLE
Question: Converting LAS file vertically stacks  all points

### ISSUE THREAD

**Issue by lyaunzbe** [potree/PotreeConverter#95]
Hello! I'm having an issue where, whenever I try to use PotreeConverter with a .LAS file, which I'm generating using Agisoft Photoscan, I get the following:
![screen shot 2015-01-20 at 3 29 17 pm](https://cloud.githubusercontent.com/assets/28675/5828480/8d768fd6-a0b9-11e4-95fe-9027f68a85e2.png)

I've tried different variations on scale, spacing, etc., but they still all stack in a single vertical line. Any help would be greatly appreciated. I can also provide a link to the .LAS file I'm working with if that helps. I know this is a .LAS file, as I have been able to view it other applications, including plas.io for example.

Thank you!

**Comment by m-schuetz** [comment]
Hi! 

> I can also provide a link to the .LAS file I'm working with if that helps.

Yes, please send me a link so I can take a look at it.

**Comment by lyaunzbe** [comment]
Thanks for the quick response! Here is a link to one of the .LAS files I've tried to convert.
https://app.box.com/s/bqpwc1em8e7i8htl5ohaqksymuvs8509

**Comment by m-schuetz** [comment]
Actually, someone else had this problem before: https://github.com/potree/potree/issues/52

He said the point cloud is in lat and long coordinates. I'm also having problems watching your file with cloud compare and lasview. With plas.io, I have to specify "scale x/y to meters" or else I'll also get a straight line.

I'm afraid las files with coordinates like this are not supported by potree at the moment. You'll have to somehow get them into a common format with a uniform unit along all axes.

According to the header, the las file was produced by skycatch, not photoscan. Could you maybe try the las file that was produced by photoscan instead? 

Watch out for the scale factor and the min/max values in the las header. If scale x/y is unusually small compared to scale z and min xy are roughly equal to max xy, then you're likely to encounter this problem:

```
scale factor x y z:         0.0000001 0.0000001 0.01
offset x y z:               -122.40000000000001 37.759999999999998 -100
min x y z:                  -122.3927227 37.7642263 -41.59
max x y z:                  -122.3887810 37.7670101 56.38
```

**Comment by lyaunzbe** [comment]
Ahh yes, the point cloud is indeed in lat/long coordinates. Do you happen to know how I would go about converting it into xyz coordinates (what tool to use: libLAS perhaps)?

Thanks for all your help so far, really appreciated!

**Comment by lyaunzbe** [comment]
So, I just decided that instead of banging my head against the wall, trying to reproject my WGS84 LAS to NAD83 (UTM10N), it would be simpler to just export my LAS in NAD83 in the first place. PotreeConverter works as expected when I do this. Thanks again for all your help and quick response time!

**Comment by m-schuetz** [comment]
Good to hear it worked out!
Send me a link once you've got something online! :)

**Comment by shutterrev** [comment]
Just found this thread, was having the same issue due to exporting .las from Photoscan in Lat/Long/ Was frustrating because I thought it was an issue with how I have converter set up, but then I tried it on a different las projected in UTM and that worked fine. Sounds like this is the fix! Thanks!
